Livecheckables/gtk-vnc.rb, Livecheckables/libosinfo.rb, Livecheckables/libsoup-with-gnome.rb, Livecheckables/libvirt-glib.rb, Livecheckables/spice-gtk.rb, Livecheckables/spice-protocol.rb, Livecheckables/usbredir.rb, Livecheckables/virt-manager.rb, Livecheckables/virt-viewer.rb
Hi! In case you are still maintaining homebrew-livecheck, here are some more formulas to add to Livecheckables.
=> Add livecheckables related to virt-manager and dependencies

Livecheckables/libsoup-with-gnome.rb, Livecheckables/libsoup.rb, Livecheckables/spice-gtk.rb, Livecheckables/spice-protocol.rb, Livecheckables/usbredir.rb
Minor updates to livecheckables.
=> Update livecheckables of virt-manager dependencies

livecheck/euristic.rb
rather than the standard SourceForge check.
=> euristic: use custom livecheck for remake

livecheck/euristic.rb
camlp5, avf, bashdb, icoutils and dvdrtools
=> euristic: honor more custom livechecks

Livecheckables/curl.rb
```
Error: redirection forbidden: http://curl.haxx.se/download/ -> https://curl.haxx.se/download/
```
=> curl: update livecheck

Livecheckables/php.rb
Adds a check for php, not sure if this would work with the older php versions in the list though,
=> php: add livecheck

cmd/brew-livecheck.rb
=> external command styled help

cmd/brew-livecheck.rb
=> skip checking versioned formulae without a livecheck

Livecheckables/awscli.rb, Livecheckables/bash-completion@2.rb, Livecheckables/graphviz.rb, Livecheckables/guile.rb, Livecheckables/intltool.rb, Livecheckables/libvirt-glib.rb, Livecheckables/ninja.rb, Livecheckables/osinfo-db-tools.rb, Livecheckables/osinfo-db.rb, Livecheckables/pixman.rb, Livecheckables/shared-mime-info.rb, Livecheckables/spice-gtk.rb, Livecheckables/spice-protocol.rb, Livecheckables/usbredir.rb, Livecheckables/virt-manager.rb, Livecheckables/virt-viewer.rb
Effectively re-opening #106 without GNOME-related packages.
=> Add livecheckables

livecheck/extend/formulary.rb
Minimal changes to enable per-tap livecheckables.
Need advice of Ruby experts on how to better inject code into `load_formula` of `formulary.rb`.
=> per-tap livecheckables

Livecheckables/unar.rb
=> unar: add livecheck

Livecheckables/libcerf.rb, Livecheckables/libev.rb, Livecheckables/libomp.rb, Livecheckables/libvterm.rb, Livecheckables/lzo.rb, Livecheckables/rtmpdump.rb
Added livechecks for libcerf, rtmpdump, lzo, libvterm, libomp, and libev.
=> Add livechecks

Livecheckables/byobu.rb, Livecheckables/intltool.rb, livecheck/euristic.rb
Generalize livechecks for `https://launchpad.net/<package-name>`
=> Generalize launchpad livechecks

Livecheckables/socat.rb
Add Livecheckable for `socat`.
=> socat: add livecheck

Livecheckables/clang-format.rb
=> clang-format: add livecheck

Livecheckables/frei0r.rb
=> frei0r: add livecheck

Livecheckables/leptonica.rb
=> leptonica: add livecheck

Livecheckables/minimal-racket.rb
=> minimal-racket: add livecheck

Livecheckables/libbluray.rb
=> libbluray: add livecheck

Livecheckables/lynx.rb
=> lynx: add livecheck

Livecheckables/spandsp.rb
=> spandsp: add livecheck

Livecheckables/siege.rb
=> siege: add livecheck

Livecheckables/rsync.rb
=> rsync: add livecheck

Livecheckables/tokyo-cabinet.rb
=> tokyo-cabinet: add livecheck

Livecheckables/speex.rb
=> speex: add livecheck

cmd/brew-livecheck.rb
This will fix the tool. The RuboCop changes were done automatically by my editor.
=> brew-livecheck: fix ARGV.flag removal and RuboCop.

Livecheckables/bonnie++.rb
The upstream page url changed.
=> bonnie++: update livecheckable regex

cmd/livecheck.rb
This PR adds a new `--json` option.
If passed, `livecheck` will output the informations in JSON format.
=> livecheck: add possibility to output in JSON

Livecheckables/aqbanking.rb
The url and regex needed to be changed.
=> aqbanking: update Livecheckable

Livecheckables/avfs.rb
The regex wasn't matching the current page, I simplified it to obtain the correct result.
=> avfs: update Livecheckable regex

Livecheckables/a52dec.rb
Adding livecheckable for `a52dec`.
=> a52dec: add livecheckable

Livecheckables/aacgain.rb
Adding livecheckable for `aacgain`.
=> aacgain: add livecheckable

Livecheckables/abuse.rb
Adding livecheckable for `abuse`.
=> abuse: add livecheckable

livecheck/heuristic.rb
The heuristic currently creates GitHub repo URLs in a way that doesn't work if the starting URL isn't already in a state where removing any trailing slash and appending ".git" would produce the Git repository. It may be more appropriate to reduce the URL down to the user/repo portion (e.g., `https://github.com/user/repo`) before trying to append ".git".
For example`bulk_downloader` uses a wiki URL as the homepage (https://github.com/simsong/bulk_extractor/wiki), so the proposed Git repo URL is https://github.com/simsong/bulk_extractor/wiki.git, which doesn't work. With these modifications, a livecheck for `bulk_downloader` correctly identifies the Git repo at https://github.com/simsong/bulk_extractor.git.
Other examples include: amap, browser, denominator, moco, sloc, sshtrix, …
=> heuristic: skip gists, improve github repo url creation

.github/workflows/tests.yml, livecheck/heuristic.rb
- `brew update-reset` before checkout, should close: #295 
- set up the tap in correct directory
- use versioned actions/checkout action
- remove noop code
- set HOMEBREW_NO_AUTO_UPDATE
- fix style of `heuristic.rb` file
=> workflows: update

livecheck/heuristic.rb
As discussed in #300, the GNOME stategy  doesn't restrict matching to stable versions (i.e., using the "even-numbered minor versions are stable" scheme).  Some GNOME versions also use x.90+ as development versions, so this wrinkle is also accounted for in the regex.
This PR restricts the versions in the GNOME strategy by default, unless the package name is in the `gnome_devel_whitelist` array. The array members here are borrowed from `Homebrew/dev-cmd/audit.rb`, omitting the version numbers and `pygtkglext` (which has been deleted from Homebrew), and renaming `libart` to correspond with the package name (`libart_lgpl`).
This fixes version-matching for nearly all GNOME-related formulae but some of these will need subsequent livecheckables to address additional issues:
* gtk+: Restrict to …
=> heuristic: add gnome.org version restrictions

Livecheckables/gwenhywfar.rb
```
$ brew livecheck gwenhywfar
Error: gwenhywfar: Unable to get versions
```
```
$ brew livecheck gwenhywfar
gwenhywfar : 4.20.2 ==> 5.2.0
```
=> gwenhywfar: update url and regex

Livecheckables/suite-sparse.rb
```
$ brew livecheck suite-sparse
suite-sparse : 5.7.1 ==> 5.7.1
```
=> suite-sparse: update url and regex

Livecheckables/sound-touch.rb
```
$ brew livecheck sound-touch
sound-touch : 2.1.2 ==> 2.1.2
```
=> sound-touch: update url and regex

Livecheckables/rakudo-star.rb
```
$ brew livecheck rakudo-star
rakudo-star : 2020.01 ==> 2020.01
```
=> rakudo-star: update url and regex

Livecheckables/rabbitmq.rb
```
$ brew livecheck rabbitmq
rabbitmq : 3.8.2 ==> 3.8.2
```
=> rabbitmq: update url and regex

Livecheckables/telegraf.rb
```
$ brew livecheck telegraf
telegraf : 1.13.4 ==> 1.13.4
```
=> telegraf: update url and regex

Livecheckables/scamper.rb
```
$ brew livecheck scamper
scamper : 20191102 ==> 20191102
```
=> scamper: update url and regex

Livecheckables/imageoptim-cli.rb
```
$ brew livecheck imageoptim-cli --debug
...
3.0.2 => #<Version:0x00007fd335925f58 @version="3.0.2", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 0>, #<Version::NumericToken 2>]>
issue-67 => #<Version:0x00007fd335925e68 @version="67", @tokens=[#<Version::NumericToken 67>]>
issue-67.2 => #<Version:0x00007fd335925d50 @version="67.2", @tokens=[#<Version::NumericToken 67>, #<Version::NumericToken 2>]>
imageoptim-cli (guessed) : 3.0.2 ==> 67.2
```
```
$ brew livecheck imageoptim-cli --debug
...
3.0.2 => #<Version:0x00007fe309992d90 @version="3.0.2", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 0>, #<Version::NumericToken 2>]>
imageoptim-cli : 3.0.2 ==> 3.0.2
```
=> imageoptim-cli: update url and regex

Livecheckables/speech-tools.rb
<details>
<summary>brew livecheck speech-tools --debug</summary>
```
Trying with url http://festvox.org/packed/festival/?C=M&O=D
Using page_match("http://festvox.org/packed/festival/?C=M&O=D", "(?-mix:href="(\d+(?:\.\d+)+)\/">)")
2.5, 2.4, 2.1, 2.0.95, 1.96, 1.95, 1.4.3, 1.4.2, 1.4.1
2.5 => #<Version:0x00007f824b92de00 @version="2.5", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 5>]>
2.4 => #<Version:0x00007f824b92ddb0 @version="2.4", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 4>]>
2.1 => #<Version:0x00007f824b92dd38 @version="2.1", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 1>]>
2.0.95 => #<Version:0x00007f824b92dcc0 @version="2.0.95", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>, #<Version::NumericToken 95>]>
1.96 => …
```
=> speech-tools: update url and regex

Livecheckables/pjproject.rb
```
$ brew livecheck pjproject
pjproject : 2.10 ==> 2.10
```
=> pjproject: update url and regex

Livecheckables/netdata.rb
```
$ brew livecheck netdata
netdata : 1.20.0 ==> 1.20.0
```
=> netdata: update url and regex

Livecheckables/libupnp.rb
```
$ brew livecheck libupnp
libupnp : 1.12.0 ==> 1.12.0
```
=> libupnp: update url and regex

Livecheckables/librdkafka.rb
```
$ brew livecheck librdkafka
librdkafka : 1.3.0 ==> 1.3.0
```
=> librdkafka: update url and regex

Livecheckables/opencv@2.rb
```
$ brew livecheck opencv@2
opencv@2 : 2.4.13.7 ==> 2.4.13.7
```
=> opencv@2: update url and regex

Livecheckables/libu2f-server.rb
```
$ brew livecheck libu2f-server
libu2f-server : 1.1.0 ==> 1.1.0
```
=> libu2f-server: update url

Livecheckables/latex2html.rb
```
$ brew livecheck latex2html
latex2html : 2020 ==> 2020
```
=> latex2html: update url and regex

Livecheckables/kapacitor.rb
release url, https://github.com/influxdata/kapacitor/releases
```
$ brew livecheck kapacitor
kapacitor : 1.5.4 ==> 1.5.4
```
=> kapacitor: update url and regex

.github/lock.yml, .github/no-response.yml, .github/stale.yml, .github/support.yml
Files are essentially the same as .github ones, https://github.com/Homebrew/.github/tree/master/.github
=> Update .github files to ref .github ones

Livecheckables/entr.rb
```
$ brew livecheck entr
entr : 4.4 ==> 4.4
```
=> entr: update url and regex

Livecheckables/cling.rb
https://github.com/root-project/cling/releases
```
$ brew livecheck cling
cling : 0.6 ==> 0.6
```
=> cling: update url and regex

Livecheckables/gdb.rb
With the change
```
$ brew livecheck gdb
gdb : 9.1 ==> 9.1
```
=> gdb: update url and regex

Livecheckables/detekt.rb
```
$ brew livecheck detekt
detekt (guessed) : 1.5.1 ==> 13.2
```
```
$ brew livecheck detekt
detekt : 1.5.1 ==> 1.6.0
```
=> detekt: add livecheckable

Livecheckables/dita-ot.rb
```
$ brew livecheck dita-ot
dita-ot (guessed) : 3.4 ==> 19_stable
```
<details>
<summary>brew livecheck dita-ot --debug</summary>
```
Trying with url https://github.com/dita-ot/dita-ot/releases/download/3.4/dita-ot-3.4.zip
Possible git repo detected at https://github.com/dita-ot/dita-ot.git
1.7.1 => #<Version:0x00007f860695d308 @version="1.7.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 7>, #<Version::NumericToken 1>]>
1.7.2 => #<Version:0x00007f860695d218 @version="1.7.2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 7>, #<Version::NumericToken 2>]>
1.7.3 => #<Version:0x00007f860695d150 @version="1.7.3", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 7>, #<Version::NumericToken 3>]>
1.7.4 => #<Version:0x00007f860695d088 @version="1.7.4", …
```
=> dita-ot: add livecheckable

Livecheckables/dnscontrol.rb
```
$ brew livecheck dnscontrol
dnscontrol (guessed) : 2.11 ==> 5609e41703f05f4ad331
```
<details>
<summary>brew livecheck dnscontrol --debug</summary>
```
Trying with url https://github.com/StackExchange/dnscontrol/archive/v2.11.tar.gz
Possible git repo detected at https://github.com/StackExchange/dnscontrol.git
0.2.1 => #<Version:0x00007f971e3de228 @version="0.2.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 2>, #<Version::NumericToken 1>]>
untagged-5609e41703f05f4ad331 => #<Version:0x00007f971e3ddda0 @version="5609e41703f05f4ad331", @tokens=[#<Version::NumericToken 5609>, #<Version::StringToken "e41703">, #<Version::StringToken "f05">, #<Version::StringToken "f4">, #<Version::StringToken "ad331">]>
v0.1.0 => #<Version:0x00007f971e3ddd00 @version="0.1.0", …
```
=> dnscontrol: add livecheckable

Livecheckables/dosbox-x.rb
```
$ brew livecheck dosbox-x
dosbox-x (guessed) : 0.83.0 ==> 201805181700
```
<details>
<summary>brew livecheck dosbox-x --debug</summary>
```
Trying with url https://github.com/joncampbell123/dosbox-x.git
Possible git repo detected at https://github.com/joncampbell123/dosbox-x.git
DOSBox-X-win32-0b7c491db7cc1021f7ff0dbfb99612b99b290bf9 => #<Version:0x00007fc1259b0f08 @version="32-0b7c491db7cc1021f7ff0dbfb99612b99b290bf9", @tokens=[#<Version::NumericToken 32>, #<Version::NumericToken 0>, #<Version::BetaToken "b7">, #<Version::StringToken "c491">, #<Version::StringToken "db7">, #<Version::StringToken "cc1021">, #<Version::StringToken "f7">, #<Version::StringToken "ff0">, #<Version::StringToken "dbfb99612">, #<Version::BetaToken "b99">, #<Version::BetaToken "b290">, #<Version::StringToken …
```
=> dosbox-x: add livecheckable

Livecheckables/elinks.rb
```
$ brew livecheck elinks
elinks (guessed) : 0.11.7 ==> 0.12pre6
```
<details>
<summary>brew livecheck elinks --debug</summary>
```
Trying with url http://elinks.cz/elinks.git
Possible git repo detected at http://elinks.cz/elinks.git
elinks-0.11.0 => #<Version:0x00007ff97e254d18 @version="0.11.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 11>, #<Version::NumericToken 0>]>
elinks-0.11.1 => #<Version:0x00007ff97e254c00 @version="0.11.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 11>, #<Version::NumericToken 1>]>
elinks-0.11.2 => #<Version:0x00007ff97e254b10 @version="0.11.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 11>, #<Version::NumericToken 2>]>
elinks-0.11.3 => #<Version:0x00007ff97e254a20 @version="0.11.3", …
```
=> elinks: add livecheckable

Livecheckables/faiss.rb
```
$ brew livecheck faiss
faiss (guessed) : 1.6.1 ==> 20180223
```
<details>
<summary>brew livecheck elinks --debug</summary>
```
Trying with url https://github.com/facebookresearch/faiss/archive/v1.6.1.tar.gz
Possible git repo detected at https://github.com/facebookresearch/faiss.git
v1.2.1 => #<Version:0x00007fcde09e41b0 @version="1.2.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 2>, #<Version::NumericToken 1>]>
v1.3.0 => #<Version:0x00007fcde09e40e8 @version="1.3.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 3>, #<Version::NumericToken 0>]>
v1.4.0 => #<Version:0x00007fcde09e4020 @version="1.4.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 4>, #<Version::NumericToken 0>]>
v1.5.0 => #<Version:0x00007fcde09effb0 @version="1.5.0", …
```
=> faiss: add livecheckable

Livecheckables/fifechan.rb
```
$ brew livecheck fifechan
fifechan (guessed) : 0.1.5 ==> 2
```
<details>
<summary>brew livecheck fifechan --debug</summary>
```
Trying with url https://github.com/fifengine/fifechan/archive/0.1.5.tar.gz
Possible git repo detected at https://github.com/fifengine/fifechan.git
0.1.0 => #<Version:0x00007fa61194f8e0 @version="0.1.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 0>]>
0.1.1 => #<Version:0x00007fa61194f818 @version="0.1.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 1>]>
0.1.2 => #<Version:0x00007fa61194f750 @version="0.1.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 2>]>
0.1.3 => #<Version:0x00007fa61194f660 @version="0.1.3", …
```
=> fifechan: add livecheckable

Livecheckables/infer.rb
```
$ brew livecheck infer
infer (guessed) : 0.17.0 ==> 0.17.2
```
<details>
<summary>brew livecheck infer --debug</summary>
```
Trying with url https://github.com/facebook/infer.git
Possible git repo detected at https://github.com/facebook/infer.git
infer-annotation-0.17.1 => #<Version:0x00007fb1fb17ccf8 @version="0.17.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 17>, #<Version::NumericToken 1>]>
infer-annotation-0.17.2 => #<Version:0x00007fb1fb17cc08 @version="0.17.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 17>, #<Version::NumericToken 2>]>
v0.1.0 => #<Version:0x00007fb1fb17cb40 @version="0.1.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 0>]>
v0.1.1 => #<Version:0x00007fb1fb17ca78 @version="0.1.1", …
```
=> infer: add livecheckable

Livecheckables/ortp.rb
Update the Livecheckable with the source url used in the Formula.
=> ortp: update Livecheckable url

Livecheckables/djvulibre.rb
```
$ brew livecheck djvulibre
djvulibre (guessed) : 3.5.27 ==> 18n-mergepoint
```
<details>
<summary>brew livecheck djvulibre --debug</summary>
```
Trying with url https://git.code.sf.net/p/djvu/djvulibre-git.git
Possible git repo detected at https://git.code.sf.net/p/djvu/djvulibre-git.git
cygwin_version_3_5_17 => #<Version:0x00007fb88d188060 @version="3_5_17", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 5>, #<Version::NumericToken 17>]>
i18n-branch-point => #<Version:0x00007fb88d193208 @version="18n-branch-point", @tokens=[#<Version::NumericToken 18>, #<Version::StringToken "n">, #<Version::StringToken "branch">, #<Version::PatchToken "p">, #<Version::StringToken "oint">]>
i18n-mergepoint => #<Version:0x00007fb88d193140 @version="18n-mergepoint", …
```
=> djvulibre: add livecheckable

Livecheckables/upscaledb.rb
```
$ brew livecheck upscaledb
upscaledb (guessed) : 2.2.0 ==> 2.2.2
```
<details>
<summary>brew livecheck upscaledb --debug</summary>
```
Trying with url https://github.com/cruppstahl/upscaledb.git
Possible git repo detected at https://github.com/cruppstahl/upscaledb.git
2.0.4 => #<Version:0x00007fccc50eba48 @version="2.0.4", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>, #<Version::NumericToken 4>]>
hamsterdb-1.1.10 => #<Version:0x00007fccc50eb980 @version="1.1.10", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 1>, #<Version::NumericToken 10>]>
hamsterdb-1.1.11 => #<Version:0x00007fccc50eb890 @version="1.1.11", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 1>, #<Version::NumericToken 11>]>
hamsterdb-1.1.12 => #<Version:0x00007fccc50eb7c8 …
```
=> upscaledb: add livecheckable

Livecheckables/tcpflow.rb
```
$ brew livecheck tcpflow
tcpflow (guessed) : 1.5.0 ==> 1.5.2
```
<details>
<summary>brew livecheck tcpflow --debug</summary>
```
Trying with url https://github.com/simsong/tcpflow.git
Possible git repo detected at https://github.com/simsong/tcpflow.git
tcpflow-1.2.5 => #<Version:0x00007fe4f8ba56f0 @version="1.2.5", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 2>, #<Version::NumericToken 5>]>
tcpflow-1.2.7 => #<Version:0x00007fe4f8ba5600 @version="1.2.7", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 2>, #<Version::NumericToken 7>]>
tcpflow-1.2.9 => #<Version:0x00007fe4f8ba5538 @version="1.2.9", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 2>, #<Version::NumericToken 9>]>
tcpflow-1.3.0 => #<Version:0x00007fe4f8ba5470 @version="1.3.0", …
```
=> tcpflow: add livecheckable

Livecheckables/vramsteg.rb
```
$ brew livecheck vramsteg
vramsteg (guessed) : 1.1.0 ==> 110ToMaster
```
<details>
<summary>brew livecheck vramsteg --debug</summary>
```
Trying with url https://github.com/GothenburgBitFactory/vramsteg.git
Possible git repo detected at https://github.com/GothenburgBitFactory/vramsteg.git
Post101ToMaster => #<Version:0x00007f932792dc10 @version="101ToMaster", @tokens=[#<Version::NumericToken 101>, #<Version::StringToken "ToMaster">]>
Post110ToMaster => #<Version:0x00007f932792db48 @version="110ToMaster", @tokens=[#<Version::NumericToken 110>, #<Version::StringToken "ToMaster">]>
Pre101ToMaster => #<Version:0x00007f932792da80 @version="101ToMaster", @tokens=[#<Version::NumericToken 101>, #<Version::StringToken "ToMaster">]>
Pre110ToMaster => #<Version:0x00007f932792d990 …
```
=> vramsteg: add livecheckable

Livecheckables/ctags.rb
before:
```
Error: ctags: undefined method `[]' for nil:NilClass
```
after:
```
ctags : 5.8 ==> 5.8
```
=> ctags: add livecheckable

Livecheckables/rogue.rb
before:
```
rogue (guessed) : 5.4.4 ==> files
```
after:
```
rogue : 5.4.4 ==> 5.4.4
```
=> rogue: add livecheckable

Livecheckables/zlib.rb
before:
```
zlib (guessed) : 1.2.11 ==> files
```
after:
```
zlib : 1.2.11 ==> 1.2.11
```
=> zlib: add livecheckable

Livecheckables/residualvm.rb
before:
```
residualvm (guessed) : 0.3.1 ==> 0.4.0git
```
after:
```
residualvm : 0.3.1 ==> 0.3.1
```
=> residualvm: add livecheck

Livecheckables/buildkit.rb
```
$ brew livecheck buildkit
buildkit : 0.6.4 ==> 0.7.0
```
<details>
<summary>brew livecheck buildkit --debug</summary>
```
Trying with url https://github.com/moby/buildkit.git
Possible git repo detected at https://github.com/moby/buildkit.git
v0.3.0 => #<Version:0x00007fb8f9988b40 @version="0.3.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 3>, #<Version::NumericToken 0>]>
v0.3.1 => #<Version:0x00007fb8f9988a00 @version="0.3.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 3>, #<Version::NumericToken 1>]>
v0.3.2 => #<Version:0x00007fb8f9988898 @version="0.3.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 3>, #<Version::NumericToken 2>]>
v0.3.3 => #<Version:0x00007fb8f9988758 @version="0.3.3", @tokens=[#<Version::NumericToken 0>, …
```
=> buildkit: fix livecheck issue

Livecheckables/arduino-cli.rb
```
$ brew livecheck arduino-cli
arduino-cli (guessed) : 0.9.0 ==> 2
```
<details>
<summary>brew livecheck arduino-cli --debug</summary>
```
Trying with url https://github.com/arduino/arduino-cli.git
Possible git repo detected at https://github.com/arduino/arduino-cli.git
0.0.100 => #<Version:0x00007fd6889e3908 @version="0.0.100", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 0>, #<Version::NumericToken 100>]>
0.0.99 => #<Version:0x00007fd6889e3840 @version="0.0.99", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 0>, #<Version::NumericToken 99>]>
0.4.0 => #<Version:0x00007fd6889e2d28 @version="0.4.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 4>, #<Version::NumericToken 0>]>
0.4.0-armv6 => #<Version:0x00007fd6889e2c60 @version="0.4.0-armv6", …
```
=> arduino-cli: add livecheckable

Livecheckables/zbar.rb
```
$ brew livecheck zbar
zbar (guessed) : 0.10 ==> 1.3.1
```
<details>
<summary>brew livecheck zbar --debug</summary>
```
Trying with url https://github.com/ZBar/ZBar.git
Possible git repo detected at https://github.com/ZBar/ZBar.git
0.1 => #<Version:0x00007f87d81f5998 @version="0.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>]>
0.10 => #<Version:0x00007f87d81f58d0 @version="0.10", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>]>
0.2 => #<Version:0x00007f87d81f5808 @version="0.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 2>]>
0.3 => #<Version:0x00007f87d81f5740 @version="0.3", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 3>]>
0.4 => #<Version:0x00007f87d81f5678 @version="0.4", @tokens=[#<Version::NumericToken 0>, …
```
=> zbar: add livecheckable

Livecheckables/ddclient.rb
```
$ brew livecheck ddclient
ddclient (guessed) : 3.9.0 ==> 3.9.1
```
<details>
<summary>brew livecheck ddclient --debug</summary>
```
Trying with url https://github.com/wimpunk/ddclient.git
Possible git repo detected at https://github.com/wimpunk/ddclient.git
v3.8.2 => #<Version:0x00007fe422915560 @version="3.8.2", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 8>, #<Version::NumericToken 2>]>
v3.8.3 => #<Version:0x00007fe422915448 @version="3.8.3", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 8>, #<Version::NumericToken 3>]>
v3.9.0 => #<Version:0x00007fe422915330 @version="3.9.0", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 9>, #<Version::NumericToken 0>]>
v3.9.1 => #<Version:0x00007fe422915240 @version="3.9.1", …
```
=> ddclient: add livecheckable

Livecheckables/allegro.rb
```
$ brew livecheck allegro
allegro (guessed) : 5.2.6.0 ==> 4418
```
<details>
<summary>brew livecheck allegro --debug</summary>
```
Trying with url https://github.com/liballeg/allegro5.git
Possible git repo detected at https://github.com/liballeg/allegro5.git
4.3.0 => #<Version:0x00007f83e69cc9f0 @version="4.3.0", @tokens=[#<Version::NumericToken 4>, #<Version::NumericToken 3>, #<Version::NumericToken 0>]>
4.3.1 => #<Version:0x00007f83e69cc928 @version="4.3.1", @tokens=[#<Version::NumericToken 4>, #<Version::NumericToken 3>, #<Version::NumericToken 1>]>
4.3.10 => #<Version:0x00007f83e69cc838 @version="4.3.10", @tokens=[#<Version::NumericToken 4>, #<Version::NumericToken 3>, #<Version::NumericToken 10>]>
4.4.0 => #<Version:0x00007f83e69cc770 @version="4.4.0", …
```
=> allegro: add livecheckable

Livecheckables/akka.rb
```
$ brew livecheck akka
akka (guessed) : 2.4.20 ==> 14v12p01
```
<details>
<summary>brew livecheck akka --debug</summary>
```
Trying with url https://downloads.typesafe.com/akka/akka_2.11-2.4.20.zip
Trying with url https://github.com/akka/akka
Possible git repo detected at https://github.com/akka/akka.git
1.0-M1 => #<Version:0x00007fe5fe21a4f8 @version="1.0-M1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::StringToken "M1">]>
2.4.9-2.12-M4 => #<Version:0x00007fe5fe21a430 @version="2.4.9-2.12-M4", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 4>, #<Version::NumericToken 9>, #<Version::NumericToken 2>, #<Version::NumericToken 12>, #<Version::StringToken "M4">]>
akka-stream-and-http-experimental-0.10 => #<Version:0x00007fe5fe21a368 …
```
=> akka: add livecheckable

livecheck/heuristic.rb
Factoring out github/sourceforge/gnu special cases into array variables to standardize the approach. Should provide minor speed improvements.
=> Factor out special cases into arrays

Livecheckables/csvq.rb
```
$ brew livecheck csvq
csvq : 1.12.4 ==> 1.12.4-pr.2
```
<details>
<summary>brew livecheck csvq --debug</summary>
```
Trying with url https://github.com/mithrandie/csvq/archive/v1.12.4.tar.gz
Possible git repo detected at https://github.com/mithrandie/csvq.git
v0.1.4 => #<Version:0x00007fda1e16c538 @version="0.1.4", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 4>]>
v0.1.5 => #<Version:0x00007fda1e16c470 @version="0.1.5", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 5>]>
v0.1.6 => #<Version:0x00007fda1e16c380 @version="0.1.6", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 6>]>
v0.1.8 => #<Version:0x00007fda1e16c290 @version="0.1.8", …
```
=> csvq: add livecheckable

Livecheckables/coccinelle.rb
```
$ brew livecheck coccinelle
coccinelle (guessed) : 1.0.8 ==> 18.10-cosmic/1.0.7
```
<details>
<summary>brew livecheck coccinelle --debug</summary>
```
Trying with url https://github.com/coccinelle/coccinelle.git
Possible git repo detected at https://github.com/coccinelle/coccinelle.git
1.0.0 => #<Version:0x00007fa12f1ce670 @version="1.0.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 0>]>
1.0.1 => #<Version:0x00007fa12f1cd130 @version="1.0.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 1>]>
1.0.2 => #<Version:0x00007fa12f1cd068 @version="1.0.2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 2>]>
1.0.3 => #<Version:0x00007fa12f1ccf78 @version="1.0.3", …
```
=> coccinelle: add livecheckable

Livecheckables/cryptominisat.rb
```
$ brew livecheck cryptominisat
cryptominisat (guessed) : 5.6.8 ==> 2018
```
<details>
<summary>brew livecheck cryptominisat --debug</summary>
```
Trying with url https://github.com/msoos/cryptominisat/archive/5.6.8.tar.gz
Possible git repo detected at https://github.com/msoos/cryptominisat.git
2.9.11 => #<Version:0x00007fb570abee38 @version="2.9.11", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 9>, #<Version::NumericToken 11>]>
4.2.0 => #<Version:0x00007fb570abed70 @version="4.2.0", @tokens=[#<Version::NumericToken 4>, #<Version::NumericToken 2>, #<Version::NumericToken 0>]>
4.5.2 => #<Version:0x00007fb570abeca8 @version="4.5.2", @tokens=[#<Version::NumericToken 4>, #<Version::NumericToken 5>, #<Version::NumericToken 2>]>
4.5.3 => #<Version:0x00007fb570abebe0 …
```
=> cryptominisat: add livecheckable

Livecheckables/bareos-client.rb
```
$ brew livecheck bareos-client
bareos-client (guessed) : 19.2.6 ==> 20.0.0-pre
```
<details>
<summary>brew livecheck bareos-client --debug</summary>
```
Trying with url https://github.com/bareos/bareos/archive/Release/19.2.6.tar.gz
Possible git repo detected at https://github.com/bareos/bareos.git
Release/12.4.0 => #<Version:0x00007ff5f0a27220 @version="12.4.0", @tokens=[#<Version::NumericToken 12>, #<Version::NumericToken 4>, #<Version::NumericToken 0>]>
Release/12.4.1 => #<Version:0x00007ff5f0a27158 @version="12.4.1", @tokens=[#<Version::NumericToken 12>, #<Version::NumericToken 4>, #<Version::NumericToken 1>]>
Release/12.4.2 => #<Version:0x00007ff5f0a27090 @version="12.4.2", @tokens=[#<Version::NumericToken 12>, #<Version::NumericToken 4>, #<Version::NumericToken 2>]> …
```
=> bareos-client: add livecheckable

Livecheckables/archey.rb
This repo has been archived.
```
$ brew livecheck archey
archey (guessed) : 1.6.0 ==> 1.6.0-pr
```
<details>
<summary>brew livecheck archey --debug</summary>
```
Trying with url https://github.com/obihann/archey-osx.git
Possible git repo detected at https://github.com/obihann/archey-osx.git
1.0 => #<Version:0x00007f9c379ddbb0 @version="1.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>]>
1.1 => #<Version:0x00007f9c379ddac0 @version="1.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 1>]>
1.2 => #<Version:0x00007f9c379dd9d0 @version="1.2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 2>]>
1.3 => #<Version:0x00007f9c379dd908 @version="1.3", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 3>]>
1.4 => #<Version:0x00007f9c379dd840 …
```
=> archey: add livecheckable

Livecheckables/robot-framework.rb
```
$ brew livecheck robot-framework
robot-framework (guessed) : 3.1.2 ==> 3.2b2
```
<details>
<summary>brew livecheck robot-framework --debug</summary>
```
Trying with url https://github.com/robotframework/robotframework.git
Possible git repo detected at https://github.com/robotframework/robotframework.git
2.0 => #<Version:0x00007fb7f3991940 @version="2.0", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>]>
2.0.1 => #<Version:0x00007fb7f3991878 @version="2.0.1", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>, #<Version::NumericToken 1>]>
2.0.2 => #<Version:0x00007fb7f39917b0 @version="2.0.2", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>, #<Version::NumericToken 2>]>
2.0.3 => #<Version:0x00007fb7f39916e8 @version="2.0.3", …
```
=> robot-framework: add livecheckable

Livecheckables/zero-install.rb
```
$ brew livecheck zero-install
zero-install (guessed) : 2.15.1 ==> 4
```
<details>
<summary>brew livecheck zero-install --debug</summary>
```
Trying with url https://github.com/0install/0install.git
Possible git repo detected at https://github.com/0install/0install.git
b2.10 => #<Version:0x00007ffe042733a0 @version="2.10", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 10>]>
gui/v0.10 => #<Version:0x00007ffe042732b0 @version="0.10", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>]>
gui/v0.11 => #<Version:0x00007ffe042731c0 @version="0.11", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 11>]>
gui/v0.12 => #<Version:0x00007ffe042730a8 @version="0.12", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 12>]>
gui/v0.13 => …
```
=> zero-install: add livecheckable

Livecheckables/spice-gtk.rb
Before:
```
spice-gtk : 0.37 ==> 0.37
```
After:
```
spice-gtk : 0.37 ==> 0.38
```
=> spice-gtk: update regex

Livecheckables/apache-brooklyn-cli.rb
```
$ brew livecheck apache-brooklyn-cli
apache-brooklyn-cli (guessed) : 1.0.0 ==> 1.0.0-M1
```
<details>
<summary>brew livecheck apache-brooklyn-cli --debug</summary>
```
Trying with url https://github.com/apache/brooklyn-client/archive/rel/apache-brooklyn-1.0.0.tar.gz
Possible git repo detected at https://github.com/apache/brooklyn-client.git
rel/apache-brooklyn-0.10.0 => #<Version:0x00007f936b1e97f8 @version="0.10.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>, #<Version::NumericToken 0>]>
rel/apache-brooklyn-0.11.0 => #<Version:0x00007f936b1e92a8 @version="0.11.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 11>, #<Version::NumericToken 0>]>
rel/apache-brooklyn-0.12.0 => #<Version:0x00007f936b1e8f60 @version="0.12.0", …
```
=> apache-brooklyn-cli: add livecheckable

Livecheckables/coinutils.rb
```
$ brew livecheck coinutils
coinutils (guessed) : 2.11.4 ==> 2002-11-05
```
<details>
<summary>brew livecheck coinutils --debug</summary>
```
Trying with url https://github.com/coin-or/CoinUtils/archive/releases/2.11.4.tar.gz
Possible git repo detected at https://github.com/coin-or/CoinUtils.git
Clp-1-00-00 => #<Version:0x00007fd01e81b280 @version="1-00-00", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 0>]>
clp-0-94-0 => #<Version:0x00007fd01e81b1b8 @version="0-94-0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 94>, #<Version::NumericToken 0>]>
clp-0-94-1 => #<Version:0x00007fd01e81b0f0 @version="0-94-1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 94>, #<Version::NumericToken 1>]>
release_2002-11-05 => …
```
=> coinutils: add livecheckable

Livecheckables/docbook-xsl.rb
```
$ brew livecheck docbook-xsl
docbook-xsl (guessed) : 1.79.2 ==> 2019-10-28
```
<details>
<summary>brew livecheck docbook-xsl --debug</summary>
```
Trying with url https://github.com/docbook/xslt10-stylesheets/releases/download/release%2F1.79.2/docbook-xsl-nons-1.79.2.tar.bz2
Possible git repo detected at https://github.com/docbook/xslt10-stylesheets.git
ndw-test-001 => #<Version:0x00007fb6fabeab50 @version="001", @tokens=[#<Version::NumericToken 1>]>
release/1.79.1 => #<Version:0x00007fb6fabeaa60 @version="1.79.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 79>, #<Version::NumericToken 1>]>
release/1.79.2 => #<Version:0x00007fb6fabea948 @version="1.79.2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 79>, #<Version::NumericToken 2>]> …
```
=> docbook-xsl: add livecheckable

Livecheckables/dps8m.rb
```
$ brew livecheck dps8m
dps8m (guessed) : 2.0 ==> 7a1
```
<details>
<summary>brew livecheck dps8m --debug</summary>
```
Trying with url https://gitlab.com/dps8m/dps8m.git
Possible git repo detected at https://gitlab.com/dps8m/dps8m.git
0fnp_eis_rework_tandd_fix => #<Version:0x00007f7f98babe08 @version="0fnp_eis_rework_tandd_fix", @tokens=[#<Version::NumericToken 0>, #<Version::StringToken "fnp">, #<Version::StringToken "eis">, #<Version::StringToken "rework">, #<Version::StringToken "tandd">, #<Version::StringToken "fix">]>
1.0-RC6 => #<Version:0x00007f7f98babd68 @version="1.0-RC6", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::RCToken "RC6">]>
1.0-RC7 => #<Version:0x00007f7f98babca0 @version="1.0-RC7", @tokens=[#<Version::NumericToken 1>, …
```
=> dps8m: add livecheckable

Livecheckables/goreman.rb
```
$ brew livecheck goreman
goreman (guessed) : 0.3.5 ==> 93
```
<details>
<summary>brew livecheck goreman --debug</summary>
```
Trying with url https://github.com/mattn/goreman/archive/v0.3.5.tar.gz
Possible git repo detected at https://github.com/mattn/goreman.git
refs/heads/fix-93 => #<Version:0x00007fec598cac10 @version="93", @tokens=[#<Version::NumericToken 93>]>
refs/heads/renovate/gopkg.in-yaml.v2-2 => #<Version:0x00007fec598ca1e8 @version="2-2", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 2>]>
v0.0.10 => #<Version:0x00007fec598c9c20 @version="0.0.10", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 0>, #<Version::NumericToken 10>]>
v0.0.2 => #<Version:0x00007fec598c95b8 @version="0.0.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken …
```
=> goreman: add livecheckable

Livecheckables/dvc.rb
```
$ brew livecheck dvc
dvc (guessed) : 0.92.1 ==> 8ffb59a4189182ec1a9
```
<details>
<summary>brew livecheck dvc --debug</summary>
```
Trying with url https://github.com/iterative/dvc/archive/0.92.1.tar.gz
Possible git repo detected at https://github.com/iterative/dvc.git
0.10.0 => #<Version:0x00007f8cb0949280 @version="0.10.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>, #<Version::NumericToken 0>]>
0.10.1 => #<Version:0x00007f8cb0949190 @version="0.10.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>, #<Version::NumericToken 1>]>
0.10.2 => #<Version:0x00007f8cb0949028 @version="0.10.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>, #<Version::NumericToken 2>]>
0.11.0 => #<Version:0x00007f8cb0948f38 @version="0.11.0", …
```
=> dvc: add livecheckable

Livecheckables/gerbil-scheme.rb
```
$ brew livecheck gerbil-scheme
gerbil-scheme (guessed) : 0.15.1 ==> 0.16-DEV
```
<details>
<summary>brew livecheck gerbil-scheme --debug</summary>
```
Trying with url https://github.com/vyzo/gerbil/archive/v0.15.1.tar.gz
Possible git repo detected at https://github.com/vyzo/gerbil.git
v0.1 => #<Version:0x00007fe5439e7688 @version="0.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>]>
v0.10 => #<Version:0x00007fe5439e74f8 @version="0.10", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>]>
v0.11 => #<Version:0x00007fe5439e6e68 @version="0.11", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 11>]>
v0.12 => #<Version:0x00007fe5439e6800 @version="0.12", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 12>]>
v0.12-DEV => …
```
=> gerbil-scheme: add livecheckable

Livecheckables/nuget.rb
relates to https://github.com/Homebrew/homebrew-core/pull/52939/files#r407134065
```
$ brew livecheck nuget
nuget : 5.4.0 ==> 5.4.0
```
=> nuget: only use recommended latest version

Livecheckables/frege.rb
```
$ brew livecheck frege
frege (guessed) : 3.24.405 ==> 3.25
```
<details>
<summary>brew livecheck frege --debug</summary>
```
Trying with url https://github.com/Frege/frege/releases/download/3.24public/frege3.24.405.jar
Possible git repo detected at https://github.com/Frege/frege.git
3.20 => #<Version:0x00007f9ae63e1970 @version="3.20", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 20>]>
3.20.0 => #<Version:0x00007f9ae63e18a8 @version="3.20.0", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 20>, #<Version::NumericToken 0>]>
3.21 => #<Version:0x00007f9ae63e17e0 @version="3.21", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 21>]>
3.21.151-test => #<Version:0x00007f9ae63e1718 @version="3.21.151-test", @tokens=[#<Version::NumericToken 3>, …
```
=> frege: add livecheckable

Livecheckables/geoserver.rb
```
$ brew livecheck geoserver
geoserver (guessed) : 2.16.2 ==> 2.17
```
<details>
<summary>brew livecheck geoserver --debug</summary>
```
Trying with url https://downloads.sourceforge.net/project/geoserver/GeoServer/2.16.2/geoserver-2.16.2-bin.zip
Possible SourceForge project [geoserver] detectedat https://downloads.sourceforge.net/project/geoserver/GeoServer/2.16.2/geoserver-2.16.2-bin.zip
Using page_match("https://sourceforge.net/projects/geoserver/rss", "(?i-mx:\/geoserver\/([a-zA-Z0-9.]+(?:\.[a-zA-Z0-9.]+)*))")
2.17, files, 2.17, files, 2.17, 2.17, files, 2.17, 2.17, files, 2.17, files, 2.17, 2.17, files, 2.17, 2.17, files, 2.17, files, 2.17, 2.17, files, 2.17, 2.17, files, 2.17, files, 2.17, 2.17, files, 2.17, 2.17, files, 2.17, files, 2.17, 2.17, files, 2.17, 2.17, files, 2.17, …
```
=> geoserver: add livecheckable

Livecheckables/gperftools.rb
```
$ brew livecheck gperftools
gperftools (guessed) : 2.7 ==> 2.7.90
```
<details>
<summary>brew livecheck gperftools --debug</summary>
```
Trying with url https://github.com/gperftools/gperftools.git
Possible git repo detected at https://github.com/gperftools/gperftools.git
google-perftools-1.10 => #<Version:0x00007f8b8c1d0640 @version="1.10", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 10>]>
google-perftools-1.5 => #<Version:0x00007f8b8c1dbf18 @version="1.5", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 5>]>
google-perftools-1.7 => #<Version:0x00007f8b8c1db9c8 @version="1.7", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 7>]>
google-perftools-1.8 => #<Version:0x00007f8b8c1db2c0 @version="1.8", @tokens=[#<Version::NumericToken 1>, …
```
=> gperftools: add livecheckable

Livecheckables/ampl-mp.rb
```
$ brew livecheck ampl-mp
ampl-mp (guessed) : 3.1.0 ==> 20141208
```
<details>
<summary>brew livecheck allegro --debug</summary>
```
Trying with url https://github.com/ampl/mp/archive/3.1.0.tar.gz
Possible git repo detected at https://github.com/ampl/mp.git
1.3.0 => #<Version:0x00007fb23aa4f710 @version="1.3.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 3>, #<Version::NumericToken 0>]>
2.0.0 => #<Version:0x00007fb23aa4f648 @version="2.0.0", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>, #<Version::NumericToken 0>]>
2.0.1 => #<Version:0x00007fb23aa4f558 @version="2.0.1", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>, #<Version::NumericToken 1>]>
2.0.2 => #<Version:0x00007fb23aa4f490 @version="2.0.2", @tokens=[#<Version::NumericToken …
```
=> ampl-mp: add livecheckable

Livecheckables/ncompress.rb
```
$ brew livecheck compress
ncompress (guessed) : 4.2.4.6 ==> 4.2.4.6-old
```
<details>
```
Trying with url https://github.com/vapier/ncompress.git
Possible git repo detected at https://github.com/vapier/ncompress.git
v1.4 => #<Version:0x00007fc34f2281d8 @version="1.4", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 4>]>
v1.6 => #<Version:0x00007fc34f233c90 @version="1.6", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 6>]>
v2.0 => #<Version:0x00007fc34f2333f8 @version="2.0", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 0>]>
v3.0 => #<Version:0x00007fc34f232db8 @version="3.0", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 0>]>
v4.0 => #<Version:0x00007fc34f232a70 @version="4.0", …
```
=> ncompress: add livecheckable

Livecheckables/nng.rb
```
$ brew livecheck nng
nng (guessed) : 1.3.0 ==> 12
```
<details>
```
Trying with url https://github.com/nanomsg/nng/archive/v1.3.0.tar.gz
Possible git repo detected at https://github.com/nanomsg/nng.git
0.1 => #<Version:0x00007fad74a40190 @version="0.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>]>
0.2.0 => #<Version:0x00007fad74a400c8 @version="0.2.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 2>, #<Version::NumericToken 0>]>
0.5.0 => #<Version:0x00007fad74a4bf90 @version="0.5.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 5>, #<Version::NumericToken 0>]>
0.6.0 => #<Version:0x00007fad74a4bec8 @version="0.6.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 6>, #<Version::NumericToken …
```
=> nng: add livecheckable

Livecheckables/ngt.rb
```
$ brew livecheck ngt
ngt (guessed) : 1.9.1 ==> 161216-152050
```
<details>
```
Trying with url https://github.com/yahoojapan/NGT/archive/v1.9.1.tar.gz
Possible git repo detected at https://github.com/yahoojapan/NGT.git
import-161216-152050 => #<Version:0x00007fab7c88ac00 @version="161216-152050", @tokens=[#<Version::NumericToken 161216>, #<Version::NumericToken 152050>]>
v0.4.0 => #<Version:0x00007fab7c88aa98 @version="0.4.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 4>, #<Version::NumericToken 0>]>
v0.4.1 => #<Version:0x00007fab7c88a1b0 @version="0.4.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 4>, #<Version::NumericToken 1>]>
v0.4.2 => #<Version:0x00007fab7c889850 @version="0.4.2", @tokens=[#<Version::NumericToken …
```
=> ngt: add livecheckable

Livecheckables/nzbget.rb
```
$ brew livecheck nzbget
nzbget (guessed) : 21.0 ==> 21.1-r2311
```
<details>
```
Trying with url https://github.com/nzbget/nzbget.git
Possible git repo detected at https://github.com/nzbget/nzbget.git
v0.3.0 => #<Version:0x00007fd25628ae30 @version="0.3.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 3>, #<Version::NumericToken 0>]>
v0.3.1 => #<Version:0x00007fd25628ad68 @version="0.3.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 3>, #<Version::NumericToken 1>]>
v0.4.0 => #<Version:0x00007fd25628aca0 @version="0.4.0", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 4>, #<Version::NumericToken 0>]>
v0.4.1 => #<Version:0x00007fd25628abb0 @version="0.4.1", @tokens=[#<Version::NumericToken 0>, …
```
=> nzbget: add livecheckable

Livecheckables/oniguruma.rb
```
$ brew livecheck oniguruma
oniguruma (guessed) : 6.9.4 ==> 6.9.4_mark1
```
<details>
```
Trying with url https://github.com/kkos/oniguruma.git
Possible git repo detected at https://github.com/kkos/oniguruma.git
v5.9.6 => #<Version:0x00007fc6ec93e2b0 @version="5.9.6", @tokens=[#<Version::NumericToken 5>, #<Version::NumericToken 9>, #<Version::NumericToken 6>]>
v5.9.6_p1 => #<Version:0x00007fc6ec93da40 @version="5.9.6_p1", @tokens=[#<Version::NumericToken 5>, #<Version::NumericToken 9>, #<Version::NumericToken 6>, #<Version::PatchToken "p1">]>
v6.0.0 => #<Version:0x00007fc6ec93d3d8 @version="6.0.0", @tokens=[#<Version::NumericToken 6>, #<Version::NumericToken 0>, #<Version::NumericToken 0>]>
v6.1.0 => #<Version:0x00007fc6ec93cfc8 @version="6.1.0", …
```
=> oniguruma: add livecheckable

Livecheckables/grok.rb
```
$ brew livecheck grok
grok (guessed) : 0.9.2 ==> 1.20110630
```
<details>
<summary>brew livecheck grok --debug</summary>
```
Trying with url https://github.com/jordansissel/grok.git
Possible git repo detected at https://github.com/jordansissel/grok.git
1.20110308.1 => #<Version:0x00007fcab91b4d98 @version="1.20110308.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 20110308>, #<Version::NumericToken 1>]>
v0.9.1 => #<Version:0x00007fcab91b4c80 @version="0.9.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 9>, #<Version::NumericToken 1>]>
v0.9.2 => #<Version:0x00007fcab91b4bb8 @version="0.9.2", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 9>, #<Version::NumericToken 2>]>
v1.20110630 => #<Version:0x00007fcab91b4af0 @version="1.20110630", …
```
=> grok: add livecheckable

Livecheckables/gtk+.rb
```
$ brew livecheck gtk+
gtk+ (guessed) : 2.24.32 ==> 19971201
```
<details>
<summary>brew livecheck gtk+ --debug</summary>
```
PIXBUF_ENGINE_GTK_1_2 => #<Version:0x00007ff390084ce8 @version="1_2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 2>]>
SNAP_19971121 => #<Version:0x00007ff3900849c8 @version="19971121", @tokens=[#<Version::NumericToken 19971121>]>
SNAP_19971201 => #<Version:0x00007ff3900846a8 @version="19971201", @tokens=[#<Version::NumericToken 19971201>]>
VIRTUAL_ATOM-22-06-01 => #<Version:0x00007ff390084298 @version="22-06-01", @tokens=[#<Version::NumericToken 22>, #<Version::NumericToken 6>, #<Version::NumericToken 1>]>
gtk-1-0-merge-1 => #<Version:0x00007ff39009fdb8 @version="1-0-merge-1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, …
```
=> gtk+: add livecheckable

Livecheckables/gtksourceviewmm.rb
```
$ brew livecheck gtksourceviewmm
gtksourceviewmm (guessed) : 2.10.3 ==> 3.18.0
```
<details>
<summary>brew livecheck gtksourceviewmm --debug</summary>
```
Trying with url https://download.gnome.org/sources/gtksourceviewmm/2.10/gtksourceviewmm-2.10.3.tar.xz
Possible GNOME package [gtksourceviewmm] detected at https://download.gnome.org/sources/gtksourceviewmm/2.10/gtksourceviewmm-2.10.3.tar.xz
Using page_match("https://download.gnome.org/sources/gtksourceviewmm/cache.json", "(?-mix:gtksourceviewmm-(\d+\.([0-8]\d*?)?[02468](?:\.\d+)*?)\.t)")
3.0.0, , 3.0.0, , 2.2.0, , 2.2.0, , 3.12.0, 1, 3.18.0, 1, 2.10.3, 1, 2.10.2, 1, 2.10.2, 1, 2.10.1, 1, 2.10.1, 1, 2.10.0, 1, 2.10.0, 1, 3.2.0, , 3.2.0,
3.0.0 => #<Version:0x00007fe8911d8e28 @version="3.0.0", @tokens=[#<Version::NumericToken 3>, …
```
=> gtksourceviewmm: add livecheckable

Livecheckables/gtksourceviewmm3.rb
```
$ brew livecheck gtksourceviewmm3
gtksourceviewmm3 (guessed) : 3.18.0 ==> 3.18.0
```
<details>
<summary>brew livecheck gtksourceviewmm3 --debug</summary>
```
Trying with url https://download.gnome.org/sources/gtksourceviewmm/3.18/gtksourceviewmm-3.18.0.tar.xz
Possible GNOME package [gtksourceviewmm] detected at https://download.gnome.org/sources/gtksourceviewmm/3.18/gtksourceviewmm-3.18.0.tar.xz
Using page_match("https://download.gnome.org/sources/gtksourceviewmm/cache.json", "(?-mix:gtksourceviewmm-(\d+\.([0-8]\d*?)?[02468](?:\.\d+)*?)\.t)")
3.0.0, , 3.0.0, , 2.2.0, , 2.2.0, , 3.12.0, 1, 3.18.0, 1, 2.10.3, 1, 2.10.2, 1, 2.10.2, 1, 2.10.1, 1, 2.10.1, 1, 2.10.0, 1, 2.10.0, 1, 3.2.0, , 3.2.0,
3.0.0 => #<Version:0x00007f8f0aab81a0 @version="3.0.0", @tokens=[#<Version::NumericToken 3>, …
```
=> gtksourceviewmm3: add livecheckable

Livecheckables/gtksourceview.rb
```
$ brew livecheck gtksourceview
gtksourceview (guessed) : 2.10.5 ==> 4.6.0
```
<details>
<summary>brew livecheck gtksourceviewmm --debug</summary>
```
2.10.5 => #<Version:0x00007fad714846a0 @version="2.10.5", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 10>, #<Version::NumericToken 5>]>
2.10.4 => #<Version:0x00007fad71484628 @version="2.10.4", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 10>, #<Version::NumericToken 4>]>
3.2.0 => #<Version:0x00007fad714845d8 @version="3.2.0", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 2>, #<Version::NumericToken 0>]>
3.2.1 => #<Version:0x00007fad71484588 @version="3.2.1", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 2>, #<Version::NumericToken 1>]>
3.2.2 => #<Version:0x00007fad71484538 …
```
=> gtksourceview: add livecheckable

Livecheckables/gtksourceview3.rb
```
$ brew livecheck gtksourceview3
gtksourceview3 (guessed) : 3.24.11 ==> 4.6.0
```
<details>
<summary>brew livecheck gtksourceviewmm --debug</summary>
```
2.10.5 => #<Version:0x00007fad714846a0 @version="2.10.5", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 10>, #<Version::NumericToken 5>]>
2.10.4 => #<Version:0x00007fad71484628 @version="2.10.4", @tokens=[#<Version::NumericToken 2>, #<Version::NumericToken 10>, #<Version::NumericToken 4>]>
3.2.0 => #<Version:0x00007fad714845d8 @version="3.2.0", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 2>, #<Version::NumericToken 0>]>
3.2.1 => #<Version:0x00007fad71484588 @version="3.2.1", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 2>, #<Version::NumericToken 1>]>
3.2.2 => …
```
=> gtksourceview3: add livecheckable

Livecheckables/gtksourceview4.rb
```
$ brew livecheck gtksourceview4
gtksourceview4 (guessed) : 4.6.0 ==> 4.6.0
```
```
$ brew livecheck gtksourceview4
gtksourceview4 : 4.6.0 ==> 4.6.0
```
=> gtksourceview4: add livecheckable

Livecheckables/curaengine.rb
```
$ brew livecheck curaengine
curaengine (guessed) : 15.04.6 ==> 15.06.03
```
<details>
<summary>brew livecheck curaengine --debug</summary>
```
Trying with url https://github.com/Ultimaker/CuraEngine.git
Possible git repo detected at https://github.com/Ultimaker/CuraEngine.git
13.05 => #<Version:0x00007fe61b2bb2f0 @version="13.05", @tokens=[#<Version::NumericToken 13>, #<Version::NumericToken 5>]>
13.06.2 => #<Version:0x00007fe61b2bb228 @version="13.06.2", @tokens=[#<Version::NumericToken 13>, #<Version::NumericToken 6>, #<Version::NumericToken 2>]>
13.06.3 => #<Version:0x00007fe61b2bb160 @version="13.06.3", @tokens=[#<Version::NumericToken 13>, #<Version::NumericToken 6>, #<Version::NumericToken 3>]>
13.11.2 => #<Version:0x00007fe61b2bb098 @version="13.11.2", …
```
=> curaengine: add livecheckable

Livecheckables/jdnssec-tools.rb
```
$ brew livecheck jdnssec-tools
jdnssec-tools (guessed) : 0.15 ==> 0.16
```
<details>
<summary>brew livecheck jdnssec-tools --debug</summary>
```
Trying with url https://github.com/dblacka/jdnssec-tools.git
Possible git repo detected at https://github.com/dblacka/jdnssec-tools.git
0.12 => #<Version:0x00007fcdbe929760 @version="0.12", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 12>]>
0.13 => #<Version:0x00007fcdbe9293c8 @version="0.13", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 13>]>
0.14 => #<Version:0x00007fcdbe929198 @version="0.14", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 14>]>
v0.10.1 => #<Version:0x00007fcdbe9288b0 @version="0.10.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>, #<Version::NumericToken …
```
=> jdnssec-tools: add livecheckable

Livecheckables/cpanminus.rb
```
$ brew livecheck cpanminus
cpanminus (guessed) : 1.9019 ==> 1.9022
```
<details>
<summary>failure log</summary>
```
1.9019 => #<Version:0x00007f97fe956d28 @version="1.9019", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 9019>]>
App-cpanminus-1.7903 => #<Version:0x00007f97fe956670 @version="1.7903", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 7903>]>
App-cpanminus-1.7904 => #<Version:0x00007f97fe955e78 @version="1.7904", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 7904>]>
App-cpanminus-1.7905 => #<Version:0x00007f97fe955888 @version="1.7905", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 7905>]>
App-cpanminus-1.7906 => #<Version:0x00007f97fe955428 @version="1.7906", @tokens=[#<Version::NumericToken 1>, …
```
=> cpanminus: add livecheckable

Livecheckables/coturn.rb
```
coturn (guessed) : 4.5.1.1 ==> 4.5.1.2
```
```
$ brew livecheck coturn
coturn : 4.5.1.1 ==> 4.5.1.1
```
=> coturn: add livecheckable

Livecheckables/gwt.rb
```
$ brew livecheck gwt
gwt : 2.8.2 ==> 2.8.2
```
=> gwt: add regex

Livecheckables/traildb.rb
```
$ brew livecheck traildb
traildb (guessed) : 0.6 ==> 1.1
```
<details>
```
Trying with url https://github.com/traildb/traildb/archive/0.6.tar.gz
Possible git repo detected at https://github.com/traildb/traildb.git
0.5 => #<Version:0x00007f8d571cebc0 @version="0.5", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 5>]>
0.6 => #<Version:0x00007f8d571cead0 @version="0.6", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 6>]>
datasci-v1.0 => #<Version:0x00007f8d571ce968 @version="1.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>]>
datasci-v1.0.1 => #<Version:0x00007f8d571ce738 @version="1.0.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 1>]>
datasci-v1.1 => …
```
=> traildb: add livecheckable

Livecheckables/traefik@1.rb
```
$ brew livecheck traefik@1
traefik@1 : versioned
```
```
$ brew livecheck traefik@1
traefik@1 : 1.7.24 ==> 1.7.24
```
=> traefik@1: add livecheckable

Livecheckables/libtorch.rb
```
$ brew livecheck libtorch
libtorch (guessed) : 1.4.0 ==> 1.4.1
```
<details>
```
Trying with url https://github.com/pytorch/pytorch.git
Possible git repo detected at https://github.com/pytorch/pytorch.git
v0.1.1 => #<Version:0x00007fc415252f20 @version="0.1.1", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 1>]>
v0.1.10 => #<Version:0x00007fc415252c50 @version="0.1.10", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 10>]>
v0.1.11 => #<Version:0x00007fc415252b38 @version="0.1.11", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 1>, #<Version::NumericToken 11>]>
v0.1.12 => #<Version:0x00007fc4152529d0 @version="0.1.12", @tokens=[#<Version::NumericToken 0>, …
```
=> libtorch: add livecheckable

Livecheckables/aspell.rb
My first contribution, be kind if I have made a mistake :)
=> aspell: add livecheckable

Livecheckables/pass.rb
Before:
```
-bash-5.0.17- /Users/miccal (32) [> brew livecheck pass
Error: pass: Unable to get versions
```
After:
```
-bash-5.0.17- /Users/miccal (32) [> brew livecheck pass
pass : 1.7.3 ==> 1.7.3
```
=> pass: add livecheckable

Livecheckables/mpw.rb
Output before:
```
-bash-5.0.17- /Users/miccal (32) [> brew livecheck mpw
mpw (guessed) : 2.6-cli-5 ==> 2.8-mac-11
```
Now, `2.8-mac-11` is for the `.app` version of Master Password, which is available as a [Cask](https://github.com/homebrew/homebrew-cask/blob/master/Casks/master-password.rb).
Output with `--debug``:
```
-bash-5.0.17- /Users/miccal (32) [> brew livecheck --debug mpw
[SNIP]
Trying with url https://gitlab.com/MasterPassword/MasterPassword.git
Possible git repo detected at https://gitlab.com/MasterPassword/MasterPassword.git
1.0.0 => #<Version:0x00007fb5880800a8 @version="1.0.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 0>]>
1.0.0-r1 => #<Version:0x00007fb5880930b8 @version="1.0.0-r1", @tokens=[#<Version::NumericToken 1>, …
```
=> mpw: add livecheckable

livecheck/heuristic.rb
The block that checks SourceForge-hosted packages combs the RSS feed of each for a list of version numbers. Currently that works only if the URL contains "/project" (which not all of them do, e.g. [`base91`](https://formulae.brew.sh/formula/base91)) and the files are hosted in versioned folders below a folder named the same as the project itself (e.g. [Bacula](https://sourceforge.net/projects/bacula/files/bacula/)). This PR fixes both by accounting for more types of SF project URLs, and adjusting how the regex scans for version numbers.
<details>
<summary>non-livechecked formulae hosted on SF</summary>
<pre>
abook
acme
aften
ant-contrib
anttweakbar
apcupsd
apng2gif
argtable
arss
asciitex
asymptote
automysqlbackup
autopano-sift-c
autopsy
avanor
aview
bacula-fd
base91
bashish
bbe
beecrypt …
=> heuristic: update SourceForge logic

Livecheckables/consul.rb
previously: https://releases.hashicorp.com/consul/1.8.0-beta1
now: https://releases.hashicorp.com/consul/1.7.3/consul_1.7.3_SHA256SUMS
=> consul: remove url and update regex

Livecheckables/xmlto.rb
Output before:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck xmlto
Error: xmlto: Unable to get versions
```
Output after:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck xmlto
xmlto : 0.0.28 ==> 0.0.28
```
I hope I have done this right -- the syntax has changed since I last contributed.
Thanks.
=> xmlto: add livecheckable

Livecheckables/s-lang.rb
Livecheckable for `s-lang` using their releases page.
=> s-lang: add livecheckable

Livecheckables/openssh.rb
Adding Livecheckable for `openssh`.
=> openssh: add livecheckable

Livecheckables/ldns.rb
=> ldns: add livecheckable

Livecheckables/bash.rb
See discussion [here](https://github.com/Homebrew/homebrew-livecheck/issues/806).
=> Update bash livecheckable

Livecheckables/arpoison.rb
Adding a Livecheckable for `arpoison`.
=> arpoison: add livecheckable

Livecheckables/md5sha1sum.rb
Adding a Livecheckable for `md5sha1sum`.
=> md5sha1sum: add livecheckable

Livecheckables/fltk.rb
Adding a Livecheckable for `fltk`.
=> fltk: add livecheckable

Livecheckables/figlet.rb
Adding Livecheckable for `figlet`.
=> figlet: add livecheckable

Livecheckables/epstool.rb
Adding Livecheckable for `epstool`.
=> epstool: add livecheckable

Livecheckables/lrzsz.rb
Adding Livecheckable for `lrzsz`.
=> lrzsz: add livecheckable

Livecheckables/makedepend.rb
Adding Livecheckable for `makedepend`.
=> makedepend: add livecheckable

Livecheckables/sdl_ttf.rb
Adding Livecheckable for `sdl_ttf`.
=> sdl_ttf: add livecheckable

Livecheckables/sdl_mixer.rb
Adding Livecheckable for `sdl_mixer`.
=> sdl_mixer: add livecheckable

Livecheckables/sdl_image.rb
Adding Livecheckable for `sdl_image`.
=> sdl_image: add livecheckable

Livecheckables/phpmyadmin.rb
Adding Livecheckable for `phpmyadmin`.
=> phpmyadmin: add livecheckable

Livecheckables/nkf.rb
Adding Livecheckable for `nkf`. Checking the releases page didn't work so I've check the RSS feed instead.
=> nkf: add livecheckable

Livecheckables/testdisk.rb
Adding Livecheckable for `tesdisk`.
=> testdisk: add livecheckable

Livecheckables/selenium-server-standalone.rb
Adding Livecheckable for `selenium-server-standalone`.
=> selenium-server-standalone: add livecheckable

Livecheckables/cairomm.rb
Adding Livecheckable for `cairomm`.
=> cairomm: add livecheckable

Livecheckables/bzip2.rb
Adding Livecheckable for `bzip2`.
=> bzip2: add livecheckable

Livecheckables/minicom.rb
Adding Livecheckable for `minicom`.
=> minicom: add livecheckable

Livecheckables/mplayer.rb
Adding Livecheckable for `mplayer`.
=> mplayer: add livecheckable

Livecheckables/visp.rb
Output before:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck visp
Error: visp: Unable to get versions
```
Output after:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck visp
visp : 3.3.0 ==> 3.3.0
```
Thank you.
=> visp: add livecheckable

Livecheckables/libftdi0.rb
Adding livecheckable for `libftdi0`
=> libftdi0: add livecheckable

Livecheckables/libftdi.rb
Adding Livecheckable for `libftdi`.
=> libftdi: add livecheckable

Livecheckables/neo4j.rb
Adding a livecheckable for `neo4j`.
=> neo4j: add livecheckable

Livecheckables/libhid.rb
Adding Livecheckable for `libhid`.
=> libhid: add livecheckable

Livecheckables/xpdf.rb
Adding Livecheckable for `xpdf`.
=> xpdf: add livecheckable

Livecheckables/ipcalc.rb
Adding Livecheckable for `ipcalc`.
=> ipcalc: add livecheckable

Livecheckables/newt.rb
Adding Livecheckable for `newt`.
=> newt: add livecheckable

Livecheckables/iftop.rb
Adding Livecheckable for `iftop`.
=> iftop: add livecheckable

Livecheckables/fcrackzip.rb
Adding Livecheckable for `fcrackzip`.
=> fcrackzip: add livecheckable

Livecheckables/lxc.rb
Adding Livecheckable for `lxc`.
=> lxc: add livecheckable

Livecheckables/dependency-check.rb
Adding Livecheckable for `dependency-check`.
=> dependency-check: add livecheckable

Livecheckables/libyubikey.rb
Adding Livecheckable for `libyubikey`.
=> libyubikey: add livecheckable

Livecheckables/pssh.rb
Adding Livecheckable for `pssh`.
=> pssh: add livecheckable

Livecheckables/john.rb
Adding Livecheckable for `john`.
=> john: add livecheckable

Livecheckables/notmuch.rb
Adding Livecheckable for `notmuch`.
=> notmuch: add livecheckable

Livecheckables/pyside.rb
Adding Livecheckable for `pyside`.
=> pyside: add livecheckable

Livecheckables/rethinkdb.rb
Adding Livecheckable for `rethinkdb`.
=> rethinkdb: add livecheckable

Livecheckables/ossp-uuid.rb
Adding Livecheckable for `ossp-uuid`.
=> ossp-uuid: add livecheckable

Livecheckables/libspectre.rb
Adding Livecheckable for `libspectre`.
=> libspectre: add livecheckable

Livecheckables/hping.rb
Adding Livecheckable for `hping` to skip livecheck. Details: http://www.hping.org/download.php
=> hping: add livecheckable to skip

Livecheckables/pure-ftpd.rb
Adding Livecheckable for `pure-ftpd`.
=> pure-ftpd: add livecheckable

Livecheckables/corkscrew.rb
Adding Livecheckable for `corkscrew`.
=> corkscrew: add livecheckable

Livecheckables/cvs.rb, livecheck/heuristic.rb
Adding Livecheckable for `cvs`.
=> cvs: add livecheckable

Livecheckables/msmtp.rb
Adding Livecheckable for `msmtp`.
=> msmtp: add livecheckable

Livecheckables/desktop-file-utils.rb
Adding Livecheckable for `desktop-file-utils`.
=> desktop-file-utils: add livecheckable

Livecheckables/mit-scheme.rb, livecheck/heuristic.rb
Adding a livecheckable for `mit-scheme`.
=> mit-scheme: add livecheckable

Livecheckables/smpeg.rb
Adding Livecheckable for `smpeg`.
=> smpeg: add livecheckable

Livecheckables/wabt.rb
```
$ brew livecheck -v wabt
wabt (guessed) : 1.0.15 ==> 2
```
```
$ brew livecheck -v wabt
wabt : 1.0.15 ==> 1.0.17
```
=> wabt: add livecheckable

Livecheckables/erlang@21.rb
```
$ brew livecheck erlang@21
erlang@21 : versioned
```
```
$ brew livecheck -v erlang@21
erlang@21 : 21.3.8.16 ==> 21.3.8.16
```
=> erlang@21: add livecheckable

Livecheckables/erlang@22.rb
```
$ brew livecheck -v erlang@22
erlang@22 : versioned
```
```
$ brew livecheck -v erlang@22
erlang@22 : 22.3.4.1 ==> 22.3.4.1
```
=> erlang@22: add livecheckable

Livecheckables/grails.rb
```
$ brew livecheck -v grails
grails (guessed) : 4.0.3 ==> 4.1.0.M1
```
```
$ brew livecheck -v grails
grails : 4.0.3 ==> 4.0.3
```
=> grails: add livecheckable

Livecheckables/ncftp.rb
Adding Livecheckable for `ncftp`.
=> ncftp: add livecheckable

Livecheckables/neon.rb
Adding Livecheckable for `neon`.
=> neon: add livecheckable

Livecheckables/argp-standalone.rb
Adding Livecheckable for `argp-standalone`.
=> argp-standalone: add livecheckable

Livecheckables/mp4v2.rb
Adding Livecheckable for `mp4v2`.
=> mp4v2: add livecheckable

Livecheckables/markdown.rb
Adding Livecheckable for `markdown`.
=> markdown: add livecheckable

Livecheckables/tcping.rb
Adding Livecheckable for `tcping`.
=> tcping: add livecheckable

Livecheckables/pidof.rb
Adding Livecheckable for `pidof`.
=> pidof: add livecheckable

Livecheckables/clisp.rb, livecheck/heuristic.rb
Adding a livecheckable for `clisp`.
=> clisp: add livecheckable

Livecheckables/ispell.rb
Adding Livecheckable for `ispell`.
=> ispell: add livecheckable

Livecheckables/ucl.rb
Adding a Livecheckable for `ucl`.
=> ucl: add livecheckable

Livecheckables/juju.rb
Adding Livecheckable for `juju`.
=> juju: add livecheckable

Livecheckables/sleepwatcher.rb
Adding Livecheckable for `sleepwatcher`.
=> sleepwatcher: add livecheckable

Livecheckables/spidermonkey.rb
Adding Livecheckable for `spidermonkey`.
=> spidermonkey: add livecheckable

Livecheckables/jhead.rb
Adding Livecheckable for `jhead`.
=> jhead: add livecheckable

Livecheckables/homeassistant-cli.rb
```
$ brew livecheck -v homeassistant-cli
homeassistant-cli (guessed) : 0.9.1 ==> 833e7f9176e1e602853d
```
```
$ brew livecheck -v homeassistant-cli
homeassistant-cli : 0.9.1 ==> 0.9.1
```
=> homeassistant-cli: add livecheckable

Livecheckables/genders.rb
```
$ brew livecheck -v genders
genders (guessed) : 1.27.3 ==> 2-0-1pre
```
```
$ brew livecheck -v genders
genders : 1.27.3 ==> 1-27-3
```
=> genders: add livecheckable

Livecheckables/ledger.rb
```
$ brew livecheck -v ledger
ledger (guessed) : 3.2.1 ==> 2006
```
```
$ brew livecheck -v ledger
ledger : 3.2.1 ==> 3.2.1
```
=> ledger: add livecheckable

Livecheckables/clib.rb
```
$ brew livecheck -v clib
clib (guessed) : 1.11.3 ==> 2.0.0-next.12
```
```
$ brew livecheck -v clib
clib : 1.11.3 ==> 1.11.3
```
=> clib: add livecheckable

Livecheckables/epic5.rb
```
$ brew livecheck -v epic5
epic5 (guessed) : 2.1.2 ==> 5-2.1.2
```
```
$ brew livecheck -v epic5
epic5 : 2.1.2 ==> 2.1.2
```
=> epic5: add livecheckable

Livecheckables/mesa.rb
```
$ brew livecheck -v mesa
mesa (guessed) : 20.1.1 ==> 20090313
```
```
$ brew livecheck -v mesa
mesa : 20.1.1 ==> 20.1.1
```
=> mesa: add livecheckable

Livecheckables/sslscan.rb
```
$ brew livecheck -v sslscan
sslscan (guessed) : 1.11.13 ==> 1.11.13-rbsec
```
```
$ brew livecheck -v sslscan
sslscan : 1.11.13 ==> 1.11.13
```
=> sslscan: add livecheckable

Livecheckables/cgns.rb
```
$ brew livecheck -v cgns
cgns (guessed) : 4.1.1 ==> 40
```
```
$ brew livecheck -v cgns
cgns : 4.1.1 ==> 4.1.1
```
=> cgns: add livecheckable

Livecheckables/pdftk-java.rb
```
$ brew livecheck -v pdftk-java
pdftk-java (guessed) : 3.1.2 ==> 52
```
```
$ brew livecheck -v pdftk-java
pdftk-java : 3.1.2 ==> 3.1.2
```
=> pdftk-java: add livecheckable

Livecheckables/pipes-sh.rb
```
$ brew livecheck -v pipes-sh
pipes-sh (guessed) : 1.3.0 ==> 2014-02-21
```
```
$ brew livecheck -v pipes-sh
pipes-sh : 1.3.0 ==> 1.3.0
```
=> pipes-sh: add livecheckable

Livecheckables/chocolate-doom.rb
```
$ brew livecheck -v chocolate-doom
chocolate-doom (guessed) : 3.0.0 ==> 5
```
```
$ brew livecheck -v chocolate-doom
chocolate-doom : 3.0.0 ==> 3.0.0
```
=> chocolate-doom: add livecheckable

Livecheckables/kamel.rb
```
$ brew livecheck -v kamel
kamel (guessed) : 1.0.0 ==> 1.0.0-nightly.202005130003
```
```
$ brew livecheck -v kamel
kamel : 1.0.0 ==> 1.0.0
```
=> kamel: add livecheckable

Livecheckables/jdnssec-tools.rb
```
$ brew livecheck -v jdnssec-tools
jdnssec-tools : 0.15 ==> 0.16
```
```
$ brew livecheck -v jdnssec-tools
jdnssec-tools : 0.15 ==> 0.15
```
relates to Homebrew/homebrew-core#56153
=> jdnssec-tools: update url and regex

Livecheckables/plank.rb
```
$ brew livecheck -v plank
plank (guessed) : 1.6 ==> 100
```
```
$ brew livecheck -v plank
plank : 1.6 ==> 1.6
```
=> plank: add livecheckable

Livecheckables/swaks.rb
Adding Livecheckable for `swaks`.
=> swaks: add livecheckable

Livecheckables/libstfl.rb
Adding Livecheckable for `libstfl`.
=> libstfl: add livecheckable

Livecheckables/sdl_sound.rb
Adding Livecheckable for `sdl_sound`.
=> sdl_sound: add livecheckable

Livecheckables/megatools.rb
Adding Livecheckable for `megatools`.
=> megatools: add livecheckable

Livecheckables/rmtrash.rb
Adding Livecheckable for `rmtrash`.
=> rmtrash: add livecheckable

Livecheckables/bsdiff.rb
Adding Livecheckable for `bsdiff`.
=> bsdiff: add livecheckable

Livecheckables/gst-python.rb
Adding Livecheckable for `gst-python`.
=> gst-python: add livecheckable

Livecheckables/pip-completion.rb
Adding Livecheckable for `pip-completion`.
=> pip-completion: add livecheckable

Livecheckables/nexus.rb
Adding Livecheckable for `nexus`.
=> nexus: add livecheckable

Livecheckables/libotr.rb
Adding Livecheckable for `libotr`.
=> libotr: add livecheckable

Livecheckables/blast.rb
Adding Livecheckable for `blast`.
=> blast: add livecheckable

Livecheckables/vsftpd.rb
Adding Livecheckable for `vsftpd`.
=> vsftpd: add livecheckable

Livecheckables/libedit.rb
Adding Livecheckable for `libedit`.
=> libedit: add livecheckable

Livecheckables/superlu.rb
Adding Livecheckable for `superlu`.
=> superlu: add livecheckable

Livecheckables/base64.rb
Adding Livecheckable for `base64`.
=> base64: add livecheckable

Livecheckables/scalapack.rb
Adding Livecheckable for `scalapack`.
=> scalapack: add livecheckable

Livecheckables/eye-d3.rb
Adding Livecheckable for `eye-d3`.
=> eye-d3: add livecheckable

Livecheckables/rarian.rb
Adding Livecheckable for `rarian`.
=> rarian: add livecheckable

Livecheckables/gst-rtsp-server.rb
Adding Livecheckable for `gst-rtsp-server`. Also see #999.
=> gst-rtsp-server: add livecheckable

Livecheckables/gst-validate.rb
Adding Livecheckable for `gst-validate`. Also see #999.
=> gst-validate: add livecheckable

Livecheckables/pcsc-lite.rb
Adding Livecheckable for `pcsc-lite`.
=> pcsc-lite: add livecheckable

Livecheckables/minizip.rb
Adding Livecheckable for `minizip`.
=> minizip: add livecheckable

Livecheckables/ntp.rb
Adding Livecheckable for `ntp`.
=> ntp: add livecheckable

Livecheckables/ncview.rb
Adding Livecheckable for `ncview`.
=> ncview: add livecheckable

Livecheckables/sdl_net.rb
Adding Livecheckable for `sdl_net`.
=> sdl_net: add livecheckable

Livecheckables/antiword.rb
Adding Livecheckable for `antiword`.
=> antiword: add livecheckable

Livecheckables/bootloadhid.rb
Adding Livecheckable for `bootloadhid`.
=> bootloadhid: add livecheckable

Livecheckables/toilet.rb
Adding Livecheckable for `toilet`.
=> toilet: add livecheckable

Livecheckables/most.rb
Adding Livecheckable for `most`.
=> most: add livecheckable

Livecheckables/reaver.rb
Adding Livecheckable for `reaver`.
=> reaver: add livecheckable

Livecheckables/opencascade.rb
Adding Livecheckable for `opencascade`.
=> opencascade: add livecheckable

Livecheckables/libreplaygain.rb
Adding Livecheckable for `libreplaygain`.
=> libreplaygain: add livecheckable

Livecheckables/libcuefile.rb
Adding Livecheckable for `libcuefile`.
=> libcuefile: add livecheckable

Livecheckables/musepack.rb
Adding Livecheckable for `musepack`.
=> musepack: add livecheckable

Livecheckables/basex.rb
Adding Livecheckable for `basex`.
=> basex: add livecheckable

Livecheckables/asciiquarium.rb
Adding Livecheckable for `asciiquarium`.
=> asciiquarium: add livecheckable

Livecheckables/ballerina.rb
Adding Livecheckable for `ballerina`. Using their GitHub repository (https://ballerina.io/swan-lake/learn/installing-ballerina/#building-from-source).
=> ballerina: add livecheckable

Livecheckables/ec2-api-tools.rb
Adding Livecheckable for `ec2-api-tools`.
=> ec2-api-tools: add livecheckable

Livecheckables/mmv.rb
Adding Livecheckable for `mmv`.
=> mmv: add livecheckable

Livecheckables/stress.rb
Adding Livecheckable for `stress`. By the way, it seems the homepage is down. Don't know if only I'm facing this issue.
=> stress: add livecheckable

Livecheckables/sipcalc.rb
Adding Livecheckable for `sipcalc`.
=> sipcalc: add livecheckable

Livecheckables/backupninja.rb
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck backupninja
Error: backupninja: Unable to get versions
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck backupninja
backupninja : 1.1.0 ==> 1.1.0
```
Thanks :)
=> backupninja: add livecheckable

Livecheckables/ttyrec.rb
Adding Livecheckable for `ttyrec`.
=> ttyrec: add livecheckable

Livecheckables/dyld-headers.rb
Adding Livecheckable for `dyld-headers`.
=> dyld-headers: add livecheckable

Livecheckables/git-subrepo.rb
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck git-subrepo
git-subrepo : 0.4.1 ==> 216-1
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck git-subrepo
git-subrepo : 0.4.1 ==> 0.4.1
```
Thank you.
=>  git-subrepo: add livecheckable

Livecheckables/node_exporter.rb
Adding Livecheckable for `node_exporter`.
=> node_exporter: add livecheckable

Livecheckables/dns2tcp.rb
Adding Livecheckable for `dns2tcp`.
=> dns2tcp: add livecheckable

Livecheckables/ucspi-tcp.rb
Adding Livecheckable for `ucspi-tcp`.
=> ucspi-tcp: add livecheckable

Livecheckables/libestr.rb
Adding Livecheckable for `libestr`.
=> libestr: add livecheckable

Livecheckables/bbftp-client.rb
Adding Livecheckable for `bbftp-client`.
=> bbftp-client: add livecheckable

Livecheckables/wmctrl.rb
Adding Livecheckable for `wmctrl`.
=> wmctrl: add livecheckable

Livecheckables/dmg2img.rb
Adding Livecheckable for `dmg2img`.
=> dmg2img: add livecheckable

Livecheckables/fastqc.rb
Adding Livecheckable for `fastqc`.
=> fastqc: add livecheckable

Livecheckables/sdl_gfx.rb
Adding Livecheckable for `sdl_gfx`.
=> sdl_gfx: add livecheckable

Livecheckables/cadaver.rb
Adding Livecheckable for `cadaver`.
=> cadaver: add livecheckable

Livecheckables/mockserver.rb
Adding Livecheckable for `mockserver`.
=> mockserver: add livecheckable

Livecheckables/libpst.rb
Updating `libpst`'s Livecheckable to conform to current standards.
=> libpst: update regex

Livecheckables/libsamplerate.rb
Updating `libsamplerate`'s `regex` to conform to current standards.
=> libsamplerate: update regex

Livecheckables/cfr-decompiler.rb, Livecheckables/druid.rb, Livecheckables/eralchemy.rb, Livecheckables/guile.rb, Livecheckables/libxml2.rb, Livecheckables/pgcli.rb, Livecheckables/taktuk.rb, Livecheckables/wildfly-as.rb
This PR changes `href=".*` and `href=".*?` in regexes (when followed by filename) to `href=.*?`.
=> Change `href=".*` and `href=".*?` to `href=.*?`

Livecheckables/antiword.rb, Livecheckables/basex.rb, Livecheckables/blast.rb, Livecheckables/chocolate-doom.rb, Livecheckables/clisp.rb, Livecheckables/mariadb-connector-c.rb, Livecheckables/media-info.rb, Livecheckables/mit-scheme.rb, Livecheckables/mockserver.rb, Livecheckables/phpmyadmin.rb, Livecheckables/spidermonkey.rb
This PR changes usage of `[ '">]` to `["' >]` to ensure uniformity.
=> Change [ '">] to ["' >]

Livecheckables/daq.rb
This PR updates `daq`'s regex to conform to current standards. I tried to work out the best possible regex, but as always, it could be improved.
=> daq: update regex

Livecheckables/gwenhywfar.rb
This PR updates `gwenhywfar`'s `regex` to conform to current standards.
=> gwenhywfar: update regex

Livecheckables/qrencode.rb
This PR updates `qrencode`'s regex to conform to current standards.
=> qrencode: update regex

cmd/livecheck.rb
There are a couple of situations where livecheck won't display any output and this may be confusing for users.
1. **When the `--newer-only` flag is present but there are no newer upstream versions**. In this case, a "No newer upstream versions." message would be helpful, sort of like `brew update`'s "Already up-to-date." message (as mentioned in #1140).
2. **When `brew livecheck` is run without any flags/arguments but there is no watchlist file (`~/.brew_livecheck_watchlist`) or the watchlist file is empty**. In this case, a "No formulae to check." error may be helpful.
Closes #1140.
=> Print a message/error in situations with no output

Livecheckables/percona-server.rb
This PR brings `percona-server`'s regex up to current standards.
=> percona-server: update regex

Livecheckables/k3d.rb
Before:
```
Formula:          k3d
Livecheckable?:   No
URL:              https://github.com/rancher/k3d/archive/v3.0.0.tar.gz
URL (processed):  https://github.com/rancher/k3d.git
Strategy:         Git
Matched Versions:
0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 3.0.0, 3.0.0-syntax.0
k3d : 3.0.0 ==> 3.0.0-syntax.0
```
After:
```
Formula:          k3d
Livecheckable?:   Yes
URL:              https://github.com/rancher/k3d
URL (processed):  https://github.com/rancher/k3d.git
Strategy:         Git
Regex:            /^v?(\d+(?:\.\d+)+)$/i
Matched Versions:
0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, …
```
=> k3d: add livecheckable

Livecheckables/vgrep.rb
Before:
```
vgrep : 2.3.3 ==> 16.09.1
```
After:
```
vgrep : 2.3.3 ==> 2.3.3
```
=> vgrep: add livecheckable

cmd/livecheck.rb
Remove special handling for global options.
=> Remove global options from parser.

Livecheckables/gh.rb
```
$ brew livecheck --debug gh
["--debug", "gh"]
#<Homebrew::CLI::Args named_args=["gh"], remaining=["gh"], v?=true, verbose?=true, d?=true, debug?=true>
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gh.rb
Formula:          gh
Livecheckable?:   No
URL:              https://github.com/cli/cli.git
Strategies:       Git
Strategy:         Git
Matched Versions:
repos-rc-0 => #<Version:0x00007fb062a22118 @version="0">
repos-rc-1 => #<Version:0x00007fb062a20f20 @version="1">
repos-rc-2 => #<Version:0x00007fb062a20160 @version="2">
repos-rc-3 => #<Version:0x00007fb0630f7e98 @version="3">
repos-rc-4 => #<Version:0x00007fb0630f7bc8 @version="4">
repos-rc-5 => #<Version:0x00007fb0630f7628 …
```
=> gh: add livecheckable

Livecheckables/masscan.rb
```
$ brew livecheck masscan
masscan (guessed) : 1.0.5 ==> 2
```
```
$ brew livecheck masscan
masscan : 1.0.5 ==> 1.0.5
```
=> masscan: add livecheckable

Livecheckables/aalib.rb, Livecheckables/automysqlbackup.rb, Livecheckables/dex2jar.rb, Livecheckables/espeak.rb, Livecheckables/fatsort.rb, Livecheckables/findent.rb, Livecheckables/gqview.rb, Livecheckables/irrlicht.rb, Livecheckables/kettle.rb, Livecheckables/kpcli.rb, Livecheckables/locateme.rb, Livecheckables/naturaldocs.rb, Livecheckables/rtf2latex2e.rb, Livecheckables/saxon.rb, Livecheckables/zip.rb
This brings some of the existing SourceForge livecheckables up to current standards in a variety of ways and also adds some explanatory comments where it's beneficial.
=> Clean up some SourceForge livecheckables
