Homebrew/homebrew-livecheck

- livecheck/extend/formulary.rb
Hi, I am receiving the following error when attempting to check for updated versions of provided formula `ant.rb`:
```
$ brew livecheck ant
Error: uninitialized constant Class::Formulae
/usr/local/Library/Taps/jeffreywildman/homebrew-livecheck/livecheck/extend/formulary.rb:13:in `factory'
/usr/local/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Taps/jeffreywildman/homebrew-livecheck/cmd/brew-livecheck.rb:94:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require' …
```
> Proposed fix for uninitialized constant Class::Formulae

- Livecheckables/python.rb
Allow livechecking of python above 2.7.9
> Fix python.rb

- livecheck/euristic.rb
Otherwise any SourceForge project with uppercase letters in its name fails to check.
> Make SourceForge regex case insensitive

- cmd/brew-livecheck.rb
- livecheck/commands/cat.rb
Dead simple sub-command implementation. Each sub-command is a script (in the sense of "no classes, no methods, no nothing") in livecheck/commands. It would definitely be more "correct" to do it with classes, so feel free to close this if you care about that kind of thing.
> Add sub-command functionality

- livecheck/euristic.rb
Fixes a regression caused by Homebrew/brew@1693ddb by checking for
inheritance from, rather than equality to, GitDownloadStrategy so that
the new subclass GitHubGitDownloadStrategy is handled correctly.
Hi @youtux!
> euristic: fix GitHubGitDownloadStrategy regression

- livecheck/extend/formulary.rb
To match changes in https://github.com/Homebrew/brew/pull/2066,
extend the Formulary module, not class.
Deals with https://github.com/youtux/homebrew-livecheck/issues/13
> Make Formulary a module

- livecheck/euristic.rb
- add overrides for kotlin, osrm-backend, prometheus, pyenv-virtualenv,
sysdig and netpbm
- remove override for nagios
> euristic: honor more custom livechecks 3

- cmd/brew-livecheck.rb
https://github.com/Homebrew/brew/issues/3311
```
$ brew livecheck -iq
gmp (guessed) : 6.1.2 ==> 6.1.2
ffmpeg (guessed) : 3.4 ==> 3.5-dev
doctl (guessed) : 1.7.1 ==> 1.7.1
magic-wormhole (guessed) : 0.10.3 ==> 0.10.3
go (guessed) : 1.9.2 ==> 2012-03-27
python3 : 3.6.3 ==> 3.7.0
nettle (guessed) : 3.3 ==> 3.3
gdbm (guessed) : 1.13 ==> 1.13
python : 2.7.14 ==> 2.7.14
saldl (guessed) : 37 ==> 37
```
```
brew livecheck -iq
antigen (guessed) : 2.2.1 ==> 2.2.1
bettercap (guessed) : 1.6.2 ==> 1.6.2
doctl (guessed) : 1.7.1 ==> 1.7.1
duti (guessed) : 1.5.3 ==> 20071221
exa (guessed) : 0.8.0 ==> 0.8.0
fd (guessed) : 5.0.0 ==> 5.0.0
ffmpeg (guessed) : 3.4 ==> 3.5-dev
fzf (guessed) : 0.17.1 ==> 0.17.1
gdbm (guessed) : 1.13 ==> 1.13
gettext (guessed) : 0.19.8.1 ==> 0.19.8.1
```
> pass explicit sort to handle APFS

- Livecheckables/clozure-cl.rb
- Livecheckables/percona-server@5.5.rb
Both formulae have been removed from core.
> Remove livechecks

- Livecheckables/mono.rb
Hey, I struggling to add **Mono**.
When I run `brew livecheck mono -d` with the livecheckable vesion, this output shows up:
```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mono.rb
Loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/Livecheckables/mono.rb
Trying with url https://github.com/mono/mono/archive/
Possible git repo detected at https://github.com/mono/mono.git
Error: Unable to get versions for mono
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `exit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
```
I don't know why this is happening. Can someone help me here?
> [WIP] Add Mono

- Livecheckables/v8.rb
Added a `v8` livecheck, tracking the version shipped in the latest Chrome stable release (using their omahaproxy webapp), for the `v8` upgrade in https://github.com/Homebrew/homebrew-core/pull/30961.
> v8: add livecheck

- Livecheckables/angular-cli.rb
- Livecheckables/bitwarden-cli.rb
- Livecheckables/joplin.rb
- Livecheckables/quicktype.rb
- Livecheckables/typescript.rb
- Livecheckables/webpack.rb
- livecheck/euristic.rb
This PR:
* adds euristic for npm
* removes most of the livechecks with `npmjs.com` urls since they are now covered by this euristic
* `bower.rb` & `imageoptim-cli.rb` are not removed. The reason is that their corresponding `homebrew-core` formula urls are not under `registry.npmjs.org`. 
Not sure if I am doing this right or not since this is my first non-formula PR for Homebrew.
> Generalize npm livechecks

- livecheck/euristic.rb
This generalization may be able to remove the following livechecks:
```
template-glib
goffice
jsonrpc-glib
gobject-introspection
gsettings-desktop-schemas
glib
librsvg
gnome-latex
at-spi2-core
tepl
gnumeric
at-spi2-atk
gtk-vnc
libsoup
goocanvas
libdazzle
gom
```
> Generalize gnome livechecks

- Livecheckables/at-spi2-atk.rb
- Livecheckables/at-spi2-core.rb
- Livecheckables/glib.rb
- Livecheckables/gnome-latex.rb
- Livecheckables/gnumeric.rb
- Livecheckables/gobject-introspection.rb
- Livecheckables/goffice.rb
- Livecheckables/gom.rb
- Livecheckables/goocanvas.rb
- Livecheckables/gsettings-desktop-schemas.rb
- Livecheckables/gtk-vnc.rb
- Livecheckables/gtksourceview@4.rb
- Livecheckables/jsonrpc-glib.rb
- Livecheckables/libdazzle.rb
- Livecheckables/librsvg.rb
- Livecheckables/libsoup.rb
- Livecheckables/template-glib.rb
- Livecheckables/tepl.rb
Test before/after with:
```bash
brew livecheck at-spi2-atk at-spi2-core glib gnome-latex gnumeric gobject-introspection goffice gom goocanvas gsettings-desktop-schemas gtk-vnc gtksourceview@4 jsonrpc-glib libdazzle librsvg libsoup template-glib tepl
```
> Remove individual GNOME livecheckables in favor of generalized check

- Livecheckables/autossh.rb
Livecheck would fail when trying to redirect from http to https.
> autossh: use https

- Livecheckables/sonarqube.rb
Previous url leads to a 404 error.
> sonarqube: update url

- cmd/brew-livecheck.rb
1. Use `require_relative` instead of determining current directory
2. Remove unnecessary definition of `require?`
I checked locally that `brew livecheck` gives the same result for several formulae.
> A few improvements

- Livecheckables/shared-mime-info.rb
Uses GitLab API to retrieve the list of releases.
> shared-mime-info: update livecheck

- Livecheckables/libtiff.rb
The missing slash prevents livecheck from working correctly.
> libtiff: add the missing slash

- livecheck/extend/formulary.rb
- Fixes #122.
- Check that `lc_path` is defined before calling `.exist?` on it.
- Also fix some inconsistent indentation.
Before:
```
$ brew livecheck gnuradio
Error: undefined method `exist?' for nil:NilClass
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/livecheck/extend/formulary.rb:22:in `load_formula'
```
After:
```
$ brew livecheck gnuradio
gnuradio (guessed) : 3.7.13.4 ==> 3.8tech-preview
```
> Fix 'undefined method .exist?' error for lc_path

- Livecheckables/gst-libav.rb
- Livecheckables/gst-plugins-bad.rb
- Livecheckables/gst-plugins-base.rb
- Livecheckables/gst-plugins-good.rb
- Livecheckables/gst-plugins-ugly.rb
- Livecheckables/gstreamer.rb
- Livecheckables/orc.rb
Before (reporting newer version installed than what was found by livecheck):
```bash
$ brew livecheck gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gstreamer orc 
gst-libav : 1.16.0 ==> 1.14.5
gst-plugins-bad : 1.16.0 ==> 1.14.5
gst-plugins-base : 1.16.0 ==> 1.14.5
gst-plugins-good : 1.16.0 ==> 1.14.5
gst-plugins-ugly : 1.16.0 ==> 1.14.5
gstreamer : 1.16.0 ==> 1.14.5
orc : 0.4.29 ==> 0.4.28
```
After (version found matches what is installed):
```bash
$ brew livecheck gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gstreamer orc 
gst-libav : 1.16.0 ==> 1.16.0
gst-plugins-bad : 1.16.0 ==> 1.16.0
gst-plugins-base : 1.16.0 ==> 1.16.0
gst-plugins-good : 1.16.0 ==> 1.16.0
gst-plugins-ugly : 1.16.0 ==> 1.16.0
gstreamer : 1.16.0 ==> …
```
> Update gstreamer livecheckables

- livecheck/euristic.rb
Before:
```bash
$ brew livecheck gtk+3
Error: Unable to get versions for gtk+3
```
After:
```bash
$ brew livecheck gtk+3
gtk+3 (guessed) : 3.24.10 ==> 3.94.0
```
> euristic.rb: escape package name for gnome regex (gtk+3)

- Livecheckables/swi-prolog.rb
The current url creates a redirection and leads to the following error: 
```
Error: redirection forbidden: http://www.swi-prolog.org/download/stable/src -> https://www.swi-prolog.org/download/stable/src
```
> swi-prolog: move to https url

- Livecheckables/systemc.rb
The previous url redirected to the https one. This led to a `redirection forbidden` error.
> systemc: use https url

- Livecheckables/tor.rb
Fix Livecheckable for `tor`. Now depends on the download page directly.
> tor: fix livecheck

- livecheck/euristic.rb
This PR replaces this:
```ruby
if regex.nil?
regex = ...
end
```
with this:
```ruby
regex ||= ...
```
Nothing more...
> euristic.rb: replace if.nil? with ||= assignments

- cmd/brew-livecheck.rb
With `--tap` option, one can check all formulae from specified tap.
For example: `brew livecheck --tap=linuxbrew/xorg` would check all
formulae available in this tap.
> Provide new --tap option

- livecheck/euristic.rb
- livecheck/utils.rb
There are upstreams that only do `debian/` prefixed tags in their repositories, like this one: https://github.com/agx/git-buildpackage.
This PR aims to support checking the life of formulae that pull from repositories like these.
> Support upstreams that tag only with 'debian/' prefix

- Livecheckables/exiftool.rb
The exiftool livecheck is failing with `Error: redirection forbidden: https://www.sno.phy.queensu.ca/~phil/exiftool/history.html -> http://exiftool.org/history.html`, so this addresses the issue.
> exiftool: update url

- cmd/brew-livecheck.rb
Before:
```
➜  homebrew/homebrew-livecheck master ✓  brew livecheck -h
Usage: brew livecheck Check for newer versions of formulae from upstream
brew livecheck brew livecheck formula1 formula2 ... brew livecheck
[--tap=tap] brew livecheck [-i|--installed] brew livecheck
[-a|--all] brew livecheck [-h|--help]
Usage: Check if a formula is outdated. If no argument is passed, the list of
formulae to check is taken from #{WATCHLIST_PATH}
Options: -h, --help        show this help message and exit -n,
--newer-only  show the latest version only if it's newer than the formula
-v, --verbose     be more verbose :) -q, --quieter     be more quiet (do
not show errors) -d, --debug       show debugging info
```
After:
```
➜  homebrew/homebrew-livecheck help ✓  brew livecheck -h
Usage: brew livecheck
Check …
```
> brew-livecheck: nicer help message

- Livecheckables/icu4c.rb
https://ssl.icu-project.org URLs appear to be dead or in a state of prolonged downtime.  http://ssl.icu-project.org (not using https) simply redirects to http://site.icu-project.org
With this in mind, it may be a good idea to modify the icu4c livecheckable to use a different page.  I'm using the [ICU download page](http://site.icu-project.org/download/) in this PR but that site doesn't allow for secure connections, unfortunately.
If a secure connection is preferred, it's also possible to use the GitHub release page like so:
```ruby
livecheck :url => "https://github.com/unicode-org/icu/releases",
:regex => /href="\/unicode-org\/icu\/releases\/tag\/release-[^"]+"[^>]*>ICU ([\d\.]+)</
```
The main downside of using the GitHub release page is that this regex relies on the release title always …
> icu4c: update url and regex

- Livecheckables/libsamplerate.rb
Unfortunately, a secure connection isn't available and there doesn't appear to be an alternative location to get release information from (e.g., the GitHub repo doesn't have releases).
> libsamplerate: add livecheck

- Livecheckables/libsndfile.rb
The main website (used in this commit) doesn't provide a secure connection, unfortunately.   Release versions *are* available in the [GitHub repo](https://github.com/erikd/libsndfile/releases) but the last release was over two years ago, so it's hard to say whether the GitHub releases page will be updated in the future.  However, if you prefer to use the GitHub releases page, I can update the livecheck accordingly.
> libsndfile: add livecheck

- Livecheckables/xvid.rb
The Xvid download page on www.xvid.com uses a web application firewall (StackPath) and can return a 403 (Forbidden) error code in certain circumstances.  The downloads.xvid.com download page doesn't have the same issue, so this modifies the livecheck to use it instead.
> xvid: update url

- Livecheckables/yuicompressor.rb
- livecheck/euristic.rb
YUI Compressor has older version tags like "yuicompressor-35" and "hudson-yuicompressor-43" before the current "2.4.8" version tag, so it doesn't play nicely with the default GitHub version-finding.  Currently it reports the latest version as 43 because of the aforementioned tag containing 43.
This uses the releases page instead and restricts the version-finding to tags starting with "v" and containing digits or periods.
> yuicompressor: add livecheck

- livecheck/euristic.rb
The URLs for SourceForge project RSS feeds changed (older URLs were redirecting to the new URLs), so this brings the URL format up to date.
> Update SourceForge RSS URL

- Livecheckables/hana.rb
The homebrew-core formula was [recently deleted](https://github.com/Homebrew/homebrew-core/pull/46711).
> hana: delete livecheckable

- Livecheckables/grib-api.rb
`grib-api` formula was [recently deleted in homebrew-core](https://github.com/Homebrew/homebrew-core/pull/46924)
> grib-api: delete livecheckable

- Livecheckables/pound.rb
`pound` was [recently deleted from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/46539).
> pound: delete livecheckable

- Livecheckables/cherokee.rb
`cherokee` was [deleted from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/43544).
> cherokee: delete livecheckable

- livecheck/euristic.rb
Example formula that benefits from this change: `internetarchive`.
> euristic.rb: support checking pypi packages

- Livecheckables/sphinx-doc.rb
It does not seem to work.
But it does with this PR: https://github.com/Homebrew/homebrew-livecheck/pull/161
> sphinx-doc: delete livecheckable

- Livecheckables/opencore-amr.rb
- livecheck/euristic.rb
opencore-amr doesn't seem to work properly with the default Sourceforge version-finding (even after updating the URL in the formula), so I've created a livecheck to handle this special case.
> opencore-amr: add livecheck

- Livecheckables/docker-cloud.rb
`docker-cloud` was [deleted from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/47752).
> docker-cloud: delete livecheckable

- Livecheckables/ansible@1.9.rb
- Livecheckables/ansible@2.0.rb
`ansible@1.9` and `ansible@2.0` were [deleted from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/47055).
> Ansible delete @1.9 and @2.0 livecheckables

- Livecheckables/erlang@17.rb
- Livecheckables/erlang@18.rb
- Livecheckables/erlang@19.rb
All three were deleted from homebrew-core: 
* [`erlang@17`](https://github.com/Homebrew/homebrew-core/pull/46552)
* [`erlang@18`](https://github.com/Homebrew/homebrew-core/pull/39877)
* [`erlang@19`](https://github.com/Homebrew/homebrew-core/pull/46869)
> Delete erlang@17, erlang@18 and erlang@19 livecheckables

- Livecheckables/go@1.8.rb
`go@1.8` was [deleted from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/37621).
> go@1.8: delete livecheckable

- Livecheckables/mariadb@10.0.rb
`mariadb@10.0` was [removed from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/46338).
> mariadb@10.0: delete livecheckable

- Livecheckables/mongodb.rb
- Livecheckables/mongodb@3.0.rb
- Livecheckables/mongodb@3.2.rb
- Livecheckables/mongodb@3.4.rb
- Livecheckables/mongodb@3.6.rb
- Livecheckables/percona-server-mongodb.rb
All mongodb formulae were [removed in homebrew-core](https://github.com/Homebrew/homebrew-core/pull/43770) after it was migrated to a non open-source license.
> Mongodb delete livecheckables

- Livecheckables/kubernetes-cli.rb
It does not work and it is not necessary anyway.
> kubernetes-cli: delete livecheckable

- Livecheckables/mysql@5.5.rb
`mysql@5.5` was [deleted from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/46354).
> mysql@5.5: delete livecheckable

- Livecheckables/node@6.rb
`node@6` was [deleted from hombrew-core](https://github.com/Homebrew/homebrew-core/pull/39465).
> node@6: delete livecheckable

- Livecheckables/percona-server@5.6.rb
`percona-server@5.6` was [deleted from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/36025).
> percona-server@5.6: delete livecheckable

- Livecheckables/php@5.6.rb
- Livecheckables/php@7.0.rb
- Livecheckables/php@7.1.rb
`php@5.6`, `php@7.0` and `php@7.1` were all deleted from homebrew-core due to EOL:
* [`php@5.6` deletion](https://github.com/Homebrew/homebrew-core/pull/35679)
* [`php@7.0` deletion](https://github.com/Homebrew/homebrew-core/pull/34739)
* [`php@7.1` deletion](https://github.com/Homebrew/homebrew-core/pull/47385)
> Delete php versioned livecheckables

- Livecheckables/raine.rb
`raine` was [removed from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/46556).
> raine: remove livecheckable

- Livecheckables/tomcat@6.rb
`tomcat@6` was [deleted from homebrew-core due to EOL](https://github.com/Homebrew/homebrew-core/pull/39942).
> tomcat@6: delete livecheckable

- .github/workflows/tests.yml
Whenever a PR adds or modifies a Livecheckable, I manually check that it works locally. With this PR, the CI will do that check.
@MikeMcQuaid : requesting your review since I am not that familiar with Github actions.
> Github action to run brew livecheck on added/modified Livecheckables during PRs

- Livecheckables/varnish@4.rb
`varnish@4` was [removed from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/41203).
> varnish@4: remove livecheckable

- Livecheckables/cfr-decompiler.rb
Upstream changed their `href` links to full urls.
> cfr-decompiler: update regex

- Livecheckables/afio.rb
`afio` livecheckable points to a website that doesn't exists anymore. Its source is downloaded from Github and livecheck correctly guesses the latest version without the livecheckable.
> afio: delete livecheckable

- Livecheckables/ipython@5.rb
- Livecheckables/node@8.rb
`ipython@5` and `node@8` were both [deleted in homebrew-core](https://github.com/Homebrew/homebrew-core/pull/48460) due to the future removal of `python@2`.
> Delete livecheckable related to the python@2 removal

- Livecheckables/globus-toolkit.rb
`globus-toolkit` was [deleted in homebrew-core](https://github.com/Homebrew/homebrew-core/pull/48714).
> globus-toolkit: delete livecheckable

- .github/workflows/tests.yml
- cmd/brew-livecheck.rb
The livecheckable step seems to fail because the master branch wasn't fetched. I also double checked the sed regex and fixed it.
> fetch origin/master in Github action tests

- Livecheckables/mupdf.rb
The source files are now in an `archive` folder.
> mupdf: update livecheckable

- Livecheckables/osquery.rb
The osquery livecheckable wasn't working and pointed to the Github releases page. The heuristic currently does a good job with Github release so I'm removing the livecheckable.
> osquery: delete livecheckable

- Livecheckables/fortio.rb
The livecheckable checked github releases but didn't work. The default heuristic works.
> fortio: delete livecheckable

- Livecheckables/hdf5.rb
The webpage of hdf5 changed, this updates the livecheckable for the current format.
> hdf5: update url and regex

- Livecheckables/openttd.rb
`openttd` url doesn't have the `/en` part anymore. Also switch to `https`.
> openttd: fix livecheckable url

- Livecheckables/nano.rb
`nano` webpage now uses two number version, this fixes the regex to be more general.
> nano: update livecheckable regex

- cmd/brew-livecheck.rb
With this change, it becomes possible to livecheck the HEAD only
formulae if they are installed. If they are not - inform the user about
it.
> brew-livecheck: allow checking installed HEAD only formulae

- Livecheckables/netpbm.rb
Generalize the regex to be able to catch the latest version.
> netpbm: update livecheckable regex

- Livecheckables/watch.rb
`watch` Livecheckable checks the gitlab page and didn't work. The default heuristic does work on gitlab.
> watch: delete livecheckable

- Livecheckables/logcheck.rb
The regex link changed slightly, making it more general.
> logcheck: fix livecheckable regex

- cmd/livecheck.rb
`brew livecheck FORMULA` always exits doing nothing, without this change.
> livecheck: fix early return

- Livecheckables/simgrid.rb
`simgrid` homepage changed which broke the Livecheckable.
> simgrid: update livecheckable url

- cmd/livecheck.rb
- livecheck/heuristic.rb
When errors other than `Unable to get versions` was raised, the formula name wasn't in the error message. When using livecheck over a large list of formulae it was a hassle to find the culprit.
> Show formula name in every error output

- Livecheckables/yaws.rb
`yaws` releases are now on Github. The tags need to be filtered so I updated the regex.
> yaws: update livecheckable

- Livecheckables/atari800.rb
`atari800` releases are now on Github but the tags were not recognized correctly by the heuristic.
> atari800: update Livecheckable url and regex

- Livecheckables/azure-cli.rb
This adds a livecheckable for `azure-cli` since the formula uses an unusual URL and doesn't livecheck properly.
> azure-cli: add livecheckable

- Livecheckables/armadillo.rb
The regex was too specific to the placement of the text around it. I reduced it to make it work with the latest changes to the webpage.
> armadillo: update regex

- Livecheckables/mg.rb
`mg` releases are now on Github and the default heuristic work fine on it.
> mg: delete livecheckable

- Livecheckables/linkerd.rb
The upstream url changed and the release tags too, hence a new regex was needed.
> linkerd: update livecheckable url and regex

- Livecheckables/luajit.rb
The default livechecking for LuaJIT doesn't distinguish between stable and beta releases (2.1.0-beta3 is given as the latest version), so this adds a livecheckable to address this.
This assumes that `livecheck` should return the latest stable version and that alpha/beta/RC/etc. releases aren't desirable, of course.
> luajit: add livecheckable

- Livecheckables/spin.rb
`spin` Livecheckable was broken. Its codebase is now on Github and the heuristic works fine without the Livecheckable.
> spin: delete livecheckable

- Livecheckables/composer.rb
composer's existing livecheckable doesn't filter Git tags, so it also picks up release candidate versions (e.g., 1.10.0-RC). This adds a regex that restricts livecheck to stable releases.
> composer: add regex

- Livecheckables/gcc.rb
gcc's default livecheck picks up releases other than just gcc (e.g., g77-0.5.22) and returns an incorrect new version (e.g., 77-0.5.22). This livecheckable restricts the search to just gcc releases.
> gcc: add livecheckable

- Livecheckables/apache-spark.rb
The apache-spark livecheck returns unstable versions (e.g., 3.0.0-preview2), so this adds a livecheckable that only returns versions without trailing text (e.g., 2.4.5).
I used the GitHub repository tags here because the [Apache Spark website's downloads page](https://spark.apache.org/downloads.html) requires JavaScript to display the available versions. The version numbers are available in the [JavaScript file](https://spark.apache.org/js/downloads.js) but it seems less reliable than just parsing the GitHub releases.
If we absolutely need to use the Apache Spark website, I can rework this to parse the version numbers from the `downloads.js` file.
Past that, is there any preference around whether to parse a Git repo's tags or an HTML page?
> apache-spark: add livecheckable

- Livecheckables/kubernetes-cli.rb
The default livecheck for kubernetes-cli also picks up unstable releases (e.g., 1.18.0-alpha.5), so this restricts it to stable releases.
In testing this, I found that it's possible to drop the `:url` argument and rely on the default behavior for the formula (searching Git tags), simply providing the regex:
```ruby
class KubernetesCli
livecheck :regex => /^v([\d\.]+)$/
end
```
Is there an established norm around whether to explicitly provide the Git repo URL or allow it to be implicitly inferred? I see 29 existing livecheckables that explicitly provide the Git repo URL and two livecheckables that only include a regex.
On the one hand, omitting the URL means the livecheckable doesn't have to be updated if the Git repo URL changes in the formula. On the other hand, if something changes in …
> kubernetes-cli: add livecheckable

- Livecheckables/fastlane.rb
The default `fastlane` livecheck returns a weird version number (166) rather than the latest version (2.141.0), so this adds a livecheckable to address the issue.
> fastlane: add livecheckable

- Livecheckables/tcl-tk.rb
The default `tcl-tk` livecheck lists an alpha version as the latest (9.0a1), so this creates a livecheckable to identify the latest stable version.
> tcl-tk: add livecheckable

- Livecheckables/gitlab-runner.rb
Adds a livecheckable that restricts matching to stable versions (skipping release candidates).
> gitlab-runner: add livecheckable

- Livecheckables/jenkins.rb
There's a tag in the Jenkins Git repo that throws off livecheck (it returns "3a154d27f5bd99802eb" as the latest version), so this adds a livecheckable to restrict matching to real versions.
> jenkins: add livecheckable

- Livecheckables/kops.rb
This adds a livecheckable to restrict matching to stable versions (skipping alpha/beta versions).
> kops: add livecheckable

- Livecheckables/node-build.rb
The default livecheck is picking up tags for ruby-build versions (e.g., "ruby-build/v20191024") and returning the numeric portion (e.g., "20191024"), giving a persistent false positive when checking for a new version. This adds a livecheckable to restrict matching to versions consisting of numbers and periods (e.g., 1.2.3).
> node-build: add livecheckable

- Livecheckables/ntfs-3g.rb
There are all sorts of tags in the ntfs-3g repo that give false positives when checking for new versions (the current new version if listed as "20070925" from a "PERMISSION_HANDLING_BASE_20070925" tag). This adds a livecheckable to restrict matching to versions consisting of numbers and periods, which encompasses the current version style used (e.g., 2017.3.23).
> ntfs-3g: add livecheckable

- Livecheckables/qt.rb
This adds a livecheckable to restrict version matching to stable versions (e.g., no alpha, beta, or rc).
> qt: add livecheckable

- Livecheckables/source-highlight.rb
The default regex used when matching versions for this package doesn't work because it searches for "src-highlite" but the archives have filenames beginning with "source-highlight". This livecheckable uses a similar regex but addresses the name mismatch.
> source-highlight: add livecheckable

- Livecheckables/tesseract.rb
This adds a livecheckable to restrict matching to stable versions (skipping alpha, beta, dev, RC, etc.).
> tesseract: add livecheckable

- Livecheckables/tfenv.rb
This adds a livecheckable to restrict matching to stable versions (skipping alpha, beta, etc.).
> tfenv: add livecheckable

- Livecheckables/theora.rb
This adds a livecheckable to restrict matching to stable versions (skipping alpha, etc.).
> theora: add livecheckable

- Livecheckables/htop.rb
This adds a livecheckable to restrict matching to stable versions (skipping beta, etc.).
> htop: add livecheckable

- Livecheckables/tidy-html5.rb
[Stable HTML Tidy versions have an even-numbered minor version](https://github.com/htacg/tidy-html5/blob/next/README/VERSION.md#minor), so this adds a livecheckable to restrict matching accordingly.
> tidy-html5: add livecheckable

- Livecheckables/ghostscript.rb
The tags in the Ghostscript repo are for more than just ghostscript, so this restricts matching to tags containing "ghostscript-" followed by a typical numeric version string (e.g., 1.2, 1.2.3, etc.).
> ghostscript: add livecheckable

- Livecheckables/docker-compose.rb
This adds a livecheckable to restrict version matching to stable versions (no rc, test, etc.).
> docker-compose: add livecheckable

- livecheck/heuristic.rb
The formulae to which the gnome.org behavior in `livecheck/heuristic.rb` should apply all have a download.gnome.org URL, so I've modified the URL in `heuristic.rb` accordingly.
The default `easy-git` livecheck fails (``Error: easy-git: undefined method `[]' for nil:NilClass``) because its URL uses the people.gnome.org domain and the gnome.org behavior is wrongly applied. Further, the gnome.org behavior even overrides the livecheckable that I created to address this issue, so `heuristic.rb` needed to be updated for accuracy but also to allow for `easy-git` to be fixed with a livecheckable.
> Restrict gnome.org matching

- Livecheckables/easy-git.rb
Now that the gnome.org matching restriction has been merged (#218), we can add a livecheckable for `easy-git`.
> easy-git: add livecheckable

- Livecheckables/docbook.rb
This adds a livecheckable for docbook and restricts it to stable versions.
> docbook: add livecheckable

- Livecheckables/wireguard-tools.rb
I switched the url from the official repository to an official mirror repository on Github which is simpler to parse with the heuristic.
> wireguard-tools: update livecheckable with Github url

- Livecheckables/aamath.rb
Adding live checkable for `aamath` as per #237.
> aamath: add livecheckable

- Livecheckables/aardvark_shell_utils.rb
Adding livecheckable for `aardvark_shell_utils` to fix `brew livecheck` errors.
> aardvark_shell_utils: add livecheckable

- Livecheckables/lrzip.rb
Adding livecheckable for `lrzip` to fix `brew livecheck` errors.
> lrzip: add livecheckable

- Livecheckables/aalib.rb
This is not yet complete, as I have a query. Formula `aalib` is currently at version `1.4rc5`, which is an `rc` version. According to #246, if I understand correctly, such versions are not allowed on Homebrew/core, but `aalib` seems to be an exception (possibly more exist). How must I handle this?
Output for `brew livecheck aalib`:
* Before this change
```Error: aalib: undefined method `[]' for nil:NilClass```
* After this change
`aalib : 1.4rc5 ==> 1.2`
> aalib: add livecheckable

- .github/workflows/tests.yml
I've spotted a few PR where the CI would fail if a newer change was made in master but not yet rebased on the PR branch. This forces `git diff` to only check newer changes coming from the PR branch.
> Update github action with current branch name during diff

- livecheck/extend/formula.rb
- livecheck/heuristic.rb
Homebrew does not allow prerelease versions in core tap.
So it might be a good idea to filter them out.
Before:
```
acmetool (guessed) : 0.0.67 ==> 0.2.1
anycable-go (guessed) : 0.6.4 ==> 1.0.0.preview1
apache-brooklyn-cli (guessed) : 0.12.0 ==> 1.0.0-rc3
arangodb (guessed) : 3.6.0 ==> 3.7.0-alpha.1
arduino-cli (guessed) : 0.8.0 ==> 2
auditbeat (guessed) : 6.8.6 ==> 7.6.0
berglas (guessed) : 0.5.0 ==> 0.5.1
buildkit (guessed) : 0.6.3 ==> 1.1.5-experimental
cacli (guessed) : 1.2.29 ==> 1.04
caddy (guessed) : 1.0.4 ==> 2.0.0-beta12
calicoctl (guessed) : 3.12.0 ==> 3.13.0-0.dev
convox (guessed) : 20200129210159 ==> 20200207161122-danone-nodejs10
cosi (guessed) : 0.8.5 ==> 0.8.6
crc (guessed) : 1.4.0 ==> 1.6.0
csvq (guessed) : 1.12.4 ==> 1.12.4-pr.2
devdash (guessed) : 0.2.0 ==> 0.3.0
dlite …
```
> heuristic: reject prereleases

- Livecheckables/buildkit.rb
Without this livecheckable, `dockerfile/` prefixed releases are matched.
> buildkit: add livecheckable

- Livecheckables/libtcod.rb
`libtcod` has moved to Github and the default heuristic correctly guess the version.
> libtcod: delete livechekable

- Livecheckables/libmetalink.rb
The archive files for `libmetalink` start with `libmetalink-`, so this adds a regex to account for it and produce just the version number.
> libmetalink: add livecheckable

- Livecheckables/httpie.rb
The existing livecheckable isn't properly matching the full version number (returning "2.0" for version "2.0.0") and it isn't necessary since the default heuristic behavior (checking Git tags) works correctly. As such, this removes the livecheckable.
> httpie: remove livecheckable

- Livecheckables/libvterm.rb
The regex in the existing `libvterm` livecheckable isn't properly matching the version string (returning "726" instead of "0.1.3"), so this updates the regex to address the issue.
> libvterm: update regex

- Livecheckables/opencv.rb
The existing livecheckable wasn't returning the latest version (3.4.9 instead of 4.2.0), so this removes the URL (letting the heuristic use the Git repo tags) and updates the regex accordingly.
> opencv: remove url, update regex

- Livecheckables/gdb.rb
The heuristic seems to favor the Git repo (though it will flop around to others if you fiddle with the regex) and this adds a livecheckable with a regex to match the release versions.
> gdb: add livecheckable

- Livecheckables/fish.rb
The existing livecheckable returns an incorrect version (3.0.2 instead of 3.1.0), so this removes the URL (letting the heuristic use the Git repo) and updates the regex accordingly.
> fish: remove url, update regex

- Livecheckables/zeromq.rb
The `zeromq` git repo currently contains a tag ending in `-win`, which throws off livecheck, so this adds a livecheckable with a regex to restrict the version matching.
> zeromq: add livecheckable

- Livecheckables/vault.rb
The existing livecheckable uses a page that provides a very limited number of versions and the newest listed version has the possibility of being a beta version. This updates the URL to use a page that lists many releases instead.
The regex is also matching beta versions without returning any beta suffix, so "1.4.0-beta1" was being shown as "1.4.0" in livecheck and reported as the latest version. This restricts the regex to only match stable versions, resolving this issue.
> vault: update url and regex

- Livecheckables/pyqt.rb
The existing livecheckable uses the [Riverbank Computing download page](https://riverbankcomputing.com/software/pyqt/download5), which doesn't list all the newest versions. The newest stable version of `pyqt` is 5.14.1 but the download page only goes up to 5.13.2 before listing the latest development version. The release of 5.14.1 is mentioned in the "Recent news" section (in the right-hand sidebar) but not the downloads page.
Removing the livecheckable lets the heuristic take over, which correctly reports 5.14.1 as the newest version.
> pyqt: remove livecheckable

- Livecheckables/syncthing.rb
The existing `syncthing` livecheckable uses the GitHub release page, so this removes the URL to allow the heuristic to use the Git repo and updates the regex to match the version tags.
> syncthing: remove url, update regex

- Livecheckables/php.rb
The PHP livecheckable is currently being restricted to version 7.2.x, even though the formula is now at 7.4.3. This unrestricts the version matching, so it will match all stable versions.
Edit: Using the Git repo isn't the best idea, for reasons mentioned below.
> php: update url and regex

- Livecheckables/graphviz.rb
The existing livecheckable was using the [Graphviz source download page](https://graphviz.gitlab.io/_pages/Download/Download_source.html) and matching against the stable tar.gz files. As of this PR, the download page lists 2.40.1 as the latest stable version, whereas the [Gitlab repo](https://gitlab.com/graphviz/graphviz/) says 2.42.2 (and is currently used in the Graphviz formula).
This updates the livecheckable to remove the URL (using the Git repo, due to the heuristic) and updates the regex to match the stable version tags. The tags in the repo are kind of messy, so the regex may need to be modified again in the future if things change.
> graphviz: remove url, update regex

- livecheck/heuristic.rb
The npmjs.org version finding in the heuristic (for formulae containing a `registry.npmjs.org` URL) is broken and this updates it to work properly. The changes are as follows:
* The existing method of generating the package name failed for `atomist-cli` (producing "@atomist/cli/-" instead of "@atomist/cli") and needed to be addressed somehow (I chose to reject URL path parts consisting of only "-")
* The trailing slash at the end of the previous URL was leading to a redirection
* The homepage for an npm package only seems to list one version and it's tricky to create a regex to match it. This uses the "Versions" tab instead, which contains a number of versions (easily matched with a regex)
* The regex has been updated to work on the "Versions" tab
This fixes livecheck for the following …
> heuristic: fix npm version finding

- livecheck/heuristic.rb
Working on the formulae that were returning unstable versions after #265 (angular-cli, atomist-cli, balena-cli, now-cli), I found that restricting the heuristic's version-matching regex for npm formulae resolves this issue.
> heuristic: restrict npm version matching

- livecheck/heuristic.rb
In the recent changes to the npm version matching update, I added some code that didn't adhere to rubocop's style, so this addresses those offenses.
> heuristic: fix code style

- livecheck/utils.rb
`utils.rb` currently contains the code `open(url).read`, where it would be better to use `URI.open(url).read` to avoid any security issues with `Kernel#open`.
> utils: explicitly use URI.open

- Livecheckables/libosinfo.rb
- Livecheckables/v8.rb
Four existing livecheckables were inheriting from Formula (e.g., `class FormulaName < Formula`), like you would see in a formula file. Presumably, someone copied the entire `class` line from the formula when creating these livecheckables. This removes the Formula inheritance for the two livecheckables with existing formulae, bringing them in line with the others.
The two livecheckables not addressed here (`osinfo-db.rb`, `osinfo-db-tools.rb`) will be removed in separate PRs, as they no longer have corresponding formulae.
> Livecheckables should not inherit from Formula

- Livecheckables/osinfo-db-tools.rb
> osinfo-db-tools: delete

- Livecheckables/osinfo-db.rb
> osinfo-db: delete

- Livecheckables/bro.rb
> bro: delete

- Livecheckables/geth.rb
> geth: delete

- Livecheckables/virt-manager.rb
> virt-manager: delete

- Livecheckables/virt-viewer.rb
> virt-viewer: delete

- Livecheckables/wine.rb
> wine: delete

- Livecheckables/sagittarius-scheme.rb
This removes trailing whitespace from livecheckables, in line with RuboCop's [Layout/TrailingWhitespace](https://rubocop.readthedocs.io/en/latest/cops_layout/#layouttrailingwhitespace) cop.
> Fix RuboCop Layout/TrailingWhitespace offenses

- Livecheckables/debianutils.rb
The debian-utils livecheckable has some unnecessary comments, so this removes them.
> debian-utils: remove unnecessary comments

- Livecheckables/gnutls.rb
The gnutls livecheckable has some seemingly unnecessary comments, so this removes them.
> gnutls: remove unnecessary comments

- Livecheckables/osrm-backend.rb
The existing livecheckable wasn't catching the newest versions (it should be 5.22.0 but lists 5.18.0), so this removes the URL (letting the heuristic use the Git repo tags) and updates the regex to match only stable versions.
> osrm-backend: remove url, update regex

- Livecheckables/armadillo.rb
- Livecheckables/lzo.rb
This fixes the indentation in livecheckables, in line with RuboCop's [Layout/IndentationWidth](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutindentationwidth) cop.
> Fix RuboCop Layout/IndentationWidth offenses

- Livecheckables/bgpdump.rb
The existing bgpdump livecheckable isn't working properly, so this updates it to use a different page and regex.
The [existing Bitbucket repo](https://bitbucket.org/ripencc/bgpdump/) (used in the formula) doesn't provide any tags, archives, etc. anymore. Per the Bitbucket repo's README, it has moved to [RIPE's NCC GitHub](https://github.com/RIPE-NCC/bgpdump) instead. However, this repo also doesn't have any tags, archives, releases, etc.
The only alternative I could find was the [RIPE source page for bgpdump](https://www.ris.ripe.net/source/bgpdump/). This lists archive files for `libbgpdump`, which may or may not be what we want.
Related to this, the archive in the formula doesn't exist anymore but I didn't have any luck replacing it with the archive for 1.6.0 from the RIPE source page …
> bgpdump: update url and regex

- cmd/livecheck.rb
This adds trailing commas in hash literals, in line with RuboCop's [Style/TrailingCommaInHashLiteral](https://www.rubocop.org/en/stable/cops_style/#styletrailingcommainhashliteral) cop.
> Fix RuboCop Style/TrailingCommaInHashLiteral offense

- Livecheckables/python@2.rb
> python@2: delete

- Livecheckables/bower.rb
The existing livecheckable for bower gives an error (`Unable to get versions`), so this removes the URL (allowing the heuristic to take over) and updates the regex accordingly.
> bower: remove url, update regex

- Livecheckables/cataclysm.rb
The existing livecheckable gives an error (`Unable to get versions`), so this removes the URL (allowing the heuristic to take over) and updates the regex accordingly.
Though this fixes version finding and properly matches versions, it leads to an incorrect livecheck result. The latest version of cataclysm as of this PR is `0.D` (and this is present in the results) but livecheck reports `0.9` as newer than `0.D`. This would presumably need to be addressed in how `Version` handles comparisons in Homebrew/brew but this PR at least resolves the issues relating to the livecheckable itself.
> cataclysm: remove url, update regex

- Livecheckables/cfengine.rb
The existing livecheckable for `cfengine` gives an error (`Unable to get versions`), so this updates the URL and regex to address this.
The page used in the livecheckable up to this point does not display versions without JavaScript, so we're unable to get the version information this way. Instead, the page fetches the version information from a JSON file and uses that information to populate the page.
This commit parses the aforementioned `releases.json` file for version information, restricting matching to stable versions.
> cfengine: update url and regex

- Livecheckables/chronograf.rb
The existing chronograf livecheckable gives an error (`Unable to get versions`). This removes the livecheckable, as the heuristic is capable of finding and identifying versions perfectly fine.
> chronograf: delete

- Livecheckables/cracklib.rb
The existing livecheckable for cracklib gives an error (`Unable to get versions`), so this removes the URL (allowing the heuristic to take over) and updates the regex accordingly (restricting matching to stable versions).
> cracklib: remove url, update regex

- Livecheckables/deployer.rb
The existing livecheckable for deployer gives an error (`Unable to get versions`), so this updates the regex to fix version matching.
> deployer: update regex

- Livecheckables/dnscrypt-proxy.rb
The existing livecheckable for `dnscrypt-proxy` gives an error (`Unable to get versions`), so this removes the URL (allowing the heuristic to take over) and updates the regex accordingly.
> dnscrypt-proxy: remove url, update regex

- Livecheckables/dnsperf.rb
The existing livecheckable for `dnsperf` gives an error (`Unable to get versions`), so this updates the URL (addressing the redirection) and regex to fix the issue.
> dnsperf: update url and regex

- cmd/livecheck.rb
While parsing livecheck JSON output, I noticed that `true` values were interspersed into the output array.  Looking closer, they appeared to correspond with formulae that had run into errors.
It looks like the source of the issue was `Homebrew.failed = true` being implicitly returned where the error is handled in `livecheck.rb`.  Adding a `nil` after this line prevents `true` from being returned and all seems well in the output.
For example, we can test `acme` using `brew livecheck --json acme`, since it currently errors.
**Before**
```
Error: acme: undefined method `[]' for nil:NilClass
[true]
```
**After**:
```
Error: acme: undefined method `[]' for nil:NilClass
[]
```
---
Ideally, passing the `--json` flag should output JSON and nothing else. This would require any errors or warnings …
> Fix issue with true values appearing in JSON output

- Livecheckables/graphviz.rb
As @Bo98 mentioned in Homebrew/homebrew-core#51115, the 2.42.3 release of Graphviz wasn't (or hasn't yet been) tagged in Git, so livecheck isn't picking it up.
This PR updates the livecheckable to use the archive index page found in the Graphviz formula (https://www2.graphviz.org/Packages/stable/portable_source/) and modifies the regex to match the stable archive files.
> graphviz: update url and regex

- Livecheckables/netcdf.rb
The `netcdf` livecheckable wasn't properly finding the newest version (only matching 4.7.2 on the page when 4.7.3 was the newest version), so this removes the URL (allowing the heuristic to take over and use Git tags) and updates the regex to match stable versions.
> netcdf: remove url, update regex

- Livecheckables/itk.rb
The heuristic uses the ITK Git repo tags by default but it reports an unstable version as the newest. This adds a livecheckable to restrict matching to stable versions only.
> itk: add livecheckable

- Livecheckables/eye-d3.rb
The `eye-d3` livecheckable was returning a 403 and needed to be updated somehow. The formula was recently switched to use the PyPI archive (Homebrew/homebrew-core#50883), so the heuristic is now capable of finding the newest version for this formula. This removes the livecheckable to allow the heuristic to take over.
> eye-d3: delete

- cmd/livecheck.rb
- livecheck/extend/formula.rb
Some formulae are important and we want to keep them around but they will not see a new version anytime soon (if ever) and livecheck shouldn't waste effort checking them. For example, the `imap-uw` formula states, "imap-uw is unmaintained software; the author has passed away and there is no active successor project."
I personally have this installed and I feel that there's still value in keeping this in Homebrew but the URLs in the formula are dead (imap-uw has been seemingly scrubbed from University of Washington's website). As it stands, livecheck will always fail with this formula unless something changes upstream. I regularly run `brew livecheck --installed` and `brew livecheck --all`, so it would be nice to avoid unnecessary checks.
To address this issue, this PR adds support for …
> Allow :skip in livecheckables to skip formulae

- Livecheckables/imap-uw.rb
As mentioned in the comment at the top of the `imap-uw` formula, the author of `imap-uw` passed away, so the software is no longer maintained and unlikely to ever see a new version. The archives in the formula still exist, so we want to keep the formula around but it's not necessary to check for new versions.
This adds a livecheckable to skip the formula, using the new `:skip` feature. The string that's used as `:skip`'s value is a very brief message explaining why the formula is being skipped. In this case, the output looks like this:
```
imap-uw : skipped - Not maintained
```
> imap-uw: add livecheckable to skip

- Livecheckables/term.rb
`term` is one script in [a GitHub repo consisting of many scripts](https://github.com/liyanage/macosx-shell-scripts). These scripts are updated individually and no releases are made, so there doesn't appear to be a way to reliably check for new versions. Even if we could, the script hasn't been updated since 2009 and it doesn't seem likely it will be updated in the future. All in all, it makes sense to skip `term` in livecheck.
> term: add livecheckable to skip

- Livecheckables/emacs.rb
Per the [Emacs version scheme explanation](https://www.gnu.org/software/emacs/manual/html_node/efaq/Latest-version-of-Emacs.html), versions with two components (e.g., 1.2) are releases and versions with three components (e.g., 1.2.3) are development versions. This adds a regex to restrict version matching for Emacs to stable versions (those with two components).
> emacs: add livecheckable

- Livecheckables/kustomize.rb
The `kustomize` Git repo contains tags for more than just `kustomize`, so this adds a livecheckable with a regex to restrict version matching to stable versions starting with `kustomize/`.
> kustomize: add livecheckable

- Livecheckables/wrk-trello.rb
`wrk-trello` hasn't been updated since 2012 and the author has mentioned in issues that it isn't maintained. There aren't any releases tagged on GitHub, so we can't really check for new versions anyway. With this in mind, it's probably best to skip this formula until/unless something changes upstream.
> wrk-trello: add livecheckable to skip

- README.md
- Python 2.7 doesn't exist as a formula any more.
> README: Swap out `python@2` for `python` in the example code

- Livecheckables/apache-zeppelin.rb
The newest version for `apache-zeppelin` is listed as `0.8.2-docker` due to that tag existing in the Git repo. This adds a livecheckable with a regex to restrict matching to only versions without anything extra at the end (which would also filter out pre-releases, should they appear).
> apache-zeppelin: add livecheckable

- Livecheckables/embulk.rb
The existing livecheckable for `embulk` gives an error (`Unable to get versions`), so this updates the URL to use the Git repo and updates the regex accordingly.
> embulk: update url and regex

- Livecheckables/ephemeralpg.rb
The existing livecheckable gives an error (`Unable to get versions`), since the URL changed but the http://ephemeralpg.org page only uses JavaScript to redirect to the new URL (i.e., not a 301 or 302 status code). This updates the livecheckable with the new URL and replaces the loose version matching regex code with a more strict version.
> ephemeralpg: update url and regex

- Livecheckables/ephemeralpg.rb
This is a follow-up to #321. In the process of updating the URLs in the `ephemeralpg` formula, I discovered that the new URLs support HTTPS now (whereas the old ones gave an SSL error). I had mistakenly thought that the new domain/server gave SSL errors as well but that isn't the case.
This updates the URL to use `https` and further reworks the regex to be a little more strict, ensuring we wouldn't run into weird problems due to the `.*?`.
> ephemeralpg: update url and regex (again)

- Livecheckables/etsh.rb
The `etsh` livecheckable was broken and outdated, so I updated the URL (using the new domain and also switching to using the src page) and regex accordingly.
> etsh: update url and regex

- Livecheckables/exempi.rb
The existing livecheckable for `exempi` was broken due to the URL changing (from https://libopenraw.freedesktop.org/download/ to https://libopenraw.freedesktop.org/exempi/). This  updates the URL and regex to work properly.
In the future, it may be more appropriate to use https://wiki.freedesktop.org/libopenraw/Exempi/ but that page only goes up to version 2.5.0 and is missing 2.5.1 for some reason. I wrote the regex so it should match on both pages, at least.
> exempi: update url and regex

- Livecheckables/exploitdb.rb
The existing livecheckable for `exploitdb` gives an error (`Unable to get versions`), so this removes the livecheckable to allow the heuristic to take over, as it's capable of matching versions for `exploitdb` using the Git repo tags.
> exploitdb: delete

- Livecheckables/fossil.rb
The existing livecheckable for `fossil` gives an error (`Unable to get versions`), due to the download page not actually containing the version information. The version information on the page is found in a JavaScript file (`download.js`), which populates the version content on that page.
This updates the livecheckable to check `download.js` for the version information and updates the regex to be a little less strict when it comes to the whitespace but more strict when it comes to matching the version string.
> fossil: update url and regex

- Livecheckables/freeswitch.rb
The existing livecheckable for `freeswitch` gives an error (`Unable to get versions`), so this removes the URL (allowing the heuristic to take over) and updates the regex accordingly.
> freeswitch: remove url and update regex

- Livecheckables/ghc.rb
The regex for the existing `ghc` livecheckable wasn't matching any versions. This updates the regex to match all the versions on the page which follow the same format, including the latest stable version.
> ghc: update regex

- Livecheckables/git.rb
The regex in the existing `git` livecheckable wasn't matching any versions, so this updates it to address the issue.
> git: update regex

- Livecheckables/goenv.rb
The existing livecheckable for `goenv` gives an error (`Unable to get versions`), so this removes the URL (allowing the heuristic to take over) and updates the regex accordingly.
> goenv: remove url and update regex

- Livecheckables/libcerf.rb
The `libcerf` livecheckable was using the old `([0-9\.]+)` style version matching in the regex, which is too loose and can match things it shouldn't. In this case, it was matching a trailing period behind the version string and reporting the latest version as `1.13.`.
This updates the regex to use the stricter regex that has become more standard, `(\d+(?:\.\d+)+)`, which resolves this issue.
> libcerf: update regex

- Livecheckables/libressl.rb
The `libressl` livecheckable was using the old `([0-9\.]+)` style version matching in the regex, which is too loose and can match things it shouldn't. In this case, it was matching a trailing period behind the version string and reporting the latest version as `3.0.2.`.
This updates the livecheckable to use the stricter regex that has become more standard, `(\d+(?:\.\d+)+)`, which resolves this issue.
> libressl: update regex

- Livecheckables/tomcat-native.rb
Right now it looks like this,
```
Error: tomcat-native: Unable to get versions
```
After the change,
```
tomcat-native : 1.2.23 ==> 1.2.23
```
> tomcat-native: add livecheckable

- Livecheckables/tomcat.rb
- Livecheckables/tomcat@7.rb
- Livecheckables/tomcat@8.rb
- use https instead of http
- update url for tomcat one with `https://archive.apache.org/dist/tomcat/`
> Update livecheck urls for tomcat formulae

- Livecheckables/codec2.rb
`codec2` codebase moved to Github. The previous livecheckable wasn't pointing to the current version and the heuristic correctly guesses the current one.
> codec2: remove livecheckable

- Livecheckables/vapoursynth.rb
The Git tags for vapoursynth contain prerelease versions, so this adds a livecheckable to restrict matching to stable versions (e.g., `47.1`, `48` rather than `49-RC1`).
> vapoursynth: add livecheckable

- Livecheckables/rlwrap.rb
The Git tags for the `rlwrap` repo contain a snapshot version among the typical versions like `v0.43`. This adds a livecheckable to restrict matching to stable versions only.
> rlwrap: add livecheckable

- Livecheckables/crystal.rb
The Git tags for the `crystal` repo contain some non-release tags (e.g., `test-ci-1`, `tets-doc-4`) and this was causing the latest version to be erroneously reported as `4`. This adds a livecheckable to restrict version matching to only tags with stable versions.
> crystal: add livecheckable

- Livecheckables/logstash.rb
`livecheck` is currently reporting `logstash`'s latested version as `2203`, since the Git repo contains a `pull/2203` tag. This adds a livecheckable to restrict matching to typical numeric versions and only stable versions (no `-snapshot1`, etc).
> logstash: add livecheckable

- Livecheckables/openshift-cli.rb
The existing livecheckable for `openshift-cli` was erroneously reporting the latest version as `3.11.0` (rather than `4.1.0`). This removes the URL (allowing the heuristic to use the Git tags) and updates the regex accordingly.
> openshift-cli: remove url and update regex

- Livecheckables/libdnet.rb
The latest version for `libdnet` was being reported as `2001-Oct-11` (rather than `1.12`), so this adds a livecheckable to restrict matching (of Git tags) to those starting with `libdnet-` and only stable versions (nothing trailing the numeric version).
> libdnet: add livecheckable

- Livecheckables/docker-credential-helper-ecr.rb
The Git repo for `docker-credential-helper-ecr` contains a `amzn2/0.3.0-1` tag, so the latest version was being reported as `2/0.3.0-1`. This adds a livecheckable to restrict matching to versions like `v0.4.0` and only stable versions (nothing trailing the version).
> docker-credential-helper-ecr: add livecheckable

- Livecheckables/mozjpeg.rb
The `mozjpeg` Git repo contains a number of tags that aren't for release versions, so the latest version was being reported as `8d` (rather than `3.3.1`). This adds a livecheckable to restrict matching to versions like `v3.3.1` and only stable versions (nothing trailing like `-pre`, etc).
> mozjpeg: add livecheckable

- Livecheckables/nethack.rb
The latest version being reported for `nethack` was `3.7.0_WIP-2020-02-14`, which is a prerelease version. This adds a livecheckable that restricts verson matching to release versions but, unfortunately, the resulting version is like `3.6.6_Released` or `3.6.2_Release`.
Currently, `livecheck` isn't so smart in the way it's dealing with the resulting version string. In this case, it would be better if livecheck only used the capture group in the regex (resulting in something like `3.6.6` here) rather than the capture group and everything past it. This is something that will need to be handled in another PR and isn't appropriate here. Any system-wide changes to fix the issue will automatically address this particular wrinkle without needing any changes to the livecheckable.
In the interim …
> nethack: add livecheckable

- Livecheckables/clojure.rb
`Error: clojure: Unable to get versions`
`clojure : 1.10.1.510 ==> 1.10.1.536`
> clojure: add livecheckable

- Livecheckables/udunits.rb
`udunits` codebase is now on Github and the heuristic is able to find the latest version.
> udunits: remove livecheckable

- Livecheckables/docker-compose-completion.rb
The latest version for `docker-compose-completion` was being reported as `1.26.0-test`. There are some other unrelated tags in the Git repo, so this adds a livecheckable to restrict version matching to those like `1.25.4` and only stable versions.
> docker-compose-completion: add livecheckable

- Livecheckables/fluxctl.rb
The latest version of `fluxctl` was being reported as `9a99` (instead of `1.18.0`), due to a `master-ccb9a99` tag in the Git repo. This adds a livecheckable to restrict version matching to those like `1.18.0` (nothing before or after), to only match `fluxctl` versions (not `chart`, `helm`, etc.) and only stable versions.
> fluxctl: add livecheckable

- Livecheckables/alure.rb
```
$ brew livecheck alure
Error: alure: Unable to get versions
```
```
$ brew livecheck alure
alure : 1.2 ==> 1.2
```
> alure: add livecheckable

- Livecheckables/ascii.rb
```
$ brew livecheck ascii
Error: ascii: Unable to get versions
```
```
$ brew livecheck ascii
ascii : 3.18 ==> 3.18
```
> ascii: add livecheckable

- Livecheckables/serf.rb
`serf` codebase is now on Github and the heuristic is able to find the latest version.
> serf: remove livecheckable

- Livecheckables/atool.rb
```
$ brew livecheck atool
Error: atool: Unable to get versions
```
```
$ brew livecheck atool
atool : 0.39.0 ==> 0.39.0
```
> atool: add livecheckable

- Livecheckables/atool.rb
This is a follow-up PR to #354, since I couldn't get to it before it was merged and there were a few items that could have been addressed.
Since we're using the `tar.gz` file in the formula, we only want to match those archives on this page. Usually we do this by adding `\.t` after the numeric portion of the regex (as the archive could be `tar.gz`, `tar.xz`, `tar.bz2`, etc. and needs to be somewhat generic).
Additionally, we want to match the `href` attributes of the links rather than any text in the HTML. Index pages like this sometimes truncate the text for the filename, so we can run into matching problems if this occurs.
With these two ideas in mind the regex would be: `/href="atool-(\d+(?:\.\d+)+)\.t/`
Additionally, you can sometimes add `?C=M&O=D` to the end of index pages like …
> atool: update url and regex

- Livecheckables/alluxio.rb
```
$ brew livecheck alluxio
Error: alluxio: Unable to get versions
```
There is some issue
```
$ brew livecheck alluxio
alluxio : 1.8.1 ==> 2.1.2
```
> alluxio: add livecheckable

- Livecheckables/awscli.rb
```
$ brew livecheck awscli
awscli (guessed) : 2.0.0 ==> 2.0.2
```
> awscli: remove livecheckable

- Livecheckables/vips.rb
```
$ brew livecheck vips
Error: vips: Unable to get versions
```
```
$ brew livecheck vips
vips (guessed) : 8.9.1 ==> 8.9.1
```
> vips: remove livecheckable

- Livecheckables/sshfs.rb
```
$ brew livecheck sshfs
sshfs : 2.10 ==> 3.7.0
```
failed attempt to upgrade it to 3.6.0 (https://github.com/Homebrew/homebrew-core/pull/47971)
> sshfs: update url and regex

- Livecheckables/ibex.rb
```
$ brew livecheck ibex
Error: ibex: Unable to get versions
```
```
$ brew livecheck ibex
ibex : 2.8.2 ==> 2.8.7
```
> ibex: update regex

- Livecheckables/verilator.rb
```
$ brew livecheck verilator
verilator : 4.028 ==> 4.030
```
> verilator: update url and regex

- Livecheckables/wiredtiger.rb
```
$ brew livecheck wiredtiger
Error: vips: Unable to get versions
```
```
$ brew livecheck wiredtiger
wiredtiger : 3.2.0 ==> 3.2.1
```
> wiredtiger: update url and regex

- Livecheckables/povray.rb
```
$ brew livecheck povray
povray : 3.7.0.8 ==> 3.7.0.20140613
```
latest version should be `3.7.0.8` instead of `3.7.0.20140613`
<details>
<summary>brew livecheck povray --debug</summary>
```
Trying with url https://github.com/POV-Ray/povray/archive/v3.7.0.8.tar.gz
Possible git repo detected at https://github.com/POV-Ray/povray.git
v3.7.0.0 => #<Version:0x00007f9a11a189e0 @version="3.7.0.0", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 7>, #<Version::NumericToken 0>, #<Version::NumericToken 0>]>
v3.7.0.1 => #<Version:0x00007f9a11a188f0 @version="3.7.0.1", @tokens=[#<Version::NumericToken 3>, #<Version::NumericToken 7>, #<Version::NumericToken 0>, #<Version::NumericToken 1>]>
v3.7.0.2 => #<Version:0x00007f9a11a18828 @version="3.7.0.2", @tokens=[#<Version::NumericToken 3>, …
```
> povray: update url and regex

- Livecheckables/htpdate.rb
Right now it takes too much time to check on it locally.
```
Loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/Livecheckables/htpdate.rb
Trying with url http://www.vervest.org/htp/archive/c/?C=M&O=D
Using page_match("http://www.vervest.org/htp/archive/c/?C=M&O=D", "(?-mix:href="htpdate-(\d+(?:\.\d+)+)\.t)")
Error: htpdate: execution expired
```
> htpdate: update url and regex

- Livecheckables/percona-xtrabackup.rb
```
$ brew livecheck percona-xtrabackup
percona-xtrabackup : 2.4.14 ==> 8.0.9
```
> percona-xtrabackup: update url and regex

- Livecheckables/libnice.rb
404 for `https://libnice.freedesktop.org/releases/`, so I switch to github url.
```
$ brew livecheck libnice
libnice : 0.1.16 ==> 0.1.16
```
> libnice: update url and regex

- Livecheckables/mupdf-tools.rb
```
$ brew livecheck mupdf-tools
mupdf-tools : 1.16.1 ==> 1.16.1
```
> mupdf-tools: update url

- Livecheckables/kitchen-sync.rb
release url, https://github.com/willbryant/kitchen_sync/releases
```
$ brew livecheck kitchen-sync
kitchen-sync : 2.0 ==> 2.0
```
> kitchen-sync: update url and regex

- Livecheckables/jython.rb
release url, https://github.com/jythontools/jython/releases
```
$ brew livecheck jython
jython : 2.7.1 ==> 2.7.1
```
> jython: update url and regex

- Livecheckables/john-jumbo.rb
The version is 1.9.0
But it installed the jump release 1.9.0-Jumbo-1, which is different from core version, `1.9.0`
```
$ brew livecheck john-jumbo
john-jumbo : 1.9.0 ==> 1.9.0-Jumbo-1
```
Need some discussion and review in here.
> john-jumbo: update url and regex

- Livecheckables/influxdb.rb
```
$ brew livecheck influxdb
influxdb : 1.7.9 ==> 1.7.10
```
relates to this https://github.com/Homebrew/homebrew-core/pull/49900 (1.7.10 upgrade)
> influxdb: update url and regex

- Livecheckables/mkvtoolnix.rb
The existing livecheckable for `mkvtoolnix` gives an error (`Unable to get versions`), so this updates the regex accordingly.
My review of #397 would have been a complete replacement of the changes in that PR, so it made more sense to create a different PR to address this. Closes #397.
> mkvtoolnix: update regex

- Livecheckables/activemq.rb
- Livecheckables/apache-opennlp.rb
- Livecheckables/apache-spark.rb
- Livecheckables/apr-util.rb
- Livecheckables/apr.rb
- Livecheckables/avro-c.rb
- Livecheckables/avro-cpp.rb
- Livecheckables/derby.rb
- Livecheckables/fop.rb
- Livecheckables/fuseki.rb
- Livecheckables/hadoop.rb
- Livecheckables/hbase.rb
- Livecheckables/hive.rb
- Livecheckables/httpd.rb
- Livecheckables/jena.rb
- Livecheckables/kafka.rb
- Livecheckables/nifi-registry.rb
- Livecheckables/nifi.rb
- Livecheckables/solr.rb
- Livecheckables/sqoop.rb
- Livecheckables/storm.rb
- Livecheckables/tika.rb
- Livecheckables/tomcat.rb
- Livecheckables/xerces-c.rb
- Livecheckables/xml-security-c.rb
- Livecheckables/zookeeper.rb
- livecheck/heuristic.rb
Fetches version numbers for Apache-hosted projects at archive.apache.org by checking the directory listing for the parent directory of the path component where the version number first appears, and removed livecheckables that are covered by the new check. Also updated `zookeeper` and added an entry for `sqoop` which has an odd way of [marking prerelease versions](http://sqoop.apache.org/).
> heuristic: add apache.org check

- Livecheckables/jbig2dec.rb
The artifact is part of the release (https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs950)
```
$ brew livecheck jbig2dec
jbig2dec : 0.17 ==> 0.17
```
> jbig2dec: update url and regex

- Livecheckables/gcc.rb
With the change
```
$ brew livecheck gcc
gcc : 9.2.0 ==> 9.2.0
```
> gcc: update url and regex

- Livecheckables/nss.rb
The existing `nss` livecheckable wasn't finding the latest version (3.51) on the [NSS Releases page](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_Releases) and was instead reporting `3.50` as the lasted version. This was due to the link for the 3.51 release using a full URL, rather than a relative URL. The old regex was only capable of matching relative URLs, do this loosens the leading path portion of the regex to avoid this issue.
This also updates the (old) loose regex for matching numeric versions with the more explicit version we use nowadays.
> nss: update regex

- Livecheckables/libosinfo.rb
The existing `libosinfo` livecheckable wasn't matching the latest versions because the regex was restricted to `tar.gz` files and the newest versions are `tar.xz` files. This updates the regex to loosen the matching to `\.t` (to avoid this particular issue) and also restricts matching to `href` attributes (since this is generally more reliable than matching text across the whole page, as index pages can truncate file name text and potentially give us bad matches). This is an index page, so I also added `?C=M&O=D` to the end of the URL to sort the files, just for good measure.
> libosinfo: update url and regex

- Livecheckables/qscintilla2.rb
The archive file names on the [Qscintilla download page](https://www.riverbankcomputing.com/software/qscintilla/download) have gone from being like `QScintilla_gpl-2.11.2.tar.gz` to `QScintilla-2.11.3.tar.gz`, so livecheck wasn't finding the newest versions. This updates the regex as follows:
* Allow for text to optionally appear between the start of the filename ("QScintilla") and the numeric version (e.g., `2.11.4`)
* Restrict matching to `href` attributes
* Do case-insensitive matching (so we don't have to update the regex again if filenames switch to something like `qscintilla-2.11.4.tar.gz` in the future)
* Use the more explicit numeric version regex in place of the (old) loose regex
> qscintilla2: update regex

- Livecheckables/aubio.rb
```
Trying with url https://aubio.org/pub/
Using page_match("https://aubio.org/pub/", "(?-mix:href="aubio-(\d+(?:\.\d+)+)\.t)")
Error: aubio: execution expired
```
```
Trying with url https://aubio.org/pub/
Using page_match("https://aubio.org/pub/", "(?-mix:aubio-(\d+(?:\.\d+)+)\.t)")
0.1.4, 0.1.4, 0.1.5, 0.1.5, 0.1.6, 0.1.6, 0.1.7.1, 0.1.7.1, 0.1.7, 0.1.7, 0.1.8, 0.1.8, 0.2.0, 0.2.0, 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.3.2, 0.3.2, 0.4.0, 0.4.0, 0.4.0, 0.4.0, 0.4.0, 0.4.0, 0.4.0, 0.4.0, 0.4.1, 0.4.1, 0.4.1, 0.4.1, 0.4.1, 0.4.1, 0.4.1, 0.4.1, 0.4.2, 0.4.2, 0.4.2, 0.4.2, 0.4.2, 0.4.2, 0.4.2, 0.4.2, 0.4.3, 0.4.3, 0.4.3, 0.4.3, 0.4.3, 0.4.3, 0.4.3, 0.4.3, 0.4.3, 0.4.3, 0.4.4, 0.4.4, 0.4.4, 0.4.4, 0.4.4, 0.4.4, 0.4.4, 0.4.4, 0.4.4, 0.4.4, 0.4.5, 0.4.5, 0.4.5, 0.4.5, 0.4.5, 0.4.5, 0.4.5, 0.4.5, …
```
> aubio: update regex

- Livecheckables/ipfs.rb
The existing livecheckable for `ipfs` was giving a prerelease version as newest (`0.5.0-dev-8to9pre2`). This livecheckable was using the GitHub release page, so this removes the URL (allowing the heuristic to use the Git repo instead) and updates the regex to restrict matching to stable versions.
> ipfs: remove url and update regex

- Livecheckables/nuget.rb
The existing livecheckable for `nuget` seems to be checking for something completely unrelated (`bmake`), so livecheck is giving an incorrect version as the newest (`20200212` rather than `5.4.0`).
The `nuget` formula uses `nuget.org` when downloading the archive but the [nuget.org downloads page](https://www.nuget.org/downloads) uses JavaScript to display the download/version information. This modifies the livecheckable to check the JSON file that's used to populate the version information on the downloads page and updates the regex accordingly.
> nuget: update url and regex

- Livecheckables/squid.rb
The existing livecheckable for `squid` was reporting `3.5.28` as the newest version (instead of `4.10`), due to the URL still using the `3.5` series release page. This updates the URL to use the v4 release page, which fixes the issue until a new major version becomes stable (e.g., v5).
This also replaces the (old) loose numeric version matching regex with the more explicit regex we use these days and makes the regex case-insensitive (to avoid any related issues in the future).
> squid: update url and regex

- Livecheckables/freeradius-server.rb
The existing livecheckable for `freeradius-server` wasn't finding the latest version (giving `3.0.19` instead of `3.0.20`). This removes the URL (allowing the heuristic to check the Git tags) and updates the regex accordingly.
The tags in the Git repo are like `release_3_0_20`, so the reported version is formatted like `3_0_20` but this is the same as `3.0.20` from a comparison standpoint.
> freeradius-server: update url and regex

- Livecheckables/mawk.rb
The existing livecheckable for `mawk` was using wildcard matches `.*` which were escaping the bounds of the `href` attribute. As a result, the latest version was being given as `1.3.4-20200120.tgz">mawk-1.3.4-20200120`, instead of `1.3.4-20200120`. I've warned about this when providing feedback about livecheck PRs and this is a perfect example of why we almost always avoid using the `.` wildcard in livecheckable regexes.
This resolves the issue by reworking the regex to accomplish the same thing in a safer, more explicit fashion. This is an index page, so I also added `?C=M&O=D` to the end of the URL, to sort the archive files in descending order, for good measure.
> mawk: update url and regex

- Livecheckables/flashrom.rb
The existing livecheckable for `flashrom` wasn't finding the latest version (giving `1.0` instead of `1.2`). This was because the regex was created with the expectation that file names would be like `flashrom-1.0.tar.bz2` but the newest versions are like `flashrom-v1.2.tar.bz2` (note the `v` before the version number). As a result, versions beyond `1.0` (`v1.0.1`, `v1.1`, and `v1.2`) weren't identified by livecheck.
This updates the regex to allow for an optional `v` and also replaces the (old) loose regex for matching numeric versions with the more explicit version we use these days. This is an index page but I did not add `?C=M&O=D` to the end of the URL because the server doesn't respond to the query string values (i.e., there's no change in sorting).
> flashrom: update regex

- Livecheckables/digdag.rb
```
$ brew livecheck digdag --debug
...
v0.9.9 => #<Version:0x00007fb9074642c8 @version="0.9.9", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 9>, #<Version::NumericToken 9>]>
v0_10_before_merge_v0_9_38 => #<Version:0x00007fb9074641b0 @version="0_10_before_merge_v0_9_38", @tokens=[#<Version::NumericToken 0>, #<Version::NumericToken 10>, #<Version::StringToken "before">, #<Version::StringToken "merge">, #<Version::StringToken "v0">, #<Version::NumericToken 9>, #<Version::NumericToken 38>]>
digdag : 0.9.41 ==> 0_10_before_merge_v0_9_38
```
```
$ brew livecheck digdag
digdag : 0.9.41 ==> 0.9.41
```
> digdag: update regex

- Livecheckables/disktype.rb
```
$ brew livecheck disktype --debug
...
Trying with url https://git.code.sf.net/p/disktype/disktype.git
Possible git repo detected at https://git.code.sf.net/p/disktype/disktype.git
c99-branchpoint => #<Version:0x00007fcff69104b0 @version="99-branchpoint", @tokens=[#<Version::NumericToken 99>, #<Version::StringToken "branchpoint">]>
release_1 => #<Version:0x00007fcff69101e0 @version="1", @tokens=[#<Version::NumericToken 1>]>
release_2 => #<Version:0x00007fcff6910118 @version="2", @tokens=[#<Version::NumericToken 2>]>
release_3 => #<Version:0x00007fcff6910050 @version="3", @tokens=[#<Version::NumericToken 3>]>
release_4 => #<Version:0x00007fcff691b860 @version="4", @tokens=[#<Version::NumericToken 4>]>
release_5 => #<Version:0x00007fcff691bea0 @version="5", …
```
> disktype: add livecheckable

- Livecheckables/afl-fuzz.rb
The existing livecheckable for `afl-fuzz` was giving the latest version as `2.52b` (instead of `2.56` or `2.56b`). This removes the URL (allowing the heuristic to check the Git tags, since the formula uses the releases from GitHub) and updates the regex accordingly.
The version from the formula is reported as `2.56` (it's actually `2.56b`) but the version from the Git tag is `2.56b`. I'll address mismatches like this in a future commit that should automatically fix this for a number of formulae/livecheckables with issues like this.
> afl-fuzz: remove url and update regex

- Livecheckables/igv.rb
The existing livecheckable for `igv` was reporting the newest version as `9` (instead of `2.8.1`) due to a `test9` tag in the Git repo. This adds a regex to restrict matching to versions like `v1.2.3` and only stable versions (no `-rc1`, etc.).
> igv: add regex

- Livecheckables/spades.rb
The existing livecheckable for `spades` was giving the newest version as `3.11.1` (instead of `3.14.0`). This updates the URL to use the files index page of the upstream server (used in the formula's stable URL) and updates the regex accordingly.
> spades: update url and regex

- Livecheckables/frotz.rb
Current livecheck behavior
```
Error: frotz: Unable to get versions
```
After the change.
```
frotz : 2.51 ==> 2.51
```
> frotz: add livecheckable

- Livecheckables/hypre.rb
The existing livecheckable for `hypre` wasn't finding the newest versions (giving `2.11.2` instead of `2.18.2`). This removes the URL (allowing the heuristic to use the Git tags) and updates the regex accordingly.
> hypre: remove url and update regex

- Livecheckables/lablgtk.rb
The existing livecheckable for `lablgtk` wasn't finding the latest versions (giving `2.18.8` instead of `3.1.0`). The `lablgtk` formula is using the upstream GitHub repo releases, so this removes the URL (allowing the heuristic to use the Git tags) and updates the regex accordingly.
> lablgtk: remove url and update regex

- Livecheckables/voldemort.rb
The existing livecheckable for `voldemort` wasn't finding the newest version (giving `1.10.25` instead of `1.10.26`). This removes the URL (allowing the heuristic to use the Git tags, which are better than the GitHub releases page) and updates the regex accordingly. [Note: I've made the leading `release-` and trailing `-cutoff` text optional, in case this software gets updated in the future and the tags change to a more `1.2.3` or `v1.2.3` format.]
The only issue here is that the latest version is now given as `1.10.26-cutoff` (instead of `1.10.26`). This will be addressed in a future PR that will fix this category of issues for all affected checks (that match Git repo tags). This will be automatically fixed when that PR is merged, so all we need to worry about here is finding the newest …
> voldemort: remove url and update regex

- Livecheckables/xboard.rb
`livecheck` was using the Git repo tags for `xboard`, which contain a number of tags for other things (e.g., `master-20140119`, `gtk-20100806`), so the newest version was being given as `20140119`. This could be addressed by adding a livecheckable with a regex to restrict the tags (as in #434) but it made more sense to use the index page where the stable archives are hosted (since we typically want to align with where we download archives from).
This was a full rewrite of the `xboard` livecheckable, so it was more fitting to open a PR that closes #434.
> xboard: add livecheckable

- Livecheckables/agedu.rb
The existing livecheckable for `agedu` used a regex with a capture group that spanned the entire alphanumeric part of the version string (`20200206.963bc9d`), whereas the version from the formula is like `20200206`. In a forthcoming PR (related to #408), we will be using the capture group as the version instead of the Git strategy's default behavior (using the part of the string from the first number onward), so this prepares for that change.
> agedu: update regex

- Livecheckables/bfg.rb
The existing livecheckable for `bfg` used a regex with a capture group that included the numeric version as well as the leading `v` (e.g., `v1.13.0`), whereas we want the version from livecheck to be like `1.13.0`.
In a forthcoming PR (related to #408), we will be using the capture group as the version instead of the Git strategy's default behavior (using the part of the string from the first number onward), so this prepares for that change.
> bfg: update url and regex

- Livecheckables/clinfo.rb
The existing livecheckable for `clinfo` used a regex with a capture group that only addressed the first two numeric parts of the version string (`2.2`), whereas the versions are much longer (`2.2.18.04.06`) and we want to capture all of it. This updates the regex to use the standard regex for Git tags, which captures the entire numeric version.
In a forthcoming PR (related to #408), we will be using the capture group as the version instead of the Git strategy's default behavior (using the part of the string from the first number onward), so this prepares for that change.
> clinfo: update url and regex

- Livecheckables/disktype.rb
The existing livecheckable for `disktype` used a regex with no capture group, whereas we want to be capturing a version like `9` (from `release_9`). This updates the regex to add a capture group around the `\d+` part of the regex.
In a forthcoming PR (related to #408), we will be using the capture group as the version (when available) instead of the Git strategy's default behavior (using the part of the string from the first number onward), so this prepares for that change.
> disktype: update regex

- Livecheckables/ipbt.rb
The existing livecheckable for `ipbt` used a regex with a capture group that spanned the entire alphanumeric part of the version string (`20190601.d1519e0`), whereas we want a version like `20190601` (to match the formula version). This updates the regex to only capture the first numeric part of the version.
In a forthcoming PR (related to #408), we will be using the capture group as the version (when available) instead of the Git strategy's default behavior (using the part of the string from the first number onward), so this prepares for that change.
> ipbt: update regex

- Livecheckables/spigot.rb
The existing livecheckable for `spigot` used a regex with a capture group that spanned the entire alphanumeric part of the version string (`20200101.b1b0b20`), whereas we want a version like `20200101` (to match the formula version). This updates the regex to only capture the first numeric part of the version.
In a forthcoming PR (related to #408), we will be using the capture group as the version (when available) instead of the Git strategy's default behavior (using the part of the string from the first number onward), so this prepares for that change.
> spigot: update regex

- Livecheckables/wapm.rb
The existing livecheckable for `wapm` used a regex with a capture group that didn't capture the full numeric version (it was missing the first digit, like `.5.0`), whereas we want a version like `0.5.0` (to match the formula version). This updates the regex to capture the entire numeric version.
This regex was also restricting matching to versions where the major version wasn't `3`, to avoid an issue where the git tags contained a `3.2` tag but the actual releases were like `0.5.0`. If there's ever a `3` major version, this wouldn't find those versions. Instead, we can accomplish what we want by only matching versions with three or more parts (e.g., `1.2.3` not `1.2`). This regex wouldn't match a version with only two parts, so that would be a problem if a valid version like that appears, …
> wapm: update regex and add explanatory comment

- Livecheckables/interactive-rebase-tool.rb
The existing livecheckable for `interactive-rebase-tool` was using a poorly-written regex that was only matching part of the numeric version (`1.` instead of the full `1.2.1`). This replaces the regex with the standard regex for Git tags, which works as expected.
> interactive-rebase-tool: update regex

- Livecheckables/v2ray-plugin.rb
The Git tags in the `v2ray-plugin` repository are typically like `v1.3.0` but there are a couple like `v20190114` that are causing the latest version to be erroneously reported as 20190114 (instead of `1.3.0`). This adds a livecheckable with a regex to restrict matching to versions like `v1.3.0` (and only stable releases).
> v2ray-plugin: add livecheckable

- Livecheckables/libpq.rb
`libpq` was giving an `Unable to get versions` error, due to the heuristic not being able to find any versions. This adds a livecheckable to address the issue.
> libpq: add livecheckable

- Livecheckables/openssl.rb
`openssl` is no longer a formula for v1.0 and is instead an alias of `openssl@1.1` at the moment. This livecheckable is no longer needed, so it should be removed.
> openssl: delete

- cmd/livecheck.rb
- livecheck/heuristic.rb
- livecheck/utils.rb
- [`Layout/LineLength`](https://github.com/Homebrew/brew/commit/cd3ced48e97f8fdab67b0737ba5441d4057457e9) was decreased and [`Layout/IfUnlessModifier`](https://github.com/Homebrew/brew/commit/cd3ced48e97f8fdab67b0737ba5441d4057457e9) and [`Style/ConditionalAssignment`](https://github.com/Homebrew/brew/commit/4498303f9a347184d9fc0bb6e93351bbfc4d1091) were enabled this weekend in Homebrew/brew (and hence `brew style` surfaces them here).
- This doesn't fix Livecheckables as they're annoyingly mostly _just_ above the LineLength limit. I'll leave those to people more experienced with livecheck regex syntax.
> Fix newly-tweaked RuboCop style offenses in main Livecheck code

- Livecheckables/ats2-postiats.rb
- Livecheckables/berkeley-db.rb
- Livecheckables/capstone.rb
- Livecheckables/zabbix.rb
`brew style .` was recently added to the livecheck CI but failed. This PR fixes the errors produced by `brew style .`
Notice that there is also one outstanding warning that I believe is bug we didn't spot before:
```
== cmd/livecheck.rb ==
W: 53: 12: Use == if you meant to do a comparison or wrap the expression in parentheses to indicate you meant to assign in a condition.
```
A value is assigned to the `cmd` variable in the conditional of an `if` statement. I didn't touch it yet since the code works this way for now.
> Fix brew style in livecheck

- livecheck/heuristic.rb
This fixes #408 (and is related to #443) but also addresses a number of issues with unwanted trailing text in versions when using the Git strategy (i.e., finding versions in Git tags from the upstream repository).
By default, the Git strategy will "clean" tags by removing any characters before the first number. However, as seen in #408, this didn't work correctly when the software name includes a number and precedes the numeric version (e.g., `ekg2_0.3.1`). In this case, the version number included everything after the first digit (`2_0.3.1`) instead of just the version (`0.3.1`). This couldn't be fixed with a regex, as regexes were only used in the Git strategy for filtering tags.
This resolves the issue by optionally using the first capture group in the regex match, when available. If a …
> heuristic: allow use of capture group for version

- Livecheckables/ekg2.rb
The Git tags for the `ekg2` repository contain prerelease versions, so this adds a livecheckable to restrict matching to only stable versions.
> ekg2: add livecheckable

- Livecheckables/fortune.rb
before:
```
Error: fortune: Unable to get versions
```
after:
```
fortune : 9708 ==> 9708
```
> fortune: add livecheckable

- Livecheckables/scummvm.rb
before:
```
scummvm (guessed) : 2.1.1 ==> 2010-testbed
```
after:
```
scummvm : 2.1.1 ==> 2.1.1
```
> scummvm: update url and regex

- cmd/livecheck.rb
This is a very simple addition that skips lines beginning with `#` in the `~/.brew_livecheck_watchlist` file.
This allows users to comment out lines, rather than only being able to remove/replace lines. I often run livecheck on a subset of formulae and having to manage my watchlist without being able to comment things out can be a pain at times.
> Allow comments in .brew_livecheck_watchlist

- Livecheckables/amdatu-bootstrap.rb
- Livecheckables/fantom.rb
- Livecheckables/fuse-zip.rb
- Livecheckables/mecab-ko-dic.rb
- Livecheckables/mecab-ko.rb
- Livecheckables/ode.rb
- Livecheckables/ompl.rb
- Livecheckables/sagittarius-scheme.rb
- Livecheckables/x265.rb
- livecheck/heuristic.rb
Similar to #317, fetches version numbers for Bitbucket-hosted projects by checking either their lists of downloads or tags, and removes livecheckables that are covered by the new check. Also adds livecheckables for `amdatu-bootstrap`, `mecab-ko`, and `mecab-ko-dic` which have unusual version number schemes.
> heuristic: add bitbucket.org check

- Livecheckables/dbus.rb
As surfaced in #461, [`dbus` uses even-numbered minor versions to indicate stable releases](https://wiki.freedesktop.org/www/Software/dbus/#index5h1) and odd-numbered minor versions to indicate development releases. We only want to use stable releases, so this adds a livecheckable to restrict matching to versions with an even-numbered minor version.
> dbus: add livecheckable

- Livecheckables/py2cairo.rb
As seen in Homebrew/homebrew-core#50871, `py2cairo` should be restricted to versions below 1.19 (as newer versions only support Python 3). This formula may be deleted in the future but for now it would be good to restrict livecheck to only match versions below 1.19.
> py2cairo: add livecheckable

- Livecheckables/wp-cli.rb
- livecheck/heuristic.rb
This adds a livecheckable for `wp-cli` that makes it only check the release that's marked as "latest" on GitHub. There's a `2.4.1` version on GitHub (which livecheck is reporting as newest) but the ["latest" release](https://github.com/wp-cli/wp-cli/releases/latest) is currently 2.4.0 and [the README on GitHub](https://github.com/wp-cli/wp-cli/blob/master/README.md#wp-cli) corroborates that this is the latest stable version.
For what it's worth, to make this work, it was necessary to exclude URLs that contain `/latest` from using the Git strategy by default, otherwise we're unable to do a page match. I tested the other formulae containing `/latest` URLs (`kotlin`, `prometheus`, `pyenv-virtualenv`, `sysdig`) and they continue to work fine.
> wp-cli: add livecheckable

- Livecheckables/apache-zeppelin.rb
`apache-zeppelin` was [removed from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/50688).
> apache-zeppelin: remove livecheckable

- cmd/livecheck.rb
1. Add `--full-name` flag to use fully-qualified formulae names in reports.
2. Move formatted strings (`formula_s`, `current_s`, etc) to the corresponding `if` block to avoid evaluating them when they're not needed.
3. Squash
```ruby
needs_to_show = is_outdated || !Homebrew.args.newer_only?
if needs_to_show
```
into
```ruby
if is_outdated || !Homebrew.args.newer_only?
```
> Add --full-name flag

- cmd/livecheck.rb
This simply shortens a line added in #311 that `brew style` now deems too long.
> Shorten a line that's too long

- Livecheckables/arx-libertatis.rb
```
$ brew livecheck arx-libertatis
arx-libertatis (guessed) : 1.1.2 ==> 1.21
```
<details>
<summary>brew livecheck arx-libertatis --debug</summary>
```
Trying with url https://github.com/arx/ArxLibertatis.git
Possible git repo detected at https://github.com/arx/ArxLibertatis.git
1.0 => #<Version:0x00007fa201a0abb8 @version="1.0", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>]>
1.0.1 => #<Version:0x00007fa201a0aaf0 @version="1.0.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 1>]>
1.0.2 => #<Version:0x00007fa201a0aa28 @version="1.0.2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 0>, #<Version::NumericToken 2>]>
1.0.3 => #<Version:0x00007fa201a0a960 @version="1.0.3", @tokens=[#<Version::NumericToken 1>, …
```
> arx-libertatis: add livecheckable

- Livecheckables/i386-elf-gdb.rb
```
$ brew livecheck i386-elf-gdb
i386-elf-gdb (guessed) : 9.1 ==> 20131001
```
<details>
<summary>brew livecheck gtksourceviewmm --debug</summary>
```
w32api-2_2 => #<Version:0x00007ff7cc802fc0 @version="32api-2_2", @tokens=[#<Version::NumericToken 32>, #<Version::StringToken "api">, #<Version::NumericToken 2>, #<Version::NumericToken 2>]>
x86_64versiong3 => #<Version:0x00007ff7cc802a20 @version="86_64versiong3", @tokens=[#<Version::NumericToken 86>, #<Version::NumericToken 64>, #<Version::StringToken "versiong3">]>
i386-elf-gdb (guessed) : 9.1 ==> 20131001
```
</details>
```
$ brew livecheck i386-elf-gdb
i386-elf-gdb : 9.1 ==> 9.1
```
> i386-elf-gdb: add livecheckable

- env.sh
> delete env.sh script

- cmd/livecheck.rb
I previously set the heuristic to skip Gist URLs but this can lead to a generic "Unable to get versions" message when the only URL is a Gist. Currently, the only formula meeting this criteria is `browser`. I was planning on creating a `:skip` livecheckable for `browser` but I thought it might be better to automatically do this in livecheck for similar formulae that may pop up in the future (hopefully none, to be honest).
This PR modifies the existing logic for the `:skip` feature such that `livecheck` will automatically skip formulae with `gist.github.com` in `stable.url` and present the following output:
```
browser : skipped - Stable URL is a GitHub Gist
```
Is this something that we're interested in or do you think it would be better to simply create a `:skip` livecheckable for …
> Skip formulae with gist.github.com stable URL

- Livecheckables/syck.rb
`syck` hasn't been actively developed or maintained for quite some time. why hasn't been around since 2009 and this repo (a copy of the last version but with some additional updates since 2009) hasn't been updated since 2012. I don't imagine this situation will change, so we're better off skipping it in livecheck.
> syck: add livecheckable to skip

- Livecheckables/libsodium.rb
The `libsodium` Git tags typically have a format like `1.0.18` but the latest release also has a `1.0.18-RELEASE` tag, which is being presented as a new version (in comparison to `1.0.18`). The `libsodium` formula uses an archive from https://download.libsodium.org/libsodium/releases/, so this adds a livecheckable to look for new versions on that index page instead.
> libsodium: add livecheckable

- Livecheckables/giflib.rb
There are a number of other formulae that meet these same criteria and need to be fixed in the future but we're temporarily holding off on creating/editing a large number of livecheckables until I've implemented some forthcoming features. I'm just tackling a few of the more popular formulae (more than 10,000 installs over 90 days) since they've been bothering me.
> giflib: add livecheckable

- Livecheckables/libsoxr.rb
> libsoxr: add livecheckable

- Livecheckables/epsilon.rb
> epsilon: add livecheckable

- Livecheckables/vde.rb
> vde: add livecheckable

- Livecheckables/libusb-compat.rb
> libusb-compat: add livecheckable

- livecheck/heuristic.rb
This modifies the Hackage strategy in the heuristic so that it uses `URI.open(haskell_pkg_url).read` instead of running `curl -s "#{haskell_pkg_url}"`.
At least on my machine, the Hackage strategy appeared to be broken before and gave an error (e.g., `Error: bench: Version value must be a string; got a NilClass ()`) but works properly after this change.
> Update Hackage strategy

- Livecheckables/djvulibre.rb
Followup of PR, #405.
```
$ brew livecheck djvulibre
djvulibre : 3.5.27 ==> 3.5.27
```
> djvulibre: use sourceforge as artifact ref

- Livecheckables/geoserver.rb
#514 added a livecheckable for `geoserver` to work around the issue with the SourceForge RSS feed not being reliable for this particular software (due to the RSS feed containing a large number of different files for each release, resulting in older releases being pushed out of the RSS feed and not being found by livecheck). This resolves the issue in a different manner, using the GitHub repo tags to look for new versions, which is much more reliable in this scenario.
Usually we prefer to check for versions from a similar location as the stable archive but it makes sense to make an exception here.
> geoserver: update url and regex

- Livecheckables/frege.rb
#512 added a livecheckable for `frege` but used the GitHub releases page. In the case of `frege`, there are a number of unstable releases which could push the latest stable release off of the first page at some point, breaking the check.
This modifies the livecheckable to use the URL for the `latest` release and updates the regex to be a little more loose in one way (not just matching releases ending with `public`) and more specific in others (more specific version regex and looking for URLs for `.jar` files only).
> frege: update url and regex

- Livecheckables/olsrd.rb
The `olsrd` formula has a comment saying "olsr's website is 'ill' and does not contain the latest release." The formula is using a release from the GitHub repo, so this removes the existing livecheckable's URL (allowing the heuristic to use the Git repo) and updates the regex accordingly.
Closes #535.
> olsrd: remove url and update regex

- Livecheckables/nwchem.rb
```
$ brew livecheck nwchem
nwchem (guessed) : 7.0.0 ==> 22_2018
```
<details>
```
Trying with url https://github.com/nwchemgit/nwchem/releases/download/v7.0.0-release/nwchem-7.0.0-release.revision-2c9a1c7c-src.2020-02-26.tar.bz2
Possible git repo detected at https://github.com/nwchemgit/nwchem.git
6.8.1-release => #<Version:0x00007fc0c8262830 @version="6.8.1-release", @tokens=[#<Version::NumericToken 6>, #<Version::NumericToken 8>, #<Version::NumericToken 1>, #<Version::StringToken "release">]>
6.8.1-scorep => #<Version:0x00007fc0c8261e58 @version="6.8.1-scorep", @tokens=[#<Version::NumericToken 6>, #<Version::NumericToken 8>, #<Version::NumericToken 1>, #<Version::StringToken "scorep">]>
master-oct22_2018 => #<Version:0x00007fc0c8261868 @version="22_2018", …
```
> nwchem: add livecheckable

- Livecheckables/oclgrind.rb
```
$ brew livecheck oclgrind
oclgrind (guessed) : 19.10 ==> 32
```
<details>
```
Trying with url https://github.com/jrprice/Oclgrind/archive/v19.10.tar.gz
Possible git repo detected at https://github.com/jrprice/Oclgrind.git
llvm_32 => #<Version:0x00007fc94323fa78 @version="32", @tokens=[#<Version::NumericToken 32>]>
v14.12 => #<Version:0x00007fc94323f848 @version="14.12", @tokens=[#<Version::NumericToken 14>, #<Version::NumericToken 12>]>
v14.5 => #<Version:0x00007fc94323f438 @version="14.5", @tokens=[#<Version::NumericToken 14>, #<Version::NumericToken 5>]>
v15.2 => #<Version:0x00007fc94323f078 @version="15.2", @tokens=[#<Version::NumericToken 15>, #<Version::NumericToken 2>]>
v15.5 => #<Version:0x00007fc94323e9e8 @version="15.5", …
```
> oclgrind: add livecheckable

- Livecheckables/net-snmp.rb
```
$ brew livecheck net-snmp
net-snmp (guessed) : 5.8 ==> 5.8.1
```
<details>
```
Trying with url https://downloads.sourceforge.net/project/net-snmp/net-snmp/5.8/net-snmp-5.8.tar.gz
Possible SourceForge project [net-snmp] detectedat https://downloads.sourceforge.net/project/net-snmp/net-snmp/5.8/net-snmp-5.8.tar.gz
Using page_match("https://sourceforge.net/projects/net-snmp/rss", "(?i-mx:\/net-snmp\/([a-zA-Z0-9.]+(?:\.[a-zA-Z0-9.]+)*))")
5.8.1, files, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, 5.8.1, files, 5.8.1, files, 5.8.1, 5.8.1, …
```
> net-snmp: add livecheckable

- Livecheckables/frotz.rb
- Livecheckables/menhir.rb
- Livecheckables/ortp.rb
- Livecheckables/sound-touch.rb
- livecheck/heuristic.rb
Finds URLs that match the pattern of GitLab-hosted downloads and checks the tags page for which tags correspond to released versions. (The releases page itself isn't checked because its content isn't delivered on the initial page load.) As it's only run for formulae that don't specify a `head` URL, the affected formulae are:
```
dav1d (guessed) : 0.6.0 ==> 0.6.0
libxc (guessed) : 4.3.4 ==> 5.0.0
mat2 (guessed) : 0.10.1 ==> 0.11.0
minipro (guessed) : 0.4 ==> 0.4
proteinortho (guessed) : 6.0.14 ==> 6.0.15
radamsa (guessed) : 0.6 ==> 0.6
```
Also removed the livecheckable for `frotz`, which was redundant.
> heuristic: add GitLab releases check

- Livecheckables/node@12.rb
#528 adds a livecheckable for the `node@12` formula, which is currently skipped due to being versioned. This is an alternative implementation that uses the https://nodejs.org/dist/ index, so the check is in line with where the formula gets archives.
Closes #528.
> node@12: add livecheckable

- Livecheckables/ocproxy.rb
```
$ brew livecheck ocproxy
ocproxy (guessed) : 1.60 ==> 1.20121120160713
```
<details>
```
Trying with url https://github.com/cernekee/ocproxy.git
Possible git repo detected at https://github.com/cernekee/ocproxy.git
1.20121120160713 => #<Version:0x00007fc054142c80 @version="1.20121120160713", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 20121120160713>]>
v1.50 => #<Version:0x00007fc054142898 @version="1.50", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 50>]>
v1.60 => #<Version:0x00007fc054142230 @version="1.60", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 60>]>
ocproxy (guessed) : 1.60 ==> 1.20121120160713
```
</details>
```
$ brew livecheck ocproxy
ocproxy : 1.60 ==> 1.60
```
> ocproxy: add livecheckable

- Livecheckables/onioncat.rb
The existing `onioncat` livecheckable checks a page that contains prerelease versions instead of stable. #534 resolves this by checking the Git repo tags instead and restricting matching to stable versions using the regex.
This PR resolves the issue by simply checking the `stable` page instead of `current`, which allows us to continue checking the same upstream location as the formula's stable URL. I've also updated the regex to bring it in line with current standards.
Closes #534.
> onioncat: update url and regex

- Livecheckables/e2fsprogs.rb
```
$ brew livecheck e2fsprogs
Error: e2fsprogs: Failed to open TCP connection to e2fsprogs.sourceforge.net:443 (Connection refused - connect(2) for "e2fsprogs.sourceforge.net" port 443)
```
```
$ brew livecheck e2fsprogs
e2fsprogs : 1.45.5 ==> 1.45.6
```
---
relates to https://github.com/Homebrew/homebrew-core/pull/53428
> e2fsprogs: fix url

- Livecheckables/marathon-swift.rb
skipCheck due to deprecation and open compilation issue
> marathon-swift: skipCheck due to deprecation and open compilation issue

- Livecheckables/swagger-codegen@2.rb
```
swagger-codegen@2 : versioned
```
```
$ brew livecheck swagger-codegen@2
swagger-codegen@2 : 2.4.12 ==> 2.4.13
```
--- 
relates to https://github.com/Homebrew/homebrew-core/pull/54114
> swagger-codegen@2: add livecheckable

- Livecheckables/z.rb
```
z (guessed) : 1.9 ==> 1.11
```
```
$ brew livecheck z
z : 1.9 ==> 1.9
```
---
relates to https://github.com/rupa/z/issues/205
> z: add livecheckable

- Livecheckables/tmux.rb
```
tmux (guessed) : 3.1a ==> 3.1b
```
```
$ brew livecheck tmux
tmux : 3.1a ==> 3.1a
```
> tmux: add livecheckable

- Livecheckables/autoconf.rb
The existing livecheckable for `autoconf` was the only formula/livecheckable using the Git protocol. This updates the URL to use the https URL for the Git repo and also updates the regex to only work with tags relating to [stable] autoconf releases.
> autoconf: update url and regex

- Livecheckables/supertux.rb
```
supertux (guessed) : 0.5.1 ==> 2-grumbel
```
```
$ brew livecheck supertux
supertux : 0.6.1.1 ==> 0.6.1.1
```
---
relates to https://github.com/Homebrew/homebrew-core/pull/54115
> supertux: add livecheckable

- Livecheckables/opensaml.rb
```
$ brew livecheck opensaml
opensaml : 3.0.1 ==> 3.1.0
```
---
relates to https://github.com/Homebrew/homebrew-core/pull/53422
> opensaml: add livecheckable

- Livecheckables/shibboleth-sp.rb
```
$ brew livecheck shibboleth-sp
shibboleth-sp : 3.0.4 ==> 3.1.0
```
---
relates to https://github.com/Homebrew/homebrew-core/pull/53422
> shibboleth-sp: add livecheckable

- Livecheckables/embulk.rb
Fixes #549
```
$ brew livecheck embulk
embulk : 0.9.23 ==> 0.10.1
```
```
$ brew livecheck embulk
embulk : 0.9.23 ==> 0.9.23
```
> embulk: livecheck against 0.9.x release line

- Livecheckables/scc.rb
```
$ brew livecheck scc
scc (guessed) : 2.12.0 ==> 928286b8064e2cf6dd35
```
```
$ brew livecheck scc
scc : 2.12.0 ==> 2.12.0
```
> scc: add livecheckable

- Livecheckables/s2geometry.rb
```
$ brew livecheck s2geometry
s2geometry (guessed) : 0.9.0 ==> 0.9.0-2019.03.04.00
```
0.9.0-2019.03.04.00 is the prerelease before 0.9.0
```
$ brew livecheck s2geometry
s2geometry : 0.9.0 ==> 0.9.0
```
> s2geometry: add livecheckable

- Livecheckables/mupen64plus.rb
```
$ brew livecheck mupen64plus
mupen64plus (guessed) : 2.5 ==> 2.5.9
```
<details>
```
Trying with url https://github.com/mupen64plus/mupen64plus-core/releases/download/2.5/mupen64plus-bundle-src-2.5.tar.gz
Possible git repo detected at https://github.com/mupen64plus/mupen64plus-core.git
1.99.1 => #<Version:0x00007fe755838be8 @version="1.99.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 99>, #<Version::NumericToken 1>]>
1.99.2 => #<Version:0x00007fe755838788 @version="1.99.2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 99>, #<Version::NumericToken 2>]>
1.99.3 => #<Version:0x00007fe755838580 @version="1.99.3", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 99>, #<Version::NumericToken 3>]>
1.99.4 => …
```
> mupen64plus: add livecheckable

- Livecheckables/z.rb
#561 was merged without being reviewed, so this PR updates the livecheckable with the changes that would have been requested during review. As with other recent PRs, this one is better off using the GitHub "latest" URL as well as the general regex for getting the version number from the tag URL in the HTML.
> z: update url and regex

- Livecheckables/tmux.rb
#562 was merged without being reviewed, so this PR updates the livecheckable with the changes that would have been requested during review. As with other recent PRs, this one is better off using the GitHub "latest" URL as well as the general regex for getting the version number from the tag URL in the HTML (with the addition of `[a-z]?`, since `tmux` has releases like `3.1a`).
> tmux: update url and regex

- Livecheckables/swagger-codegen@2.rb
#563 was merged without being reviewed, so this PR updates the livecheckable with the changes that would have been requested during review. In this case, the regex diverged from the standard regex in that it was missing parentheses around the version part of the regex, which creates a capture group (and is used in the heuristic these days).
> swagger-codegen@2: update regex

- Livecheckables/supertux.rb
#564 was merged without being reviewed, so this PR updates the livecheckable with the changes that would have been requested during review. As with other recent PRs, this one is better off using the GitHub "latest" URL as well as the general regex for getting the version number from the tag URL in the HTML.
> supertux: update url and regex

- cmd/livecheck.rb
Livecheck has apparently long-assumed that `WATCHLIST_PATH` (`~/.brew_livecheck_watchlist`) will definitely exist, which isn't guaranteed to be true.
The following related error has been appearing in the `brew livecheck` step of our GitHub Actions checks: `Error: No such file or directory @ rb_sysopen - /Users/runner/.brew_livecheck_watchlist`. This modification will resolve this error but we may need to do more to fix the `brew livecheck` step, if it doesn't go back to running checks for added/modified livecheckables.
> Fix assumption of WATCHLIST_PATH existence

- Livecheckables/gl2ps.rb
In testing whether the URL in the existing livecheckable supported https, I found that the server redirects to https://geuz.org/gl2ps/, so this updates the livecheckable to the more canonical URL without the www subdomain. This also updates the URL to use the http://geuz.org/gl2ps/src/ index page (which is in line with where the formula downloads the stable archive) and updates the regex accordingly.
> gl2ps: update url and regex

- Livecheckables/eigen.rb
Since GitLab support was added in #507, the existing `eigen` livecheckable is no longer necessary, as the heuristic is fully capable of finding the latest version.
> eigen: remove livecheckable

- Livecheckables/gnu-prolog.rb
The `gnu-prolog` formula uses the http://www.gprolog.org/ website, so this update the existing livecheckable's URL to bring it in line. This also modifies the regex, so it will find the `tar.gz` file link on the page even if the "Current stable version is" text changes in the future.
> gnu-prolog: update url and regex

- Livecheckables/icoutils.rb
This updates the existing livecheckable to use the index page where the stable archive used in the formula is hosted (which supports https). This also updates the regex to only match URLs in `href` attributes.
> icoutils: update url and regex

- Livecheckables/nuttcp.rb
This updates the URL for the existing `nuttcp` livecheckable to use an https URL (as found in the formula's stable URL) and updates the regex to bring it in line with more recent standards.
> nuttcp: update url and regex

- Livecheckables/faad2.rb
This removes the URL in the existing livecheckable for `faad2` (allowing the heuristic to take over and use the SourceForge strategy) and updates the regex to only match within `url` attributes in the SourceForge RSS feed.
> faad2: remove url and update regex

- Livecheckables/cppunit.rb
This updates the regex for the existing `cppunit` livecheckable to not use a full URL when matching the cppunit archive files, making it a little more resilient to potential changes in the future. This also replaces the old `[0-9\.]+` style regex with the standard regex we use these days.
> cppunit: update regex

- Livecheckables/cvsync.rb
This updates the regex for the existing `cvsync` livecheckable to not use a full URL when matching the cvsync archive file, making it a little more resilient to potential changes in the future. This also replaces the old `[0-9\.]+` style regex with the standard regex we use these days.
> cvsync: update regex

- Livecheckables/dterm.rb
This updates the regex for the existing `dterm` livecheckable to not use a full URL when matching the dterm archive file, making it a little more resilient to potential changes in the future. This also replaces the old `[0-9\.]+` style regex with the standard regex we use these days.
> dterm: update regex

- Livecheckables/geos.rb
This updates the existing livecheckable for `geos` to use the index page where the stable archive used in the formula is hosted. This also updates the regex to avoid matching against the full URL for archive files,  use the standard regex, loosen the extension matching (looking for `.t` instead of `.tar.bz2` specifically), and properly escape periods.
> geos: update url and regex

- Livecheckables/libxml++.rb
The version-filtering feature (#536) is shelved for the moment, so we'll have to restrict matching for major/minor versions using the regex.
The regex used here is the one that was already being used for the formula in the GNOME strategy, with the simple modification of restricting the first digit of the version to `2`. The `libxml++` formula name doesn't give any indication but it should only use versions with a major version of 2. The version 3 series is handled by the `libxml++3` formula, as is common with GNOME formulae.
Closes #537.
> libxml++: add livecheckable

- Livecheckables/mafft.rb
As discussed in #558, the existing livecheckable for `mafft` is also picking up releases that are listed as "Experimental" on the upstream [Source](https://mafft.cbrc.jp/alignment/software/source.html) page. This updates the regex to painstakingly avoid matching the experimental releases.
I tried to write the regex as loosely as possible (such that it will accommodate some minor changes) but any notable changes to how the page lists experimental versions can potentially break this. Unfortunately, it doesn't seem like there's a better way of dealing with this issue at the moment.
Closes #558.
> mafft: update regex

- Livecheckables/sonarqube-lts.rb
As discussed in #560, the `sonarqube` [index page for archives](https://binaries.sonarsource.com/Distribution/sonarqube/) doesn't distinguish between current and LTS releases. Instead, we have to check the [Sonarqube downloads page](https://www.sonarqube.org/downloads/) and use a complicated regex to only match the LTS release archive.
I've tried to make the regex only as specific as it needs to be to match, in hopes that it doesn't break easily in the future. However, any notable changes to how the upstream downloads page formats this information will break this check. Unfortunately, there doesn't seem to be an easy way to deal with this. If anyone finds a better way of handling this, feel free to create a PR to update this livecheckable.
Closes #560.
> sonarqube-lts: add livecheckable

- Livecheckables/mpw.rb
In my review of #591, I was busy explaining that we didn't need the `-cli1`/`-cli-1` group to repeat and I forgot to explain that we didn't need to group this part at all as a result.
The livecheckable is functionally identical before/after this change and I've just modified the regex to remove the parentheses here for the sake of simplification.
> mpw: update regex

- Livecheckables/clang-format.rb
The existing `clang-format` livecheckable is finding and returning versions that use a date, like YYYY-MM-DD. However, the `clang-format` formula has moved to using `llvm` archive files from GitHub, so the formula's version is like 10.0.0.
This updates the livecheckable to check the "latest" release page on GitHub and extract the version from the release's tag.
> clang-format: update url and regex

- Livecheckables/unbound.rb
The URL in the existing `unbound` livecheckable redirects to https://nlnetlabs.nl/downloads/unbound/, so this updates the URL to avoid the redirection. I've also updated the regex to bring it in line with more recent standards.
> unbound: update url and regex

- Livecheckables/transmission-cli.rb
Output before:
```
-bash-5.0.17- /Users/miccal (32) [> brew livecheck transmission-cli
Error: transmission-cli: Unable to get versions
```
Output after:
```
-bash-5.0.17- /Users/miccal (32) [> brew livecheck transmission-cli
transmission-cli : 2.94 ==> 2.94
```
The `url` at `https://github.com/transmission/transmission-releases/` simply lists several different releases and formats. Using `https://github.com/transmission/transmission-releases.git` did not seem to work.
There are some old ones with `Transmission` and newer ones with `transmission`, so to be safe I added the case-insensitive `i` flag.
> transmission-cli: add livecheckable

- Livecheckables/ex-vi.rb
This formula currently works fine using the SourceForge strategy. However, once the SourceForge strategy update in #539 is merged into master, the check for this formula will no longer correctly identify the latest version due to the default regex for the strategy not being sufficient in this particular case.
This adds a livecheckable with a regex that will properly identify versions in the SourceForge project's RSS feed. This ensures the check for the formula will work properly both before and after the forthcoming SourceForge strategy update.
> ex-vi: add livecheckable

- cmd/livecheck.rb
- livecheck/extend/formula.rb
We're using a `#skip?` method to access the `@skip` instance variable boolean in the livecheck PR (Homebrew/brew#7179), so I wanted to similarly update the `Formula#livecheckable` method to `#livecheckable?`. This makes it clear that the variable is a boolean instead of, say, a hash/object containing the livecheckable information (e.g., url, regex, etc.). [Currently that information is in `Formula#livecheck_args` and will be accessible at `Formula#livecheck` in the future.]
I will be proposing `#livecheckable?` as an addition to the livecheck DSL's implementation, so this PR helps to keep Homebrew/homebrew-livecheck's `Formula` class extension closer to the Homebrew/brew implementation. Eventually the livecheck command will migrate to Homebrew/brew, so this is one small step towards …
> Rename Formula#livecheckable to livecheckable?

- Livecheckables/slashem.rb
This check for this formula doesn't return a proper version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
> slashem: add livecheckable

- Livecheckables/perltidy.rb
> perltidy: add livecheckable

- Livecheckables/ssldump.rb
> ssldump: add livecheckable

- Livecheckables/apcupsd.rb
> apcupsd: add livecheckable

- Livecheckables/portmidi.rb
> portmidi: add livecheckable

- Livecheckables/biosig.rb
> biosig: add livecheckable

- Livecheckables/gplcver.rb
> gplcver: add livecheckable

- Livecheckables/cppcms.rb
> cppcms: add livecheckable

- Livecheckables/cmu-pocketsphinx.rb
> cmu-pocketsphinx: add livecheckable

- Livecheckables/cmu-sphinxbase.rb
> cmu-sphinxbase: add livecheckable

- Livecheckables/etl.rb
> etl: add livecheckable

- Livecheckables/fetchmail.rb
The check for this formula doesn't return a correct version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
> fetchmail: add livecheckable

- Livecheckables/gqview.rb
> gqview: add livecheckable

- Livecheckables/libmaa.rb
> libmaa: add livecheckable

- Livecheckables/kettle.rb
The check for this formula doesn't return a proper version using the SourceForge strategy (giving `files` as the newest version. This will be fixed after the SourceForge strategy update in #539 is merged into master but this could use a livecheckable with a more specific regex to restrict matching a bit and potentially avoid issues in the future.
> kettle: add livecheckable

- Livecheckables/libquvi.rb
> libquvi: add livecheckable

- Livecheckables/libspnav.rb
> libspnav: add livecheckable

- Livecheckables/libwmf.rb
> libwmf: add livecheckable

- Livecheckables/makepp.rb
The check for this formula doesn't return a correct version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
> makepp: add livecheckable

- Livecheckables/mhash.rb
> mhash: add livecheckable

- Livecheckables/mkvalidator.rb
> mkvalidator: add livecheckable

- Livecheckables/mingw-w64.rb
> mingw-w64: add livecheckable

- Livecheckables/mpgtx.rb
> mpgtx: add livecheckable

- Livecheckables/nrpe.rb
> nrpe: add livecheckable

- Livecheckables/pidgin.rb
> pidgin: add livecheckable

- Livecheckables/primer3.rb
> primer3: add livecheckable

- Livecheckables/proctools.rb
> proctools: add livecheckable

- Livecheckables/putmail-queue.rb
> putmail-queue: add livecheckable

- Livecheckables/qrupdate.rb
The check for this formula doesn't work at all currently but it won't be fixed by the SourceForge strategy update in #539 is merged into master.
> qrupdate: add livecheckable

- Livecheckables/quvi.rb
> quvi: add livecheckable

- Livecheckables/sc68.rb
> sc68: add livecheckable

- Livecheckables/sstp-client.rb
> sstp-client: add livecheckable

- Livecheckables/synfig.rb
The check for this formula is currently broken and it won't be fully fixed when the SourceForge strategy update in #539 is merged into master.
> synfig: add livecheckable

- Livecheckables/tivodecode.rb
> tivodecode: add livecheckable

- Livecheckables/vncsnapshot.rb
> vncsnapshot: add livecheckable

- Livecheckables/wv2.rb
> wv2: add livecheckable

- Livecheckables/zip.rb
> zip: add livecheckable

- Livecheckables/x3270.rb
> x3270: add livecheckable

- Livecheckables/ant-contrib.rb
> ant-contrib: add livecheckable

- Livecheckables/chadwick.rb
> chadwick: add livecheckable

- Livecheckables/avfs.rb
The current livecheckable for `avfs` correctly identifies the latest version but it simply checks the `avfs` SourceForge project page, which may not include the information we need. This updates the livecheckable to use the SourceForge RSS feed (the heuristic doesn't seem to select the SourceForge strategy for any existing URLs, so we have to force it for now) and caters the regex to this context.
> avfs: update url and regex

- Livecheckables/djview4.rb
> djview4: add livecheckable

- Livecheckables/espeak.rb
> espeak: add livecheckable

- Livecheckables/ftgl.rb
> ftgl: add livecheckable

- Livecheckables/gnu-cobol.rb
The check for this formula doesn't return a correct version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
> gnu-cobol: add livecheckable

- Livecheckables/libid3tag.rb
> libid3tag: add livecheckable

- Livecheckables/libpano.rb
> libpano: add livecheckable

- Livecheckables/mad.rb
> mad: add livecheckable

- Livecheckables/madplay.rb
> madplay: add livecheckable

- Livecheckables/pdftohtml.rb
> pdftohtml: add livecheckable

- Livecheckables/tta.rb
> tta: add livecheckable

- Livecheckables/asymptote.rb
> asymptote: add livecheckable

- Livecheckables/automysqlbackup.rb
> automysqlbackup: add livecheckable

- Livecheckables/cdrtools.rb
> cdrtools: add livecheckable

- Livecheckables/cntlm.rb
> cntlm: add livecheckable

- Livecheckables/darkice.rb
> darkice: add livecheckable

- Livecheckables/dex2jar.rb
> dex2jar: add livecheckable

- Livecheckables/findent.rb
> findent: add livecheckable

- Livecheckables/mcpp.rb
> mcpp: add livecheckable

- Livecheckables/mp3wrap.rb
> mp3wrap: add livecheckable

- Livecheckables/timidity.rb
> timidity: add livecheckable

- Livecheckables/zssh.rb
The check for this formula doesn't return a fully correct version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
> zssh: add livecheckable

- Livecheckables/camellia.rb
> camellia: add livecheckable

- Livecheckables/expect.rb
> expect: add livecheckable

- Livecheckables/jags.rb
> jags: add livecheckable

- Livecheckables/naturaldocs.rb
> naturaldocs: add livecheckable

- Livecheckables/pngcheck.rb
> pngcheck: add livecheckable

- Livecheckables/unzip.rb
> unzip: add livecheckable

- Livecheckables/xmlsh.rb
> xmlsh: add livecheckable

- Livecheckables/streamripper.rb
> streamripper: add livecheckable

- Livecheckables/w3m.rb
The check for this formula currently defaults to the Git strategy but the tags contain more information than we need (`0.5.3+git20200502`) and the formula uses archive files from SourceForge anyway. This PR adds a livecheckable to check the SourceForge RSS feed and adds an appropriate regex, such that we get clean versions like `0.5.3` instead.
> w3m: add livecheckable

- Livecheckables/zabbix.rb
The existing livecheckable for `zabbix` was broken (`Error: zabbix: 404 Not Found`) but unfortunately the upstream Zabbix situation is a bit dodgy. The Zabbix SourceForge project doesn't have the latest version (4.4.8) and instead only goes up to 4.4.7.
The formula uses an archive file from the Zabbix CDN, so this PR updates the livecheckable to use an index page on the Zabbix CDN but the trouble is that the archive files are organized into folders based on the major/minor version (e.g., 4.4). As a result, this livecheckable will eventually quietly fail to give the newest version when there's a new major/minor version folder and will need to be updated to work again.
It's not a great solution but it seems to be the only available option at the moment due to the upstream situation.
> zabbix: add url and update regex

- Livecheckables/dfu-programmer.rb
The default check for the `dfu-programmer` formula uses the Git strategy but the latest version (0.7.2) isn't tagged there. The formula download the stable archive from the SourceForge project, so this adds a livecheckable to check the SourceForge RSS feed using an appropriate regex.
> dfu-programmer: add livecheckable

- Livecheckables/irrlicht.rb
The default check for the `irrlicht` formula doesn't work (`Error: irrlicht: undefined method `[]' for nil:NilClass`). The formula downloads the stable archive from the SourceForge project, so this adds a livecheckable to check the SourceForge RSS feed using an appropriate regex.
> irrlicht: add livecheckable

- Livecheckables/nload.rb
The default check for the `nload` formula doesn't work properly (`Error: nload : Unable to get versions`), so this adds a livecheckable with a url and regex to identify the newest version at the same place the stable archive comes from.
> nload: add livecheckable

- Livecheckables/autopsy.rb
The [Autopsy website's downloads page](https://www.autopsy.com/download/) lists 4.15.0 as newest and the GitHub repo reports the same. The formula currently uses an old version from SourceForge but Autopsy moved to GitHub, so checking SourceForge isn't useful here.
This adds a livecheckable to check the "latest" release on GitHub and get the version from the tag URL.
> autopsy: add livecheckable

- Livecheckables/sdcc.rb
> sdcc: add livecheckable

- Livecheckables/saxon.rb
In the future, this will benefit from an "alterations" feature, since the returned version uses hyphens instead of periods (e.g., `9-9-1-7` instead of `9.9.1.7`). However, these are identical from a version comparison standpoint, so it's fine for now.
> saxon: add livecheckable

- Livecheckables/little-cms.rb
The `little-cms` formula is only for the version 1 series of releases, so this adds a livecheckable to restrict matching to versions with a major version of 1.
> little-cms: add livecheckable

- Livecheckables/libvo-aacenc.rb
> libvo-aacenc: add livecheckable

- Livecheckables/gauche.rb
> gauche: add livecheckable

- Livecheckables/ngspice.rb
The default check for `ngspice` uses the Git repo but the repo contains tags like `32.2`, whereas the versions on SourceForge that we use are only like `32`. This adds a livecheckable to check for versions in the SourceForge RSS feed instead, so we get a proper version.
> ngspice: add livecheckable

- Livecheckables/zint.rb
The default check for `zint` uses the Git strategy but the repo doesn't contain version tags, so it's not usable. This adds a livecheckable to check the SourceForge RSS feed (since that's where the formula's stable archive is hosted) and adds an appropriate regex.
> zint: add livecheckable
