Homebrew/homebrew-livecheck

Livecheckables/premake.rb
=> premake: add livecheckable

Livecheckables/jnettop.rb
The check for this formula doesn't return a fully correct version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
=> jnettop: add livecheckable

Livecheckables/squirrel.rb
=> squirrel: add livecheckable

Livecheckables/aview.rb
=> aview: add livecheckable

Livecheckables/locateme.rb
=> locateme: add livecheckable

Livecheckables/libngspice.rb
The default check for `libngspice` uses the Git repo but the repo contains tags like `32.2`, whereas the versions on SourceForge that we use are only like `32`. This adds a livecheckable to check for versions in the SourceForge RSS feed instead, so we get a proper version. [Just to be clear, this livecheckable is basically a duplicate of `ngspice`.]
=> libngspice: add livecheckable

Livecheckables/itpp.rb
The default check for `itpp` uses the Git repo but it doesn't have a tag for the latest version. This adds a livecheckable to search for versions in the SourceForge project RSS feed instead, as the stable archive is hosted on SourceForge.
=> itpp: add livecheckable

Livecheckables/anttweakbar.rb
The caveat here is that the version in the formula is like "1.16" but the version we get from the file name is like "116". Unfortunately we can't address this issue until the forthcoming "alterations" feature is added.
=> anttweakbar: add livecheckable

Livecheckables/docbook2x.rb
=> docbook2x: add livecheckable

Livecheckables/aacgain.rb
We're looking for a few livecheckables to migrate for testing purposes in Homebrew/homebrew-core#54565 and `aacgain` was the next livecheckable in line after `a52dec` alphabetically.
This PR simply updates the regex in the existing livecheckable for `aacgain`, to bring it up to current standards before it can be migrated as a test case.
=> aacgain: update regex

Livecheckables/ant.rb
The existing `ant` livecheckable needed to be updated to split the `:url` and `:regex` onto separate lines (for later migration purposes) but I also reworked it in the process. The existing livecheckable looked for release note files, whereas it's more appropriate to get the versions from the same binaries that the formula uses. This updates the URL and regex accordingly.
=> ant: update url and regex

Livecheckables/ant@1.9.rb
LIke #696, the existing `ant@1.9` livecheckable needed to be updated to split the `:url` and `:regex` onto separate lines (for later migration purposes) but I also reworked it in the process. The existing livecheckable looked for release note files, whereas it's perhaps more appropriate to get the versions from the same binaries that the formula uses. This updates the URL and regex accordingly.
=> ant@1.9: update url and regex

Livecheckables/armadillo.rb
The existing livecheckable for `armadillo` needed to be updated to ease future migration (i.e., moving the comment onto a separate line) and I simply reworked it in the process. This removes the PR, allowing the heuristic to use the SourceForge strategy, and adds an appropriate regex to match versions in the project's SourceForge RSS feed.
=> armadillo: remove url and update regex

Livecheckables/pijul.rb
The `pijul` formula was removed in Homebrew/homebrew-core#52730 and we'll need to remove the livecheckable here, so that it doesn't pose a problem for the migration from livecheckables to `livecheck` blocks in formulae.
=> pijul: remove livecheckable

Livecheckables/szip.rb
Livecheck isn't able to find the newest release for `szip` by default (`Error: szip: Unable to get versions`). The upstream archive files are currently placed into folders based on the version (e.g., `2.1.1`) and this PR adds a livecheckable to get versions from the same place as the stable archive in the formula.
If this breaks in the future, it's also possible to get the latest version from the `szip` website like:
```ruby
class Szip
livecheck :url   => "https://support.hdfgroup.org/doc_resource/SZIP/",
:regex => /href=.+?szip-v?(\d+(?:\.\d+)+)\.t/
end
```
=> szip: add livecheckable

Livecheckables/docker-swarm.rb
The existing livecheckable for `docker-swarm` doesn't work currently, since the repository name changed from `swarm` to `classicswarm` and the regex is explicit about the account and repo names when trying to find tag names in `href` attributes. Livecheck just checks the repo's Git tags by default, so this removes the URL to allow for that and updates the regex accordingly.
For anyone reading, this is a good example of why we try to only be as specific as necessary with a regex to match what we want. Unnecessary specificity, like the leading account/repo part of the URL here, can cause livecheckables to break when changes like this happen. Sometimes breaking is appropriate and other times it's unnecessary and just leads to more maintenance for us. There's a balance to be found between …
=> docker-swarm: remove url and update regex

Livecheckables/rsyslog.rb
The `rsyslog` homepage must have changed a bit, as the assumptions included in this livecheckable's regex don't seem to be true anymore. The check is currently broken (`Error: rsyslog: Unable to get versions`), so this PR updates the regex to work with the current situation. It's looser than I would like but works for now.
One alternative is matching versions on the [stable download page](https://www.rsyslog.com/downloads/download-v8-stable/) but the URL path contains the major version (i.e., `.../download-v8-stable/`), so we would need to manually update the URL in the future if there's a major release. This isn't appealing, so we'll just have to live with this regex for now.
=> rsyslog: update url and regex

Livecheckables/oniguruma.rb
The latest version of `oniguruma` in the formula (as of writing) is `6.9.5-rev1` but the standard regex we're using in the livecheckable only matches versions like `1.2.3` or `v1.2.3` (with nothing behind it). The intention is to avoid matching prerelease versions, like `v6.9.5_rc1` in this repository.
This is the first `rev#` release but there was a `mark1` release for 6.9.4 before, which seems like a similar revision-after-release kind of deal. This appears to be becoming a regular occurrence, so this PR updates the regex to also match versions with trailing `mark#` or `rev#` extensions.
=> oniguruma: update regex

Livecheckables/libgit2.rb
The existing livecheckable for `libgit2` restricts matching to a version with a major of 0 and minor of 27-29, so livecheck reported the latest version to be 0.28.5 instead of 1.0.0.
The formula is currently using the 1.0.0 release, so this reworks the livecheckable to check the "latest" release on GitHub (updating the regex accordingly).
=> libgit2: update url and regex

Livecheckables/libtorrent-rasterbar.rb
The existing livecheckable for `libtorrent-rasterbar` checks the `libtorrent` homepage for the latest version but currently this page is outdated with respect to the latest version (displaying 1.2.5 instead of 1.2.6).
The formula uses a release from GitHub, so this removes the URL (allowing the heuristic to default to checking the Git tags) and updates the regex accordingly (using a modification of the "standard" regex for matching versions in Git tags). The only caveat is that the matched versions in tags are like `1_2_6` instead of `1.2.6`. These two are the same from the standpoint of version comparison but I'll come back and address this cosmetic issue in the future if/when I implement an "alterations" feature.
=> libtorrent-rasterbar: remove url and update regex

Livecheckables/rebar3.rb
The existing livecheckable for `rebar3` checks rebar3.org for the latest version but currently this page is outdated with respect to the latest version (displaying 3.13.1 instead of 3.13.2).
The formula uses a release from GitHub, so this removes the URL (allowing the heuristic to default to checking the Git tags) and updates the regex accordingly (using the "standard" regex for matching versions in Git tags).
=> rebar3: remove url and update regex

Livecheckables/softhsm.rb
The existing livecheckable for `softhsm` checks the [OpenDNSSEC download page](https://www.opendnssec.org/download/) but unfortunately the latest version available there is 2.5.0 (instead of 2.6.1). The formula uses an archive at https://dist.opendnssec.org/source/, so this PR updates the URL to this index page and improves the regex in the process.
=> softhsm: update url and regex

Livecheckables/sdedit.rb
The check for this formula doesn't return the correct latest version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
=> sdedit: add livecheckable

Livecheckables/simutrans.rb
The default check for `simutrans` uses the Git strategy but the repo doesn't contain tags for the latest versions. This adds a livecheckable to check the SourceForge RSS feed (since that's where the formula's stable archive is hosted) and adds an appropriate regex.
=> simutrans: add livecheckable

Livecheckables/minidjvu.rb
The check for this formula doesn't return the correct latest version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
=> minidjvu: add livecheckable

Livecheckables/rtf2latex2e.rb
The check for this formula doesn't return the correct latest version using the SourceForge strategy and this will continue to be the case after the SourceForge strategy update in #539 is merged into master.
As an aside, the returned version from this check contains hyphens in the version instead of dots (e.g., `2-2-3` vs. `2.2.3`). This is fine from the perspective of version comparison but we can tidy this up in the future with an "alterations" feature.
=> rtf2latex2e: add livecheckable

Livecheckables/ttf2pt1.rb
=> ttf2pt1: add livecheckable

Livecheckables/harbour.rb
=> harbour: add livecheckable

Livecheckables/chordii.rb
The latest version in the `chordii` formula was `4.5.3b` but the existing livecheckable didn't match beta(?) versions, so the main change here is to update the regex to allow for this (while also improving it in general).
The restriction to the 4.5 series of releases may not be absolutely necessary at this point (the file names for the 5.0 releases aren't matched by this regex), so I've removed it for now. We can revisit it in the future if it becomes a problem.
=> chordii: remove url and update regex

Livecheckables/ganglia.rb
=> ganglia: add livecheckable

Livecheckables/log4c.rb
=> log4c: add livecheckable

Livecheckables/udis86.rb
=> udis86: add livecheckable

Livecheckables/gpcslots2.rb
=> gpcslots2: add livecheckable

Livecheckables/mpg123.rb
The existing livecheckable for `mpg123` was checking the first-party download page but this was timing out in testing. This PR updates the URL to one that will use the SourceForge strategy (as the stable archive is downloaded from SourceForge) and updates the regex accordingly.
=> mpg123: update url and regex

Livecheckables/qmmp.rb
The existing livecheckable for `qmmp` was checking the first-party downloads page but this was timing out locally. This PR updates the URL to one that will use the SourceForge strategy (as the stable archive is downloaded from SourceForge) and updates the regex accordingly.
=> qmmp: update url and regex

Livecheckables/tcl-tk.rb
The existing livecheckable for `tcl-tk` was checking the first-party download page but this was timing out locally. This PR updates the URL to one that will use the SourceForge strategy (as the stable archives are downloaded from SourceForge) and updates the regex accordingly.
=> tcl-tk: update url and regex

Livecheckables/jnethack.rb
The default check for `jnethack` was checking SourceForge, which doesn't contain the latest version. The [homepage](https://jnethack.osdn.jp/) points to releases on OSDN, which contains some newer versions that SourceForge doesn't have (e.g., `3.6.6-0.1`). This adds a livecheckable to check OSDN releases, so we properly find the latest versions.
=> jnethack: add livecheckable

cmd/livecheck.rb, livecheck/extend/formula.rb
This PR aims to add fallback code to livecheck, in order to handle the livecheck Formula DSL (Homebrew/brew#7027) for `skip`.
With this addition, any `skip` added to `some-formula.rb` in homebrew/core as part of the livecheck DSL will be handled properly. See Homebrew/brew#7179 for more details.
Example:
some-formula.rb in homebrew/core:
```ruby
...
livecheck do
skip "Not maintained"
end
...
```
Output of `brew livecheck some-formula`:
```bash
some-formula: skipped - Not maintained
```
=> Add support for livecheck DSL

Livecheckables/aacgain.rb, Livecheckables/imap-uw.rb
The `aacgain` and `imap-uw` livecheckables were migrated to `livecheck` blocks in their respective formulae (Homebrew/homebrew-core#54595, Homebrew/homebrew-core#54597), as initial tests before a wide-scale migration of livecheckables. Now that `brew livecheck` supports the new livecheck DSL (#555), we can safely remove these livecheckables.
=> aacgain, imap-uw: remove livecheckable

Livecheckables/bigloo.rb
The `bigloo` homepage has evidently changed since the existing livecheckable was created, so the check is currently failing (`Error: bigloo: Unable to get versions`).
This updates the livecheckable's regex to identify the latest version but this too could break in the future if the page's HTML significantly changes. Unfortunately, I don't think there's a better way to handle this check, since this is the only place where the latest version is posted and their archives are fetched over FTP.
=> bigloo: update livecheckable

Livecheckables/jrtplib.rb
The existing livecheckable for `jrtplib ` is broken, now that the [JRTPLIB page](https://research.edm.uhasselt.be/jori/page/CS/Jrtplib.html) has been replaced with a notice that the library is no longer being developed. The longer explanation can be found on [the project's GitHub repo](https://github.com/j0r1/JRTPLIB), which makes it clear that development has ended.
We can still technically check the GitHub repo releases but it seems like a waste of effort since the developer has publicly stated that development has ended. Skipping the check for the foreseeable future seems fine to me, as we would have to update the livecheckable if the repo is handed off to someone else anyway.
=> jrtplib: skip

Livecheckables/libplctag.rb
The existing livecheckable for `libplctag` used an overly-specific regex that failed to match once the `libplctag` repo moved from `kyle-github/libplctag` to `libplctag/libplctag` (`Error: libplctag: Unable to get versions`).
This removes the URL, allowing the heuristic to simply check the Git repo tags, and updates the regex to the standard one we use for matching Git tags like `1.2.3` or `v1.2.3`.
=> libplctag: remove url and update regex

Livecheckables/minidjvu.rb
Despite my efforts, the existing livecheckable for `minidjvu` broke when the SourceForge strategy update PR was merged (```Error: minidjvu: undefined method `[]' for nil:NilClass```).
The reason why this livecheckable checked the `minidjvu` homepage instead of the RSS feed was because there's a `0.33` version on SourceForge that livecheck will treat as newest until/unless a 1.0+ or 0.34+ version is released.
This updates the URL to one that will use the SourceForge strategy and updates the regex to specifically avoid matching the old `0.33` version (which isn't newer than the current `0.8` version).
=> minidjvu: update url and regex

Livecheckables/theora.rb
The existing livecheckable for `theora` checked the Git tags (by default) but unfortunately https://git.xiph.org has been unresponsive for quite some time, so all of the checks for related formulae are failing:
```
fatal: unable to access 'https://git.xiph.org/theora.git/': Failed to connect to git.xiph.org port 443: Operation timed out
Error: theora: Unable to get versions
```
This updates the existing livecheckable to check the [`theora` downloads page](https://www.theora.org/downloads/) instead and modifies the regex accordingly.
=> theora: add url and update regex

Livecheckables/getdns.rb
The existing livecheckable for `getdns` uses the [first-party releases page](https://getdnsapi.net/releases/), which is where the stable archive in the formula comes from. However, this page can sometimes take a long time to respond and often leads to an `execution expired` error in livecheck.
This updates the URL to check the "latest" release on GitHub instead (updating the regex accordingly), which is more reliable and will avoid this error.
=> getdns: update url and regex

Livecheckables/nsd.rb
The existing livecheckable for `nsd` uses the [first-party project page](https://www.nlnetlabs.nl/projects/nsd/), which is close to where the stable archive in the formula comes from. However, this site can sometimes take a long time to respond and often leads to an `execution expired` error in livecheck.
This updates the URL to check the Git tags instead (updating the regex accordingly), which is more reliable and will avoid this error.
=> nsd: update url and regex

Livecheckables/zabbix.rb
The URL in the `zabbix` livecheckable has to be updated when a new major/minor version is released, so this simply updates the check to use 5.0 (instead of 4.4).
=> zabbix: update url

Livecheckables/miniupnpc.rb
The existing livecheckable for `miniupnpc` is finding versions properly but it's listing a development version as newest (`2.1.20191224`). Stable versions of this software only use a major and minor (e.g., `2.1`), so this updates the regex to only match these versions.
=> miniupnpc: update regex

Livecheckables/ddclient.rb
`ddclient` has moved from [SourceForge](https://sourceforge.net/p/ddclient/) to [GitHub](https://github.com/ddclient/ddclient), so the existing livecheckable needed to be updated to be able to find the latest version. Currently, the formula is using version 3.9.1 but the last version on SourceForge is 3.9.0.
This updates the livecheckable to check the GitHub repo and modifies the regex accordingly.
=> ddclient: remove url and update regex

Livecheckables/exim.rb
The upstream download page at https://ftp.exim.org/pub/exim/exim4/ places maintenance releases (e.g., `4.93.0.4`) in a separate `fixes` subdirectory. As a result, we can't create a check that finds both the main releases (e.g., `4.93`) and the aforementioned maintenance releases.
The Git repo tags seem to be the best solution currently and I decided to use the GitHub mirror here, since the upstream repo (git://git.exim.org/exim.git) doesn't work over https.
=> exim: update url and regex

Livecheckables/scamper.rb
The existing livecheckable for `scamper` was finding versions properly but missing versions with a letter at the end (e.g., `20191102b` instead of `20191102`).
This updates the regex to allow for these maintenance versions while also making some changes to potentially reduce the chance of breaking in the future and to be a little more clear about the version format.
=> scamper: update regex

Livecheckables/inspircd.rb
The existing livecheckable for `inspircd` checks the [GitHub releases page](https://github.com/inspircd/inspircd/releases) but the regex only matches the version marked as "latest". Unfortunately, the "latest" version is set to `2.0.29`, even though the [upstream website](https://www.inspircd.org) describes v2 as deprecated and that users should upgrade to v3.
This updates the livecheckable to simply check the Git tags (updating the regex accordingly), to avoid this issue.
=> inspircd: update url and regex

Livecheckables/ansible-lint.rb, Livecheckables/aws-elasticbeanstalk.rb, Livecheckables/bzt.rb, Livecheckables/ccm.rb, Livecheckables/charm-tools.rb, Livecheckables/codemod.rb, Livecheckables/csvkit.rb, Livecheckables/cython.rb, Livecheckables/diffoscope.rb, Livecheckables/doitlive.rb, Livecheckables/dxpy.rb, Livecheckables/eralchemy.rb, Livecheckables/jenkins-job-builder.rb, Livecheckables/keepassc.rb, Livecheckables/keepkey-agent.rb, Livecheckables/ocrmypdf.rb, Livecheckables/pgcli.rb, Livecheckables/pipenv.rb, Livecheckables/tox.rb, Livecheckables/vsts-cli.rb
Updating PyPI livecheck `url`s to `https://pypi.org/simple/formula`.
=> Update PyPI livecheck urls

Livecheckables/spotifyd.rb
before:
```
➜  homebrew/homebrew-core master ✓  brew livecheck spotifyd
spotifyd (guessed) : 0.2.24 ==> 452658987034c42dfa0b
```
after:
```
➜  homebrew/homebrew-core master ✓  brew livecheck spotifyd
spotifyd : 0.2.24 ==> 0.2.24
```
=> spotifyd: add livecheckable

cmd/livecheck.rb, livecheck/utils.rb
Fix new RuboCop style offenses in `cmd/livecheck.rb` and `livecheck/utils.rb` due to changes in Homebrew/brew.
=> Fix style offenses in livecheck.rb and utils.rb

Livecheckables/zboy.rb
The default check for `zboy` also matches versions like `2011-01-06`, whereas stable versions are like `0.71`. This adds a livecheckable with a regex to only match proper release versions.
=> zboy: add livecheckable

Livecheckables/msdl.rb
The default check for `msdl` (using the SourceForge strategy) doesn't match the trailing `-r#` part of the version string. This adds a livecheckable with a regex that optionally matches this additional part of the version.
=> msdl: add livecheckable

Livecheckables/x264.rb
The `x264` upstream Git repository doesn't tag releases and the only way I found to get version numbers like `r1234` is to check the [binaries index page](https://artifacts.videolan.org/x264/) for a given platform (even though we don't use the binaries in the formula). Sometimes one platform will have a binary for a newer version and a different platform won't yet have that version available (and it may never before the next release) but I had to pick some platform for the purposes of this check, so I went with macOS.
Another issue is that the binaries aren't always for stable versions (e.g., the binary might have been built on a commit that's not yet in the `stable` branch of the upstream repo), so livecheck may report a newer version that's not yet appropriate to use in the formula. …
=> x264: add livecheckable

Livecheckables/akka.rb
The existing livecheckable for `akka` checked the Git repo's tags and used a regex that only matched versions with a single digit major version (e.g., `2.6.4`). This was because there were some older tags like `v10.0.0` that will appear newer until the version numbers go past `v10.1.0`.
This updates the livecheckable to check the "latest" GitHub release, as this will continue to work if the `akka` versions ever reach `v10.0.0`.
=> akka: update livecheckable

Livecheckables/closure-compiler.rb
The existing livecheckable for `closure-compiler` had to use a link shortener to get around an issue where the upstream URL wouldn't allow livecheck to check the URL.
This avoids the issue by updating the livecheckable to check the upstream index page where the formula's stable archive is located.
=> closure-compiler: update livecheckable

Livecheckables/wapm.rb
The existing livecheckable for `wapm` was restricting matching to versions with three parts (e.g., `1.2.3`), to avoid a problematic `3.2` version in the Git tags.
This updates the livecheckable to check the "latest" release on GitHub instead, so it will continue to work if there's ever a version with only two parts.
=> wapm: add url and update regex

Livecheckables/marathon-swift.rb
This simply cleans up the explanatory comment and `skip` text, as part of ongoing efforts to tidy up the existing livecheckables.
=> marathon-swift: update comment and skip text

Livecheckables/dpkg.rb
The `url` has been changed to `http://ftp.debian.org/...` to prevent the urls cop from raising style errors on migration to homebrew-core. The new `url` does not break livecheck.
=> dpkg: update url

Livecheckables/fakeroot.rb
The `url` has been changed to `http://ftp.debian.org/...` to prevent the urls cop from raising style errors on migration to homebrew-core. The new `url` does not break livecheck.
=> fakeroot: update url

Livecheckables/checkbashisms.rb
The `url` has been changed to `http://ftp.debian.org/...` to prevent the urls cop from raising style errors on migration to homebrew-core. The new `url` does not break livecheck.
=> checkbashisms: update url

Livecheckables/castxml.rb
The `url` has been changed to `http://ftp.debian.org/...` to prevent the urls cop from raising style errors on migration to homebrew-core. The new `url` does not break livecheck.
=> castxml: update url

Livecheckables/freetds.rb
The `url` in `freetds.rb`, earlier a `fossies.org` url, caused a style issue when migrated to a `livecheck` block in `homebrew-core`.
The `url` in the Livecheckable has been updated to http://www.freetds.org/files/stable/, which works with `livecheck` and does not cause a style issue when migrated to `homebrew-core`.
=> freetds: update url

Livecheckables/watchman.rb
The `watchman` Git repo contains a couple tags like `2020.05.18.00`, whereas the newest stable version is `4.9.0`. This adds a livecheckable with a regex to restrict matching to versions with two to three parts (e.g., `1.2`, `1.2.3`), which omits the versions that use a date.
If a stable version appears in the future with four parts (e.g., `1.2.3.4`), we'll have to restrict the length of the first part to fewer than four digits instead.
=> watchman: add livecheckable

Livecheckables/closure-compiler.rb
Updates the `url` for `closure-compiler` to one compliant with the `urls` cop in Homebrew/brew. The update is due to style issues raised by the `urls` cop during migration to homebrew-core.
=> closure-compiler: update url

cmd/livecheck.rb
before:
```
Error: forgit: Calling Formula#installed? is deprecated! Use Formula#latest_version_installed? (or Formula#any_version_installed? ) instead.
Please report this issue to the homebrew/livecheck tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-livecheck/cmd/livecheck.rb:104
Error: forgit: undefined method `url' for nil:NilClass
```
after:
```
forgit (guessed) : HEAD-ade7ca9 ==> HEAD-ade7ca9
```
after further fixes:
```
forgit (guessed) : ade7ca9 ==> 9faef0c
```
=> livecheck: fix HEAD only formulae checking

Livecheckables/detekt.rb
Formula `detekt` has been moved to a GitHub organisation named `detekt` and the author maintains a personal fork at the current url. Livecheck was not fetching the latest version, and was actually fetching a version older than the one currently available in homebrew-core.
The output before this change:
```
detekt: 1.9.1 ==> 1.9.0
```
The output after:
```
detekt: 1.9.1 ==> 1.9.1
```
=> detekt: update url

livecheck/extend/formula.rb
This PR removes support for the older hash format for Livecheckables, retaining support for the block format alone. All Livecheckables have already been converted to the block format in #764.
=> livecheck: remove support for hash format

livecheck/commands/cat.rb
I'm not sure if there's value in keeping this around and removing it means there's one less thing to migrate to Homebrew/brew in the future.
Are there any objections to this?
=> Remove commands/cat.rb

Livecheckables/spice-protocol.rb
The earlier regex was too specific w.r.t the extension and was not matching the latest version (as they had updated their compression format). Updated the regex to be more loose w.r.t the extension, while also updating the version number matching to our preferred regex.
=> spice-protocol: update regex

Livecheckables/plzip.rb
Fixes a `redirection-forbidden` error for `plzip`.
=> plzip: update url and regex

Livecheckables/coq.rb
The upstream `coq` developers have created a release (8.11.2) that doesn't adhere to how they've been doing releases in the past and the `coq` formula has been updated to use it. That is to say, the release isn't the "latest" on GitHub, there are no release artifacts (just the source), and the version wasn't announced on the [first-party website](https://coq.inria.fr/).
It would have been helpful to resolve this ambiguity before the homebrew-core PR was merged (e.g., discussing it with the upstream developers to understand if the version should be used and to request that they adhere to good release standards). As it stands, the formula's using the 8.11.2 "release" from GitHub, so this updates the existing livecheckable to check the Git tags for versions.
=> coq: update url and regex

Livecheckables/libdca.rb
The existing livecheckable for `libdca` was reporting `0.0.6` as the latest release instead of `0.0.7` (as found in the formula). The livecheckable checks the [libdca download page](https://www.videolan.org/developers/libdca.html) but this page hasn't been updated for the 0.0.7 release.
This updates the livecheckable to check the [libdca release folders index page](https://download.videolan.org/pub/videolan/libdca/), which aligns with the stable archive in the formula.
=> libdca: update url and regex

Livecheckables/mu.rb
The existing livecheckable for `mu` checks the "latest" release on the [GitHub releases page](https://github.com/djcb/mu/releases). Unfortunately, the tag for the latest release at the moment has a typo in it (`1,4.7` instead of `1.4.7`), which breaks matching and leads to a development version (1.3.10) being reported as newest.
This updates the livecheckable to check the Git repo tags instead and restricts matching to versions with an even-numbered minor version number (as an odd-numbered minor version indicates a development version).
=> mu: update url and regex

Livecheckables/simgrid.rb
The existing livecheckable for `simgrid` checks the [first-party website](https://simgrid.org/) but it apparently went down recently for a brief period of time. The formula is using an archive from the Git repository, so this PR updates the livecheckable to check the Git repo tags instead. This should be more reliable but it's also good to align the check with the source of the stable archive in the formula, when appropriate.
=> simgrid: update url and regex

livecheck/extend/formula.rb
The PR (Homebrew/brew#7668) adding the ability to reference Formula URLs in the `livecheck` DSL has been merged. It changes the `Livecheck` class constructor to accept the `Formula` object as a parameter, to be able to access the URLs for `head`, `stable`, `devel` and `homepage`.
The `Livecheck` object instantiation in livecheck/extend/formula.rb has been updated in this PR to reflect that change.
=> Fix Livecheck object instantiation

Livecheckables/lmdb.rb
The default check for `lmdb` checks the Git tags but they include tags for more than just `lmdb`. This adds a livecheckable that uses the `head` URL (Git repo) and restricts matching to the tags like `LMDB_1.2.3`.
This uses the recently-added support for referencing specific formula URLs in `url` (namely, `:head`, `:stable`, `:devel`, and `:homepage`). This allows us to avoid explicitly duplicating these URLs in the livecheckable (and keeping them in sync).
=> lmdb: add livecheckable

Livecheckables/libewf.rb
[The main repository for `libewf`](https://github.com/libyal/libewf) only contains experimental builds at this point and the stable archive is from the [libyal/libewf-legacy repo](https://github.com/libyal/libewf-legacy). This adds a livecheckable to restrict checking to the stable URL, which will check the libewf-legacy Git repo tags.
=> libewf: add livecheckable

Livecheckables/jsoncpp.rb
The upstream Git repo for `jsoncpp` releases versions that appear to be stable releases but are marked as pre-release on the GitHub releases page (e.g., `1.9.2`). This adds a livecheckable to check the "latest" release page on GitHub to get the latest version.
=> jsoncpp: add livecheckable

Livecheckables/anttweakbar.rb
As the [website](http://anttweakbar.sourceforge.net/doc/tools:anttweakbar:download) states, this Formula is no longer being maintained, and so we must skip `livecheck` for this Formula. Also, `livecheck` was earlier reporting an incorrect "new version" (1.16 ==> 116) - probably because the URL to the source had 116 in it.
=> anttweakbar: skip livecheck

Livecheckables/libp11.rb
By default, livecheck picks up the `11` part of the `libp11` name and adds it to the matched version like `11-0.4.10` (whereas the version should be `0.4.10`). This adds a livecheckable with a regex to fix this issue.
=> libp11: add livecheckable

Livecheckables/root.rb
The default check for `root` is looking for versions in the tags of the upstream repo and the latest version is being reported as `6-23-01` instead of `6.20.04`.
This adds a livecheckable that checks the [first-party download index page](https://root.cern.ch/download/) (to align with the stable archive source) and restricts matching to production versions (those with an even-numbered minor version).
=> root: add livecheckable

Livecheckables/gtkmm.rb
The default check for `gtkmm` reports `3.24.2` as the newest version but this formula is only for versions with a major version of `2` (i.e., versions with a major version of `3` belong in `gtkmm3`). This adds a livecheckable to restrict matching to versions with a major version of `2` (while still respecting the stable/development GNOME version scheme).
=> gtkmm: add livecheckable

Livecheckables/exiv2.rb
The default check for `exiv2` was checking the Git tags and reporting an unstable version as newest (`0.27.3-RC2`). This adds a livecheckable to check the [first-party "builds" index page](https://www.exiv2.org/builds/) (where the stable archive comes from) and restricts matching to stable versions.
=> exiv2: add livecheckable

Livecheckables/micronaut.rb
The default check for `micronaut` was returning a newer version (`v2.0.0.M3`) than the one marked as "latest" on GitHub (`1.3.5`). This adds a livecheckable to check the "latest" release on GitHub to get the latest version.
=> micronaut: add livecheckable

Livecheckables/urdfdom.rb
The default check for `urdfdom` was picking up an unrelated Git tag, leading to the latest version being wrongly reported as `1.7.1` instead of `1.0.4`. This adds a livecheckable to restrict matching to Git tags like `1.2.3` (excluding ones like `robot_model-1.7.1`).
=> urdfdom: add livecheckable

Livecheckables/mosquitto.rb
The earlier `url` was that of the Download page which hadn't been updated to show the latest version. Updated the `url` to that of the source index page and also modified the `regex` to current standards.
=> mosquitto: update url and regex

Livecheckables/bash-completion.rb
We skip livecheck for `bash-completion` as `1.x` versions are not being released alongside `2.x` versions. The last `1.x` release was eight years ago, so it doesn't make sense to check for newer versions.
(macOS currently ships with Bash 3.2, while `bash-completion` versions `2.x` require Bash 4+. So, `bash-completion@2` is available as a versioned Formula in homebrew-core while `bash-completion` is the `1.x` version supported by default on Bash 3.2 on macOS.)
=> bash-completion: add livecheckable

Livecheckables/libmagic.rb
Adding Livecheckable for `libmagic` using the `url` https://astron.com/pub/file/.
=> libmagic: add livecheckable

Livecheckables/telnet.rb
Adding a Livecheckable for `telnet`. Important note: homebrew-core lists the version for `telnet` as that of Apple's `remote_cmd` version (currently 63). This Livecheckable considers the version of `remote_cmd` to be `telnet`'s version as well.
=> telnet: add livecheckable

Livecheckables/asuka.rb
The regex is for homepage source.
before:
```
Error: asuka: Unable to get versions
```
after:
```
asuka : 0.8.0 ==> 0.8.0
```
=> asuka: add livecheckable

Livecheckables/mysql-client.rb
Fixes `livecheck` error by adding a Livecheckable for `mysql-client`; using GitHub repo to match versions tagged as `mysql-x.x.x` and not the MySQL Cluster versions. Concerns: There's a version `mysql-client@5.7` formula as well. Do let me know if changes are required.
=> mysql-client: add livecheckable

Livecheckables/scala.rb
Adding a Livecheckable for `scala` using the `url` https://www.scala-lang.org/files/archive.
=> scala: add livecheckable

Livecheckables/metis.rb
Using the `homepage` as `url` and matching text. There doesn't seem to be a proper index page of *all* versions, although a tree of some versions does exist.
=> metis: add livecheckable

Livecheckables/gradle.rb
Add a Livecheckable for `gradle`, using their GitHub repository `url` to check for newer versions.
=> gradle: add livecheckable

Livecheckables/libspatialite.rb
They happen to have just one version (the latest) with an `a` affixed, so instead of using `\d` I used `[0-9a-z]` for the patch part alone, but it could possibly be improved.
=> libspatialite: add livecheckable

Livecheckables/sdl.rb
They do have a release page at https://www.libsdl.org/release/ but I used http://hg.libsdl.org/SDL/tags instead, to check the tags. An issue (?) I noticed when browsing through the first URL was that their 2+ versions are released as `SDL2-x.x.x` whereas their latest 1.x version, `1.2.5` (homebrew-core has this) is released as just `SDL-1.2.5`. Do let me know if I've got to change something here.
=> sdl: add livecheckable

Livecheckables/mecab.rb
The source code for `mecab` was originally part of `code.google.com` and was later migrated to GitHub when Google Code was shut down. I checked [their archives](https://code.google.com/archive/p/mecab/) and it says that the repository had been moved to https://taku910.github.io/mecab (`:homepage`).
The GitHub repository doesn't have version tags and based on my rudimentary Japanese skills I think there's no list of versions anywhere on the page except the ["Updates" section](http://taku910.github.io/mecab/#news) and the ["Download" section](http://taku910.github.io/mecab/#download).
There is a [Google Drive link](https://drive.google.com/drive/folders/0B4y35FiV1wh7fjQ5SkJETEJEYzlqcUY4WUlpZmR4dDlJMWI5ZUlXN2xZN2s2b0pqT3hMbTQ) which contains all the source archives (and also the bindings for …
=> mecab: add livecheckable

Livecheckables/flac.rb
The default check for `flac` looks at the Git repo tags but https://gitlab.xiph.org/xiph/flac.git doesn't have a tag for the latest release (1.3.3). This adds a livecheckable to check the first-party release index (which is currently redirecting to [the release index at the OSU Open Source Lab](https://ftp.osuosl.org/pub/xiph/releases/flac/)).
=> flac: add livecheckable

Livecheckables/readline.rb
Output before:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck readline
readline (guessed) : 8.0.4 ==> 8.0
```
Output after:
```
-bash-5.0.17- /Users/miccal (28) [> brew livecheck readline
readline : 8.0.4 ==> 8.0.4
```
Inspired by https://github.com/Homebrew/homebrew-livecheck/pull/808 and discussion [here](https://github.com/Homebrew/homebrew-livecheck/issues/806), as `readline` is like `bash` with its versions and patches.
=> readline: add livecheckable

Livecheckables/cataclysm.rb
Typically,`cataclysm` releases follow a `0.1`, `0.7.1`, or `0.E` format, where the minor version rolls over to letters after 9. [It could be hexadecimal but we haven't hit a minor version of 18 yet to find out.] Recent `cataclysm` releases also introduce a `0.E-2` format, where the `-2` is a point release.
Instead of updating the existing regex to match this additional version format when checking Git tags, I've simply reworked this livecheckable to check the "latest" release on GitHub. The way I've written the regex is loose enough that it will match any additional version formats that we encounter in the future.
Checking the "latest" GitHub release also avoids the version comparison issue that we discussed in #510 (i.e., number versions like `0.9` appearing as newer than letter versions …
=> cataclysm: add url and update regex

Livecheckables/popt.rb
The rpm5.org url is down (has been for a while probably, as apparent from the use of a Wayback Machine url in homebrew-core). They do have rpm.org now, I think, and this GitHub repository for `popt`. I tried not using a regex and it works too, so let me know if I should add one.
=> popt: add livecheckable

livecheck/livecheck_strategy.rb
This updates the variable name for the list of GNOME formulae to skip (based on the package name) to `GNOME_DEVEL_SKIP_LIST`, which better explains the purpose of the constant but also avoids language that may reduce inclusivity or cause harm in some way.
=> Update name used for list of items to skip

livecheck/livecheck_strategy.rb
Thinking about this some more after #812, `GNOME_DEVEL_ALLOWLIST` makes more sense than `GNOME_DEVEL_SKIP_LIST`, since the list is for formulae (based on GNOME package name) that don't use the GNOME version scheme (and shouldn't use the more restrictive regex). Naming this in a way that describes the purpose well is kind of tricky, so this will work for now.
Pardon the PRs/commits one after another, due to my indecisiveness about variable naming.
=> Update language used for GNOME_DEVEL list (again)

Livecheckables/agda.rb
The default check for `agda` looks for versions in the Git repo tags but there are a number of tags that we don't want to match. It's possible to add a livecheckable with a regex to only match tags like `1_2_3`, `v1.2.3`, or `v1.2.3.4` (not `1.2.3.20200607`).
However, the formula's stable archive comes from Hackage, so it's better to simply create a livecheckable that checks the stable URL instead.
Closes #814.
=> agda: add livecheckable

Livecheckables/a52dec.rb, livecheck/heuristic.rb
The existing livecheckable for `a52dec` defaults to the SourceForge strategy but isn't a compatible URL, so it's one of the few existing livecheckables that's broken.
This adds `liba52.sourceforge.net/` to the `SOURCEFORGE_SPECIAL_CASES` array (so the SourceForge strategy isn't used for that subdomain) and adds a livecheckable to check the first-party downloads page.
=> a52dec: add special case, update url and regex

livecheck/heuristic.rb
I moved most frozen arrays out of functions in previous PRs, so they're not allocated when the function is called. The only remaining array like this was `version_rejections` in the `version_heuristic` function.
This moves the array outside of the function and renames it to `UNSTABLE_VERSION_KEYWORDS` to reflect that it's a constant and better explain its purpose.
=> heuristic: move version_rejections out of function

Livecheckables/qca.rb
The default check for `qca` checks the Git tags in the HEAD repo but there are also tags like `kde4.5` which result in livecheck reporting `4.5` as the latest version instead of `2.3.0`. This adds a livecheckable which restricts matching to versions like `v2.3.0`.
The check is also currently warning about a redirection (`warning: redirecting to https://invent.kde.org/libraries/qca.git/`) and this is being addressed in Homebrew/homebrew-core#56258.
=> qca: add livecheckable

Livecheckables/algol68g.rb
The `homepage` doesn't list the version available in homebrew-core (2.8.5) and only some Linux distributions seemed to be using this version. The source for this version is however, downloadable from the `homepage`.
I've created this Livecheckable using a URL from OpenBSD instead, as it's the only thing I found which we could check reliably.
=> algol68g: add livecheckable

Livecheckables/jed.rb
Livecheck checks the Git repo tags for `jed` and successfully finds the latest version (0.99-19), granted it's the only version in the tags. The Git repo is accessed over the insecure `git://` protocol, which we want to avoid if an `https` source is available.
The first-party [releases index page](https://www.jedsoft.org/releases/jed/) can be accessed over HTTPS and it's also where the stable archive comes from, so this adds a livecheckable to check this instead.
=> jed: add livecheckable

Livecheckables/mikutter.rb
Livecheck checks the Git repo tags for `mikutter` and successfully finds the latest version (4.0.5). However, the Git repo is accessed over the insecure `git://` protocol, which we want to avoid if an `https` source is available.
The [first-party download page](https://mikutter.hachune.net/download) can be accessed over HTTPS and it's also where the stable archive comes from, so this adds a livecheckable to check this instead.
=> mikutter: add livecheckable

Livecheckables/git-annex.rb
By default, livecheck checks the Git repo for `git-annex` and successfully finds the latest version (8.20200522). However, the Git repo is accessed over the insecure `git://` protocol, which we want to avoid if an `https` source is available.
The formula uses a stable archive from Hackage, so this simply adds a livecheckable with `url :stable` to check that URL instead (as this is over HTTPS).
=> git-annex: add livecheckable

Livecheckables/monkeysphere.rb
Livecheck checks the Git repo tags for `monkeysphere` and successfully finds the latest version (0.44). However, the Git repo is accessed over the insecure `git://` protocol, which we want to avoid if an `https` source is available.
The formula uses an archive from Debian, presumably because it uses HTTPS and the first-party website has an expired certificate. This adds a livecheckable that checks the [Debian index page](https://deb.debian.org/debian/pool/main/m/monkeysphere/) where the stable archive is found, as it's accessible over HTTPS.
=> monkeysphere: add livecheckable

Livecheckables/texi2html.rb
See https://www.nongnu.org/texi2html/ - developers do not intend to make any further releases.
=> texi2html: skip

Livecheckables/kde-extra-cmake-modules.rb
The default check for `kde-extra-cmake-modules` checks the Git repo tags but it picks up at least one tag that we don't want (`plasma2tp`). The check works fine for now but this adds a livecheckable to restrict matching to versions like `v1.2.3`, so we don't inadvertently match an undesirable tag in the future.
=> kde-extra-cmake-modules: add livecheckable

Livecheckables/git-crypt.rb
Adding Livecheckable for `git-crypt`. Using their GitHub repository rather than the homepage.
=> git-crypt: add livecheckable

Livecheckables/libcaca.rb
Adding Livecheckable for `libcaca` using `:head`. The homebrew-core Formula is for a `beta` version so I've allowed for matching of those tags in the `regex`.
=> libcaca: add livecheckable

Livecheckables/sdl.rb
As seen in #833, apparently parts of SDL (that is, not SDL2) can go above a major version of 1. I thought it was appropriate to restrict matching for the `sdl` livecheckable to a major version of 1 but apparently that may not be the right way to go.
Restricting to a major version of 1 isn't necessary to match the correct versions and was simply a "better safe than sorry" approach, so it's fine to just use `\d+` like we normally do.
=> sdl: update regex

Livecheckables/media-info.rb
Adding Livecheckable for `media-info`. The Formula's `url` gives an idea of where all the sources may be listed, and it redirects to the `old.` subdomain. The main website (`homepage`) has a project page and a section dedicated to macOS versions of the project, but it lists only one version (the current latest `20.03`).
The link to the page is https://mediaarea.net/en/MediaInfo/Download/Mac_OS and the download URL given is https://mediaarea.net/download/binary/mediainfo/20.03/MediaInfo_CLI_20.03_Mac.dmg (the URL is very similar to the one in the Formula, except for the `dmg` being downloaded instead).
If the latter is preferred, I'll update the Livecheckable's URL.
=> media-info: add livecheckable

Livecheckables/avrdude.rb, livecheck/heuristic.rb
Adding livecheckable for `avrdude`, and adding it to the special cases for GNU urls.
=> avrdude: add livecheckable

Livecheckables/vert.x.rb
Livecheck was unable to find a version by default, so this adds a livecheckable that checks the first-party download page for the latest version.
=> vert.x: add livecheckable

Livecheckables/less.rb
Adding Livecheckable for `less`. The website also lists a BETA version along with the RECOMMENDED version, and unless we check for the presence of RECOMMENDED, I don't think we can match the latest non-BETA version. (The tarball URLs have no `-beta` or `-rc` for the BETA version and look exactly like a normal version's URLs).
=> less: add livecheckable

Livecheckables/mecab-ipadic.rb
The default check for `mecab-ipadic` wasn't able to find any versions, so this adds a livecheckable that checks the Debian index page where the stable archive in the formula is found. Unfortunately we can't check the first-party website for new versions because they use Google Drive download links and the filename isn't listed on the page for this particular software.
=> mecab-ipadic: add livecheckable

Livecheckables/oath-toolkit.rb, livecheck/heuristic.rb
Adding Livecheckable for `oath-toolkit`, and also adding it to `GNU_SPECIAL_CASES`.
With the addition of this, all Formulae with >10000 downloads in the last 365 days (except versioned ones) should _probably_ have working `livecheck`s.
=> oath-toolkit: add livecheckable

completions/bash/brew-livecheck, completions/zsh/_brew_livecheck
Adding `bash` and `zsh` completions for `brew livecheck`. Should add `fish` shortly too. The changes here almost resemble those in Homebrew/brew#7748 entirely but with inputs taken from similar PRs in Homebrew/homebrew-services.
To test the `zsh` completion you'll have to use this symlink:
```zsh
ln -s /usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/completions/zsh/_brew_livecheck /usr/local/share/zsh/site-functions/_brew_functions
```
As for `bash`, I just used `source` for the `completions/bash/brew-livecheck` file and tested it.
If the Tap is (re)installed, the symlinks will be created automatically (this will happen only after the PR is merged, obviously).
As for the Homebrew/brew PR, do I let it be or close it and create a new one when it's time to migrate the command? …
=> Add completion for livecheck

livecheck/livecheck_strategy.rb, livecheck/utils.rb
This is work done by Maxim in #601 but I wanted to avoid modifying the strategies in that PR (to keep it simple), so I removed the change and suggested that we could handle this in a separate PR.
There hasn't been a follow-up PR yet and I will be modifying this part of the Git strategy in another PR shortly, so I wanted to go ahead and incorporate these changes.
=> Inline git_tags_only_debian? into git strategy

Livecheckables/qhull.rb
Adding Livecheckable for `qhull`. I match only the `year.version` versions like `2020.1` (current latest) or `2009.1.1`. Here's their GitHub repo (https://github.com/qhull/qhull), if there are any changes to make, let me know!
=> qhull: add livecheckable

cmd/livecheck.rb, livecheck/heuristic.rb, livecheck/livecheck_strategy.rb, livecheck/utils.rb
The debug output includes a mess of information in the beginning that I have never found useful and it's a chore to constantly scroll past it.
More importantly, the debug output doesn't provide enough relevant information about what's happening in livecheck internally. This makes it more difficult than it should be for anyone who isn't intimately familiar with livecheck's behavior to understand what's actually happening in a given check.
Even for people who spend a lot of time working with livecheck, not having better debug information means that we have to waste time figuring out what livecheck is doing instead of it being immediately apparent from the debug output.
The main things that this PR does related to improving debug output are:
* Removes the unhelpful glut of information …
=> Improve debug and JSON output

cmd/livecheck.rb
The `--debug` and `--json` flags have different purposes (displaying debug output and outputting JSON, respectively) and shouldn't be executed together. This adds a `conflicts` line to the CLI information to enforce this.
=> Make --debug and --json flags mutually exclusive

Livecheckables/libelf.rb
Adding Livecheckable to skip livecheck for `libelf`. The last release was in 2009 and the homebrew-core Formula uses a WayBack Machine URL as the website has been down for a while.
There seems to be a related project called `elftools` which is being developed and `libelf` is a part of it. However, that doesn't have a Formula and I think skipping this seems to be the best way forward.
The skip message _probably_ needs work though. Or a comment.
=> libelf: add livecheckable to skip

Livecheckables/rpm2cpio.rb
Adding Livecheckable for `rpm2cpio`. In its current form the Livecheckable is probably less than ideal, however I was unable to find alternatives. Any better options?
=> rpm2cpio: add livecheckable

Livecheckables/sentencepiece.rb
relates to Homebrew/homebrew-core#56614
Update livecheck to exclude `1.0.0` tag
```
$ brew livecheck -v sentencepiece
sentencepiece (guessed) : 0.1.91 ==> 1.0.0
```
```
$ brew livecheck -v sentencepiece
sentencepiece : 0.1.91 ==> 0.1.92
```
=> sentencepiece: add livecheckable

Livecheckables/awscli@1.rb
```
$ brew livecheck -v awscli@1
awscli@1 : versioned
```
```
$ brew livecheck -v awscli@1
awscli@1 : 1.18.70 ==> 1.18.84
```
relates to Homebrew/homebrew-core#56618
=> awscli@1: add livecheckable

Livecheckables/mariadb-connector-c.rb
Adding Livecheckable for `mariadb-connector-c`.
=> mariadb-connector-c: add livecheckable

Livecheckables/cloog.rb
Adding Livecheckable for `cloog`. SSL error on using `https` so using `http` (for now).
=> cloog: add livecheckable

Livecheckables/latexml.rb
```
$ brew livecheck -v latexml
latexml (guessed) : 0.8.4 ==> 1.0.7
```
```
$ brew livecheck -v latexml
latexml : 0.8.4 ==> 0.8.4
```
=> latexml: add livecheckable

Livecheckables/mavsdk.rb
```
$ brew livecheck -v mavsdk
mavsdk (guessed) : 0.27.0 ==> 9
```
```
$ brew livecheck -v mavsdk
mavsdk : 0.27.0 ==> 0.28.0
```
relates to Homebrew/homebrew-core#56620
=> mavsdk: add livecheckable

Livecheckables/hfstospell.rb
0.5.2 is not the latest release, thus there is no release artifact that we need.
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "hfstospell"
Download failed: https://github.com/hfst/hfst-ospell/releases/download/v0.5.2/hfstospell-0.5.2.tar.gz
```
```
$ brew livecheck -v hfstospell
hfstospell : 0.5.1 ==> 0.5.1
```
=> hfstospell: add livecheckable

Livecheckables/clp.rb
```
$ brew livecheck -v clp
clp (guessed) : 1.17.6 ==> 2002-11-05
```
```
$ brew livecheck -v clp
clp : 1.17.6 ==> 1.17.6
```
=> clp: add livecheckable

Livecheckables/cern-ndiff.rb
```
$ brew livecheck -v cern-ndiff
cern-ndiff (guessed) : 5.05.01 ==> 060411-10AM
```
```
$ brew livecheck -v cern-ndiff
cern-ndiff : 5.05.01 ==> 5.05.01
```
=> cern-ndiff: add livecheckable

Livecheckables/javacc.rb
```
$ brew livecheck -v javacc
javacc (guessed) : 7.0.5 ==> 60_61_merge
```
```
$ brew livecheck -v javacc
javacc : 7.0.5 ==> 7.0.6
```
relates to Homebrew/homebrew-core#56648
=> javacc: add livecheckable

Livecheckables/jvm-mon.rb
```
$ brew livecheck -v jvm-mon
jvm-mon (guessed) : 0.3 ==> 1.0-ea1
```
```
$ brew livecheck -v jvm-mon
jvm-mon : 0.3 ==> 0.3
```
=> jvm-mon: add livecheckable

Livecheckables/tnftp.rb
Adding Livecheckable to skip livecheck for `tnftp`. Context: Apple removed `tnftp` from all macOS versions after High Sierra.
If this shouldn't be skipped or there are edits to be made, let me know.
=> tnftp: add livecheckable

Livecheckables/foremost.rb, livecheck/heuristic.rb
Using `:homepage` isn't feasible due to the `sourceforge.io` URL redirecting to the `sourceforge.net` URL. We could possibly open a PR in homebrew-core but the `.io` URL is `https` while the `.net` isn't, and I'm not sure that change would be preferred (despite the redirect in the browser too).
=> foremost: add livecheckable

Livecheckables/tnftpd.rb
This adds a very similar livecheckable to the recently-added `tnftp`, as these formulae are both found on the same index page. The only difference is the use of the `tnftpd` name in the regex.
=> tnftpd: add livecheckable

Livecheckables/perl.rb
Output before:
```
-bash-5.0.17- /Users/miccal (30) [> brew livecheck perl
perl : 5.30.3 ==> 5.30.3
```
Output after:
```
-bash-5.0.17- /Users/miccal (30) [> brew livecheck perl
perl : 5.30.3 ==> 5.32.0
```
I noticed that `livecheck` was not reporting the [latest version](https://github.com/Homebrew/homebrew-core/pull/56701), and I have tried to follow the strategy used in recent PR's.
Thank you (as always).
=> perl: update livecheckable

Livecheckables/pdflib-lite.rb
Adding a livecheckable to skip `pdflib-lite`.
See here: https://www.pdflib.com/products/pdflib-family/overview/?pdfliblite (at the bottom of the page there's a note about the situation)
=> pdflib-lite: add livecheckable to skip

Livecheckables/libsvg.rb
Adding Livecheckable for `libsvg`. There is a version marked as `LATEST` but I've not checked that as it could be unreliable (despite the fact that this particular library's version hasn't changed since 2005~).
=> libsvg: add livecheckable

Livecheckables/procmail.rb
Adding Livecheckable for `procmail`.
We use a WayBack Machine URL as the website `procmail.org` has been down since 2015, probably. The Formula has a comment stating that the Apple-provided patched version is used, and `brew info` lists the version as `stable 14 (bottled)`.
Unless we decide to `skip`, this is probably a good way to check for new versions. Comment could be reworded though.
=> procmail: add livecheckable

Livecheckables/gst-plugins-bad.rb
See #999, the `gst-` Livecheckables shouldn't match odd numbers in the minor version, as pointed out in #942 as well.
=> gst-plugins-bad: update regex

Livecheckables/gst-plugins-base.rb
See #999, the `gst-` Livecheckables shouldn't match odd numbers in the minor version.
=> gst-plugins-base: update regex

Livecheckables/gst-plugins-good.rb
See #999, the `gst-` Livecheckables shouldn't match odd numbers in the minor version.
=> gst-plugins-good: update regex

Livecheckables/gst-plugins-ugly.rb
See #999, the `gst-` Livecheckables shouldn't match odd numbers in the minor version.
=> gst-plugins-ugly: update regex

Livecheckables/gstreamer.rb
See #999, the gst- Livecheckables shouldn't match odd numbers in the minor version.
=> gstreamer: update regex

Livecheckables/gst-libav.rb
See #999, we shouldn't match odd-number minor versions for `gstreamer` Formulae.
=> gst-libav: update regex

Livecheckables/gst-editing-services.rb
Adding Livecheckable for `gst-editing-services`. Also see #999.
=> gst-editing-services: add livecheckable

Livecheckables/grace.rb
Adding Livecheckable for `grace`. The `Download` page inked to in the `homepage` is actually an FTP directory, so unless we have the strategy for that, we should check the Debian archives (which we use).
=> grace: add livecheckable

Livecheckables/libsvm.rb
Adding Livecheckable for `libsvm`. Their website has a download link but that does not have the version number in it, and I could only create a Livecheckable by matching text. They have a GitHub repo but the versioning there is done without the `.`s, i.e., `v324` instead of `v3.2.4`.
=> libsvm: add livecheckable

Livecheckables/vbindiff.rb
Adding Livecheckable for `vbindiff`. They have a GitHub repo without tags; Homebrew/homebrew-core uses the latest version available which is a beta. Development doesn't seemed to have happened since that release in 2017 (beta 5), before which the latest version seemed to have been released in 2008 (beta 4).
=> vbindiff: add livecheckable

Livecheckables/ecm.rb
Adding a livecheckable to skip `ecm`.
The creator's website (http://neillcorlett.com) shows a message stating that the website has been "down" since 2014 (they're taking a break, according to a post of theirs [elsewhere](https://www.reddit.com/r/retrogaming/comments/6zbgly/does_anyone_know_what_happened_to_neill_corlett/dn2dca8/?context=3)).
The skip message and the comment could be improved, as always.
=> ecm: add livecheckable to skip

Livecheckables/tcptrace.rb
Adding Livecheckable for `tcptrace`. The homebrew-core Formula definition for `tcptrace` has a comment stating that the website "is currently offline", but that doesn't seem to be the case.
=> tcptrace: add livecheckable

Livecheckables/bcrypt.rb, livecheck/heuristic.rb
Adding a livecheckable for `bcrypt`.
Edit: The script I wrote to automate the `commit`, `push` and PR creation gave this PR a wrong title, which has been fixed.
=> bcrypt: add livecheckable

Livecheckables/libsvg-cairo.rb
Adding Livecheckable for `libsvg-cairo`.
=> libsvg-cairo: add livecheckable

livecheck/livecheck_strategy.rb
This refactors the Hackage strategy to resemble similar strategies that use the `page_match` function. Refactoring the strategy in this manner is necessary to enable some future changes.
Specifically, we want to be able to return the generated URL and regex used in the strategy back to `latest_version()`, where we can print it in the debug output, and back to `print_latest_version`, where they can be included in JSON output. This will be enabled in a later PR but this is a necessary change leading up to that PR.
=> Refactor Hackage strategy to resemble others

Livecheckables/geckodriver.rb
The default check for `geckodriver` uses the Git strategy with the GitHub repo (derived from the homepage URL) but it has to go through the other URLs before it reaches this point. This adds a livecheckable to remove the guesswork and to also use the standard regex for Git tags.
=> geckodriver: add livecheckable

Livecheckables/gmp.rb
The default check for `gmp` ends up checking a mirror which supports the GNU strategy, whereas it would be preferable to be checking for a version in the same location as the stable archive. This adds a livecheckable that checks the index page where the stable archive is located.
=> gmp: add livecheckable

Livecheckables/lv.rb
Adding a livecheckable to skip `lv`. The comment and message may need to be modified.
=> lv: add livecheckable to skip

cmd/livecheck.rb
In a recent livecheck run, I once again encountered a formula where the GitHub repo was deleted entirely. We decided it was appropriate to deprecate the formula and this reminded me that livecheck doesn't currently skip deprecated formulae. This seems like a straightforward addition to the existing automatic skip for versioned formulae (unless a livecheckable is available).
=> Skip deprecated formulae

Livecheckables/elasticsearch@5.6.rb, Livecheckables/go@1.10.rb, Livecheckables/go@1.9.rb, Livecheckables/kibana@5.6.rb, Livecheckables/postgresql@9.4.rb, Livecheckables/premake.rb, Livecheckables/redis@3.2.rb
The following formulae are currently deprecated and have livecheckables:
* elasticsearch@5.6
* go@1.10
* go@1.9
* kibana@5.6
* postgresql@9.4
* premake
* redis@3.2
All of these have been deprecated for over a year, so I think it's safe to remove the livecheckables and allow these to be skipped.
=> Remove deprecated livecheckables

Livecheckables/git-interactive-rebase-tool.rb
The `interactive-rebase-tool` formula has been renamed to `git-interactive-rebase-tool`. This renames the livecheckable and also adds `url :stable` to make the desired URL explicit.
=> interactive-rebase-tool: update livecheckable name, add url

Livecheckables/marathon-swift.rb, Livecheckables/residualvm.rb
The `marathon-swift` and `residualvm` formulae were recently deleted, so this removes the related livecheckables.
=> Delete livecheckables for removed formulae

livecheck/utils.rb
We've had a longstanding issue with livecheck where we'll get a `Username for 'https://github.com':` type prompt when livecheck executes `git_tags` (i.e., `git ls-remote --tags ...`) on a repo that no longer exists. This is a problem, as it will halt a livecheck run until you press enter to get past the prompts (which often repeat due to multiple URLs being tried).
Prepending `GIT_TERMINAL_PROMPT=0` to the `git ls-remote --tags` call prevents this from happening and we instead get a `fatal: could not read Username for 'https://github.com': terminal prompts disabled` error, which is preferable.
=> git_tags: disable terminal prompt

Livecheckables/kim-api.rb
Adding Livecheckable for `kim-api`.
We have multiple resources to check for newer versions. The page for `kim-api` at https://openkim.org/kim-api/ has a link to a GitHub repository and also a releases page (which is what I use). It also lists the current latest version available from Homebrew (through Repology).
=> kim-api: add livecheckable

Livecheckables/libagg.rb
Adding Livecheckable to skip `libagg`.
The [Wikipedia entry](https://en.wikipedia.org/wiki/Anti-Grain_Geometry) for this Formula offers some information – active development stalled in 2006, and the creator passed away in 2013. The homepage is up, but other pages (such as the Downloads page) are down.
So I think skipping this is okay, though of course the comment and message could be modified.
=> libagg: add livecheckable to skip

Livecheckables/sloccount.rb
Adding Livecheckable for `sloccount`. The website states that they've moved development to SourceForge, but it's at the same version (2.26).
=> sloccount: add livecheckable

Livecheckables/crowdin.rb
Adding Livecheckable for `crowdin`. The source is available on GitHub (and I'm using the repo in the Livecheckable). It seems the Formula in homebrew-core is for an older major version. They have their own Tap though, where the newer version is available. Should we consider updating the Formula?
=> crowdin: add livecheckable

Livecheckables/hmmer.rb
Adding Livecheckable for `hmmer`.
Alternative page to check: http://hmmer.org/download.html
Also, I'm unsure if this regex has to be modified – they seem to have had version numbers with letters affixed at the end, in the past.
=> hmmer: add livecheckable

Livecheckables/ifstat.rb
Adding Livecheckable for `ifstat`. I've used a stricter regex w.r.t `href` (`href=['"]?` rather than `href=.*?`) because there's another package's link on the same page, which matches our looser regex. Any suggestions on improving the regex?
=> ifstat: add livecheckable

Livecheckables/confluent-platform.rb
Adding Livecheckable for `confluent-platform`.
I struggled with finding a good solution for this one. They don't have an idea page for all sources and the process to download the source tarball involves filling out an e-mail address, agreeing to T&C and then a submit action – the Downloads page has no url for the tarball in the page source.
The other option was to check the docs, which have buttons at the bottom right for the versions. I tried working with that but couldn't seem to get it right.
Finally I ended up matching text in the current release's Release Notes heading. Not ideal, but I'd like to know your suggestions on this one.
=> confluent-platform: add livecheckable

Livecheckables/httperf.rb
Adding Livecheckable for `httperf`.
Development has moved from Google Code to https://github.com/httperf/httperf but the problem is that they don't have releases or tags, or any changes.txt we can check for the latest version – that happens to be `0.9.1` which isn't available from Google Code. Have I missed something?
=> httperf: add livecheckable

Livecheckables/funcoeszz.rb
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck funcoeszz
Error: funcoeszz: Unable to get versions
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck funcoeszz
funcoeszz : 18.3 ==> 18.3
```
The `\.s` part is to ensure only the `.sh` ones are matched, and not any of the other numbers that appear in the `url` via the examples shown.
I checked that `--debug` only matches the one `version` up the top of the `url` and the 47 `version`'s at the bottom of the `url`.
Thank you.
=> funcoeszz: add livecheckable

Livecheckables/chafa.rb
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck chafa
Error: chafa: Unable to get versions
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck chafa
chafa : 1.4.1 ==> 1.4.1
```
Thanks.
=> chafa: add livecheckable

Livecheckables/vcs.rb
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck vcs
Error: vcs: Unable to get versions
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck vcs
vcs : 1.13.2 ==> 1.13.4
```
Note that I have sent a PR to update `vcs` [here](https://github.com/Homebrew/homebrew-core/pull/56927).
Thank you.
=> vcs: add livecheckable

Livecheckables/vorbis-tools.rb
The default check for `vorbis-tools` was unable to find any versions, so this adds a livecheckable with a URL and regex to establish a working check.
=> vorbis-tools: add livecheckable

Livecheckables/bash.rb, Livecheckables/readline.rb
I have updated the `url`'s for `bash` and `readline`, as the old ones are `404 Not Found`.
Before:
```
-bash-5.0.17- /Users/miccal (37) [> brew livecheck bash readline
Error: bash: 404 Not Found
Error: readline: 404 Not Found
```
After:
```
-bash-5.0.17- /Users/miccal (37) [> brew livecheck bash readline
bash : 5.0.17 ==> 5.0.17
readline : 8.0.4 ==> 8.0.4
```
Thanks.
=> bash & readline: update url

Livecheckables/pango.rb
I have created a `livecheckable` for `pango` using `:stable` for the `url` so that it uses GNOME's "even-numbered minor is stable" scheme. Previously, `livecheck` was using `https://gitlab.gnome.org/GNOME/pango.git`.
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck pango
pango : 1.44.7 ==> 1.45.3
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck pango
pango : 1.44.7 ==> 1.44.7
```
Closes https://github.com/Homebrew/homebrew-livecheck/issues/1035
Thanks.
=> pango: add livecheckable

Livecheckables/nomad.rb
I have updated the `livecheckable` for `nomad` to use `https://releases.hashicorp.com/nomad/` for the `url` and added `[<\/a>]` to the regex based on studying the page source of the `url` -- this is so that things like `-beta1`, `-rc1` and/or `-connect1` are not included in `livecheck`.
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck nomad
nomad : 0.11.3 ==> 0.12.0
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck nomad
nomad : 0.11.3 ==> 0.11.3
```
Closes https://github.com/Homebrew/homebrew-livecheck/issues/1036
Thanks.
**EDIT:** This is what I had originally:
```
class Nomad
livecheck do
url "https://releases.hashicorp.com/nomad/"
regex(/href=.*?nomad_v?(\d+(?:\.\d+)+)[<\/a>]/i)
end
end
```
=> nomad: update livecheckable

Livecheckables/pixman.rb
I have slightly updated the `livecheckable` for `pixman` to conform to the recent style, combined with the assumption that only even minor versions are stable, as explained [here for `cairo`](https://www.cairographics.org/manual/cairo-Version-Information.html):
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck pixman
pixman : 0.40.0 ==> 0.40.0
```
Thanks.
=> pixman: update livecheckable

Livecheckables/cairomm.rb
I have updated the `livecheckable` for `cairomm` to conform to the recent style, combined with the assumption that only even minor versions are stable, as explained [here for `cairo`](https://www.cairographics.org/manual/cairo-Version-Information.html). This matches https://github.com/Homebrew/homebrew-livecheck/pull/1041  and https://github.com/Homebrew/homebrew-livecheck/pull/1042.
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck cairomm
cairomm : 1.12.2 ==> 1.15.5
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck cairomm
cairomm : 1.12.2 ==> 1.12.2
```
Closes https://github.com/Homebrew/homebrew-livecheck/issues/1040
Thanks.
=> cairomm: update livecheckable

Livecheckables/chibi-scheme.rb
The site is down, reported in [here](https://github.com/ashinn/chibi-scheme/issues/663)
I also updated the formula to [use github resource](https://github.com/Homebrew/homebrew-core/pull/57097) 
```
$ brew livecheck chibi-scheme
chibi-scheme : 0.8 ==> 0.8
```
=> chibi-scheme: update url and regex

Livecheckables/cairo.rb
I have slightly updated the `livecheckable` for `cairo` to conform to the recent style, combined with the fact that only even minor versions are stable, as explained [here](https://www.cairographics.org/manual/cairo-Version-Information.html) -- I had to add `[^r]` to ensure that the releases for `rcairo` were not included. This matches https://github.com/Homebrew/homebrew-livecheck/pull/1041, and it outputs the same as before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck cairo
cairo : 1.16.0 ==> 1.16.0
```
Thanks.
=> cairo: update livecheckable

Livecheckables/mit-scheme.rb
The `:homepage` lists versions for both the stable and testing releases, so I have changed the `url` as suggested in https://github.com/Homebrew/homebrew-livecheck/issues/1049 and updated the regex accordingly.
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck mit-scheme
mit-scheme : 10.1.11 ==> 11.0.90
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck mit-scheme
mit-scheme : 10.1.11 ==> 10.1.11
```
Closes https://github.com/Homebrew/homebrew-livecheck/issues/1049
Thanks.
=> mit-scheme: update livecheckable

Livecheckables/moarvm.rb
Adding Livecheckable for `moarvm`. Closes #1054.
=> moarvm: add livecheckable

Livecheckables/mono.rb
I have updated the `livecheckable` for `mono` to use the `url` at `https://www.mono-project.com/download/stable/` for its stable version. 
Looking at the source of this page, I see the following:
```
href="https://download.mono-project.com/archive/6.8.0/macos-10-universal/MonoFramework-MDK-6.8.0.123.macos10.xamarin.universal.pkg"
```
hence the addition of `\.macos` in the regex, which I think will prevent other numerical matches that may have nothing to do with the stable version.
Output before:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck mono
mono : 6.8.0.123 ==> 6.10.0.104
```
Output after:
```
-bash-5.0.17- /Users/miccal (29) [> brew livecheck mono
mono : 6.8.0.123 ==> 6.8.0.123
```
Closes https://github.com/Homebrew/homebrew-livecheck/issues/1048
Thanks.
=> mono: update livecheckable

Livecheckables/pwncat.rb
Adding Livecheckable for `pwncat`. Closes #1055.
=> pwncat: add livecheckable

cmd/livecheck.rb, livecheck/heuristic.rb, livecheck/livecheck_strategy.rb, livecheck/livecheck_strategy/apache.rb, livecheck/livecheck_strategy/bitbucket.rb, livecheck/livecheck_strategy/git.rb, livecheck/livecheck_strategy/gnome.rb, livecheck/livecheck_strategy/gnu.rb, livecheck/livecheck_strategy/hackage.rb, livecheck/livecheck_strategy/launchpad.rb, livecheck/livecheck_strategy/npm.rb, livecheck/livecheck_strategy/page_match.rb, livecheck/livecheck_strategy/pypi.rb, livecheck/livecheck_strategy/sourceforge.rb, livecheck/utils.rb
Work on this started months ago when the strategies were all one big if/elsif statement in `heuristic.rb` and the general idea was to refactor the strategies into individual units of some sort (see the tail end of #301).
@maxim-belkin opened a PR (#601) before I had gotten around to creating one for my changes, so I ended up using that PR to close the gap some between the state of livecheck at the time and my refactoring work by moving the strategies into functions in `livecheck_strategy.rb`.
He had suggested that we create individual files for each strategy but I hadn't determined if that was going to be the best approach with the future migration to Homebrew/brew in mind. This ended up being appropriate In the end, after I took some inspiration from `unpack_strategy.rb`.
This creates a …
=> Refactor strategies, add debug and JSON info

livecheck/heuristic.rb
After some discussion in #1025, I added `.empty?` to the `Version` class in Homebrew/brew#7846. This allows us to remove the code in `latest_version()` that creates an empty `Version` and replace the `version == empty_version` comparison with `version.empty?`. This accomplishes the same goal without an unnecessary allocation.
=> Replace empty_version with version.empty?

livecheck/heuristic.rb
I had moved `latest_version()` to use `strategy::NAME` instead of `strategy.name.demodulize` in #1025 but I missed this one instance.
=> Address remaining use of strategy.name.demodulize

Livecheckables/byacc.rb
This PR updates `byacc`'s `regex` to match current standards. I didn't use our standard `(\d+(?:\.\d+)+)` for two reasons:
1. All versions have been of the form `YYYYMMDD`
2. There is just one `byacc-1.9` at the bottom of the page we're checking, and I didn't want to match it.
Then again,`\d{8}` may be too strict or there might be better alternatives.
=> byacc: update regex

cmd/livecheck.rb
Formula.tap can be nil in some cases. Currently this make livecheck fail without any useful error message. I think the simplest fix is to skip those when looking at non-core taps.
=> Allow to livecheck formulae without tap

Livecheckables/c-ares.rb
Updating `c-ares`'s `regex` to conform to current standards.
=> c-ares: update regex

Livecheckables/iozone.rb
This PR modifies `iozone`'s Livecheckable to match our current standards.
I had a hard time deciding what to do for this one, due to multiple possible variants that would work. I'll try to outline the rationale behind my final choice here:
1. The `:homepage` check isn't as reliable checking the index page with all versions. Sp I've used `http://www.iozone.org/src/current`.
2. The URL for the Stable releases page and Current releases (or Latest releases) is the same – on the homepage there are two `<a>` tags, one for Stable files and the other for Latest files. Both have the same `href=` attribute values (which is the `url` I've used here).
3. The filename patterns have changed over the years.
* Sometimes there has been a delimiter between `iozone` and `3`, now there isn't. Hence I've used …
=> iozone: update url and regex

README.md
The example in README.md is outdated and doesn't match the current format/style
=> README: update example livecheckable formula

Livecheckables/cern-ndiff.rb, Livecheckables/freeradius-server.rb, Livecheckables/simgrid.rb, Livecheckables/smpeg.rb
In reference to my [comment in #1067](https://github.com/Homebrew/homebrew-livecheck/pull/1067#pullrequestreview-443533365), this updates the existing use of `[_.]` in livecheckables to `[._]`. This is functionally identical but it's stylistically in line with the order we use in `[._-]`, which we use in other contexts. It's not a meaningful change but standardizing the order simply makes it easier to search for across livecheckables.
=> Update [_.] delimiters to [._]

Livecheckables/lua.rb
Updating `lua`'s `regex` to conform to current standards.
=> lua: update regex

Livecheckables/lynx.rb
Updating `lynx`'s `regex` to conform to current standards.
=> lynx: update regex

Livecheckables/lzip.rb
Updating `lzip`'s `regex` to conform to current standards.
=> lzip: update regex

Livecheckables/rsync.rb
Updating `rsync`'s `regex` to conform to current standards.
=> rsync: update regex

Livecheckables/siege.rb
Update `siege`'s `regex` to conform to current standards.
=> siege: update regex

Livecheckables/speex.rb
Update `speex`'s `regex` to conform to current standards.
=> speex: update regex

Livecheckables/tokyo-cabinet.rb
Update `tokyo-cabinet`'s `regex` to conform to current standards.
=> tokyo-cabinet: update regex

Livecheckables/xvid.rb
Updating `xvid`'s `regex` to conform to current standards.
=> xvid: update regex

Livecheckables/aspectj.rb, Livecheckables/cfr-decompiler.rb
This PR updates the Livecheckables which contain `\.j` in their regex to use `\.jar` instead. The Livecheckables affected are `aspectj` and `cfr-decompiler`.
=> Change \.j to \.jar in regex

Livecheckables/antlr4-cpp-runtime.rb, Livecheckables/exomizer.rb, Livecheckables/groovy.rb, Livecheckables/groovysdk.rb, Livecheckables/gsoap.rb, Livecheckables/ptex.rb, Livecheckables/sonarqube.rb, Livecheckables/spring-roo.rb, Livecheckables/wirouter_keyrec.rb
In this PR, Livecheckable regexes containing `\.z` are modified to use `\.zip`. The Livecheckables affected are:
```
1 antlr4-cpp-runtime.rb
2 exomizer.rb
3 groovy.rb
4 groovysdk.rb
5 gsoap.rb
6 ptex.rb
7 sonarqube.rb
8 spring-roo.rb
9 wirouter_keyrec.rb
```
=> Change \.z to \.zip in regex

README.md
In the interest of temporarily discouraging contributions that are unrelated to unblocking the migrations to homebrew-core and Homebrew/brew, I've added a notice to the README's Contributing section to explain the situation. The homebrew-core migration should occur sometime in the next few weeks, if everything goes according to plan.
=> README: Add temporary contributing notice

Livecheckables/bcftools.rb
Update `bcftools` to conform to current standards.
=> bcftools: update url and regex

livecheck/livecheck_strategy/git.rb, livecheck/livecheck_strategy/gnu.rb
We seem to have a new audit that's giving us warnings about a couple strategies.
```
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/livecheck/livecheck_strategy/git.rb ==
C: 20: 17: Use String#include? instead of a regex match with literal-only pattern.
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/livecheck/livecheck_strategy/gnu.rb ==
C: 29:  7: Use String#include? instead of a regex match with literal-only pattern.
```
This PR addresses both of these issues in a contextually-appropriate manner.
Edit: A comparison of output before and after these changes showed that everything is still working the same, so this should be fine to merge.
=> Address new style warnings

livecheck/livecheck_strategy/git.rb, livecheck/livecheck_strategy/page_match.rb, livecheck/utils.rb
This incorporates strategy-related functions from `utils.rb` into the strategies where they're used. Namely, `git_tags()` is incorporated into the `Git` strategy and `page_matches()` is added to the `PageMatch` strategy.
The reason why I'm renaming `git_tags()` to `tag_info()` here is because others have asked that we surface the commit hash in the future, if possible. I have a local implementation of this but I likely won't be able to add it until sometime after the Homebrew/brew migration.
This is part of a larger refactoring effort that I'm currently working on (and should be finished by the end of the week) but I'm trying to decompose it into topical PRs, when possible.
=> Integrate strategy functions into strategies

livecheck_strategy/apache.rb, livecheck_strategy/bitbucket.rb, livecheck_strategy/git.rb, livecheck_strategy/gnome.rb, livecheck_strategy/gnu.rb, livecheck_strategy/hackage.rb, livecheck_strategy/launchpad.rb, livecheck_strategy/npm.rb, livecheck_strategy/pypi.rb, livecheck_strategy/sourceforge.rb
The `regex` parameter for each strategy's `#find_versions` method was technically optional except for the `PageMatch` strategy. This updates the function definitions to use `find_versions(url, regex = nil)` (instead of `find_versions(url, regex)`).
This doesn't create any functional changes for livecheck, since `latest_versions()` uses a `nil` value as the `regex` argument when one isn't provided. However, I think it's simply better to be explicit in the function definition about `regex` being optional.
=> Make find_versions regex param explicitly optional

Livecheckables/wiggle.rb
I was going through the Livecheckables that needed updates with `href`, and I noticed that this one could use the index page instead. Sorry to make a single Livecheckable PR but I thought we could make the change anyway as it's 'cleanup'.
=> wiggle: update url and regex

Livecheckables/mbedtls.rb
Livecheckable was broken, they now mark latest releases on GitHub and recommend downloading from there.
Link to downloads page: https://tls.mbed.org/download
GitHub releases page: https://github.com/ARMmbed/mbedtls/releases
=> mbedtls: update livecheckable

Livecheckables/libtrng.rb
This brings the existing `libtrng` livecheckable up to current standards:
* Use `href=.*?` (instead of `href=`, in this case)
=> libtrng: update regex

Livecheckables/src.rb
This brings the existing `src` livecheckable up to current standards:
* Use `href=.*?` (instead of `href='.*?`, in this case)
=> src: update regex

Livecheckables/cassandra.rb
This brings the existing `cassandra` livecheckable up to current standards:
* Use `href=.*?` (instead of `href=".*?`, in this case)
=> cassandra: update url and regex

Livecheckables/bind.rb
This brings the existing `bind` livecheckable up to current standards:
* Use `href=.*?` (instead of `href=".*?`, in this case)
* Use `v?(\d+(?:\.\d+)+)` instead of `([0-9.]+)` `([A-Za-z0-9.\-]+)` in this case)
Besides the changes above, BIND uses an even-numbered minor (e.g., x.2.x) to indicate stable releases, so this updates the regex to only match those versions. This approach mimics what we do in similar formula that use an even-numbered minor for stable releases and is generally more in line with what we do in most other checks these days.
=> bind: update regex

Livecheckables/abcl.rb
This brings the existing `abcl` livecheckable up to current standards:
* Use `v?(\d+(?:\.\d+)+)` instead of `([0-9.]+)` (`([0-9,.]+)` in this case)
Generally speaking, this brings the regex in line with the other checks that identify version numbers from directories on a directory listing page like `1.2.3/`.
=> abcl: update url and regex

Livecheckables/eprover.rb
This brings the existing `eprover` livecheckable up to current standards:
* Use some flavor of `v?(\d+(?:\.\d+)+)` instead of `([0-9.]+)`
Though the folders on this directory listing page have a format like `V_1.2/`, this loosens the regex a bit, in case the directory name format is changed to `1.2` in the future. This also brings the regex more in line with other checks that match versions in folder names on a directory listing page.
=> eprover: update regex

Livecheckables/nasm.rb
This brings the existing `nasm` livecheckable up to current standards:
Generally speaking, this brings the regex in line with the other checks that identify version numbers from directories on a directory listing page like `1.2.3/`.
=> nasm: update regex

Livecheckables/wireguard-go.rb
This brings the existing `wireguard-go` livecheckable up to current standards:
* Use `href=.*?` (instead of `href=.*>`, in this case)
=> wireguard-go: update regex

Livecheckables/easy-git.rb
This brings the existing `easy-git` livecheckable up to current standards:
* Use `["' >]` instead of the trailing `"`
=> easy-git: update regex

Livecheckables/libnatpmp.rb
This brings the existing `libnatpmp` livecheckable up to current standards:
* Use `href=.*?` (instead of `href='download.php\?file=`, in this case)
* Use `v?(\d{6,8})` instead of `([0-9]+)`
=> libnatpmp: update regex

Livecheckables/libuecc.rb
This brings the existing `libuecc` livecheckable up to current standards:
* Use `href=.*?` (instead of `href='`, in this case)
* Use a flavor of `v?(\d+(?:\.\d+)+)` instead of `([0-9.]+)`
In general, this modifies this check to get the version from the tarball instead of the tag on the page. The updated version-matching also identifies the `0.1` version, which wasn't matched by the previous regex. Most versions these days are like `2`, `3`, etc. but this will continue to work if there are versions like `1.2`, `1.2.3`, etc. in the future.
=> libuecc: update regex

Livecheckables/ocaml.rb
This brings the existing `ocaml` livecheckable up to current standards:
* Use `href=.*?` (instead of `href='`, in this case)
* Use `v?(\d+(?:\.\d+)+)` instead of `([\d.]+\.[\d.]+\.?[\d.]?)`
This also removes the leading `<a ` and trailing `'>`, as they're unnecessary in this context.
=> ocaml: update regex

Livecheckables/gpa.rb
This brings the existing `gpa` livecheckable up to current standards:
* Use `v?(\d+(?:\.\d+)+)` instead of `(\d+\.\d+(\.\d+)?)`
=> gpa: update regex

Livecheckables/lcdf-typetools.rb
This brings the existing `lcdf-typetools` livecheckable up to current standards:
* Use `href=.*?` (instead of `href='`, in this case)
=> lcdf-typetools: update regex

Livecheckables/mupdf-tools.rb
This brings the existing `mupdf-tools` livecheckable up to current standards:
This uses `\.(?:t|zip)` for the file extension, as there's one zip archive among the tarballs.
=> mupdf-tools: update regex

Livecheckables/npth.rb
This brings the existing `npth` livecheckable up to current standards:
* Use `v?(\d+(?:\.\d+)+)` instead of `(\d+\.\d+(\.\d+)?)`
=> npth: update regex

Livecheckables/spandsp.rb
This brings the existing `spandsp` livecheckable up to current standards:
* Use `v?(\d+(?:\.\d+)+)` instead of `([\d.]+)`
This also loosens the trailing `\.tar\.gz"` to the standard `\.t`, which allows it to match another version on the index page that we were missing (due to it using a `.tgz` extension).
=> spandsp: update regex

Livecheckables/zsh-lovers.rb
This brings the existing `zsh-lovers` livecheckable up to current standards:
=> zsh-lovers: update regex

Livecheckables/python.rb, Livecheckables/python@3.8.rb
Renaming `python.rb` to `python@3.8.rb` as the Formula in core is `python@3.8`. Prior to this change, livecheck would give `python@3.8 : versioned` as the output for `brew livecheck python`.
=> python: rename to python@3.8, update regex

Livecheckables/fluent-bit.rb
This brings the existing `fluent-bit` livecheckable up to current standards:
* Use the standard regex for Git tags like `1.2.3` or `v1.2.3` (`/^v?(\d+(?:\.\d+)+)$/i`)
=> fluent-bit: update url and regex

Livecheckables/jhiccup.rb
This brings the existing `jhiccup` livecheckable up to current standards:
=> jhiccup: update regex

Livecheckables/libflowmanager.rb
This brings the existing `libflowmanager ` livecheckable up to current standards:
=> libflowmanager: update regex

Livecheckables/libtrace.rb
This brings the existing `libtrace ` livecheckable up to current standards:
=> libtrace: update regex

Livecheckables/django-completion.rb
This brings the existing `django-completion` livecheckable up to current standards:
* Use the standard regex for Git tags like `1.2.3` or `v1.2.3` (`/^v?(\d+(?:\.\d+)+)$/i`)
=> django-completion: update url and regex

Livecheckables/libprotoident.rb
This brings the existing `libprotoident ` livecheckable up to current standards:
=> libprotoident: update regex

Livecheckables/sonarqube-lts.rb
This brings the existing `sonarqube-lts` livecheckable up to current standards:
* Use `href=.*?` (instead of `href=.+?`, in this case)
=> sonarqube-lts: update regex

Livecheckables/libcello.rb
This brings the existing `libcello` livecheckable up to current standards:
This also removes the trailing `.*?>Download}`, as it's unnecessary.
=> libcello: update regex

Livecheckables/mpich.rb
This brings the existing `mpich ` livecheckable up to current standards:
* Use `v?(\d+(?:\.\d+)+)` instead of `([0-9.]+)` (`([0-9a-z.]+)` in this case)
Generally speaking, this brings the regex in line with the other checks that identify version numbers from directories on a directory listing page like `1.2.3/`.
=> mpich: update url and regex

Livecheckables/ragel.rb
This brings the existing `ragel ` livecheckable up to current standards:
Unfortunately it's currently necessary to use the HTTP version of the homepage instead of the HTTPS URL in the formula, since there's an upstream SSL verification issue. I left a comment noting that we should return to using `url :homepage` once this is resolved upstream.
=> ragel: update url and regex

Livecheckables/aqbanking.rb, Livecheckables/libmikmod.rb, Livecheckables/mikmod.rb
This PR improves regexes containing `href=.*` in the following ways:
* `href=.*` –> `href=.*?`
* `[0-9.]+` or `[0-9.,]+` –> `(\d+(?:\.\d+)+)`
* Delimiter between software name and version string, `-` –> `[._-]`
* The regexes are now case-insensitive
The Livecheckables affected are `aqbanking`, `libmikmod` and `mikmod`.
=> Improve regexes containing `href=.*`

cmd/livecheck.rb, livecheck_strategy.rb
We now have a "Sort files before requiring them" style warning, so this modifies the strategy-requiring code  in `cmd/livecheck.rb` and `livecheck_strategy.rb` to involve a sort.
=> Fix "Sort files before requiring them" warning

Livecheckables/ant.rb, Livecheckables/ant@1.9.rb, Livecheckables/aspell.rb, Livecheckables/cppunit.rb, Livecheckables/cvsync.rb, Livecheckables/dterm.rb, Livecheckables/geos.rb, Livecheckables/gl2ps.rb, Livecheckables/gnu-prolog.rb, Livecheckables/icoutils.rb, Livecheckables/miniupnpc.rb, Livecheckables/nload.rb, Livecheckables/nuttcp.rb, Livecheckables/onioncat.rb, Livecheckables/scamper.rb, Livecheckables/szip.rb, Livecheckables/theora.rb, Livecheckables/transmission-cli.rb, Livecheckables/x264.rb, Livecheckables/zabbix.rb
This PR improves regexes containing `href=.*` in the following ways:
* `href=.+` or `href=.+?` –> `href=.*?`
* Delimiter between software name and version string, `-` –> `[._-]`
* The regexes are now case-insensitive
* Additional fixes in
* `icoutils`
* `scamper`
* `szip`
* `x264`
=> Improve regexes containing `href=.+` and `href=.+?`

Livecheckables/midnight-commander.rb
The existing check is giving an SSL error:
```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)
```
The Midnight commander homepage says "A list of the latest releases is available [here](http://www.midnight-commander.org/downloads)", pointing to http://www.midnight-commander.org/downloads. The downloads URL redirects to http://ftp.midnight-commander.org, which is a directory listing page.
This modifies the livecheckable to use the aforementioned page and updates the regex accordingly.
=> midnight-commander: update url and regex

Livecheckables/fortune.rb
The existing livecheckable for `fortune` is giving an SSL error:
```
Error: fortune: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)
```
This temporarily modifies the URL to use HTTP instead of HTTPS (leaving a comment to return to HTTPS when possible).
Besides that, I also made a small change to the regex to bring it up to current standards.
=> fortune: update url and regex

Livecheckables/fossil.rb
The existing livecheckable for `fossil` broke since the format of the release `title` strings in `download.js` changed a little (so the regex failed to match).
The format now seems to be:
* Preview/unstable: "Version 2.12 preview 2020-07-12"
* Stable: "Version 2.11.1 circa 2020-05-25 + patches"
This check is more fragile than I would like but I don't think we have any other choice but to keep updating the regex when upstream makes breaking changes like this.
=> fossil: update regex

Livecheckables/biosig.rb
The existing livecheckable for `biosig` wasn't finding the latest versions in the SourceForge RSS feed, since the filename format changed. This updates the regex to match both the older and newer file name format.
This also adds an explicit `url`, as it's one of the few remaining livecheckables without one.
=> biosig: add url and update regex

Livecheckables/darkice.rb
The existing livecheckable for `darkice` wasn't able to identify any versions. This updates it to check the "latest" release on GitHub (as the formula uses archives from the GitHub repository).
This also adds an explicit `url` in the process, as it was one of the few remaining livecheckables without one.
=> darkice: add url and update regex

Livecheckables/x3270.rb
The existing livecheckable for `x3270` was not able to find versions. This updates it to check [the first-party downloads page](http://x3270.bgp.nu/download.html) and updates the regex to bring it up to current standards.
This also adds an explicit `url` in the process, as this was one of the few remaining livecheckables without one.
=> x3270: add url and update regex

Livecheckables/burp.rb
The existing livecheckable for `burp` wasn't able to find versions. This updates it to use the `stable` URL (a SourceForge archive) and updates the regex accordingly (while also following current standards).
=> burp: update url and regex

Livecheckables/stk.rb
The existing livecheckable for `stk` is currently failing due to an upstream SSL certificate issue. Unfortunately, we can't work around this, as HTTP URLs simply redirect to HTTPS. As a result, CI will predictably fail for this PR until the upstream situation is resolved.
However, this regex needs to be brought up to our current standards. I'm handling this individually, so this one PR can fail instead of tanking a batch PR.
=> stk: update regex

Livecheckables/alpine.rb
The default check for `alpine` checks the HEAD repo (https://repo.or.cz/alpine.git) but it's currently experiencing SSL issues:
```
fatal: unable to access 'https://repo.or.cz/alpine.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to repo.or.cz:443
```
This addresses the issue by adding a livecheckable that uses the homepage, as that's the closest we can get to the stable source (i.e., the `src` subdirectory doesn't allow directory listing).
=> alpine: add livecheckable

cmd/livecheck.rb
The `formulae_to_check` variable in `#livecheck` is usually an array of `Formula` objects or `nil`. However, when formulae are collected from the watchlist file, `formulae_to_check` is an `Enumerator` instead of an array.
This PR reworks the watchlist code to produce an array of formulae, like the other conditional blocks. Though this consistency is good in its own right, I specifically worked on this so that we'll be able to produce an error when `formulae_to_check` is empty (which we can't do with an `Enumerator`).
=> Use array instead of enumerator for watchlist

livecheck/livecheck_strategy/xorg.rb
Some of the X.Org formulae from linuxbrew/xorg are being merged into homebrew-core in Homebrew/homebrew-core#57995. With this in mind, livecheck needs to handle the checks for these formulae. The linuxbrew/xorg tap has an `Xorg` strategy (created by Maxim) that's used on these formulae, so I'm incorporating it into livecheck as a built-in strategy.
The `Xorg` strategy wasn't quite working properly for all of the cases that I encountered, so I made some improvements:
* Modified the `match?` logic to only match URLs the strategy can use (we can expand this as needed)
* Reworked the way that the `package_name`, `page_url`, and `regex` are identified and generated, so it should be a little more reliable than the previous method
* Added support for caching page content, so we don't end up …
=> Add Xorg strategy

Livecheckables/alluxio.rb, Livecheckables/autogen.rb, Livecheckables/coturn.rb, Livecheckables/docbook.rb, Livecheckables/gcc@4.9.rb, Livecheckables/gcc@5.rb, Livecheckables/gcc@6.rb, Livecheckables/gcc@7.rb, Livecheckables/libpq.rb, Livecheckables/poco.rb, Livecheckables/qcachegrind.rb, Livecheckables/spades.rb, Livecheckables/speech-tools.rb, Livecheckables/sword.rb, Livecheckables/tomcat-native.rb, Livecheckables/tomcat@7.rb, Livecheckables/tomcat@8.rb
This PR changes `href="` when followed by a version directory to `href=.*?`, and also updates the portion of the regex checking for `/` to `/?["' >]`.
Note: `jenkins-lts` will be handled separately.
=> Change `href="` followed by version directory to `href=.*?`

Livecheckables/libvisio.rb
This brings the existing `libvisio` livecheckable up to current standards:
* Use `v?(\d+(?:\.\d+)+)` instead of `([0-9.\-]+)`
=> libvisio: update url and regex

Livecheckables/aescrypt-packetizer.rb, Livecheckables/duck.rb, Livecheckables/dxflib.rb, Livecheckables/gkrellm.rb, Livecheckables/libav.rb, Livecheckables/mednafen.rb, Livecheckables/mupdf.rb, Livecheckables/mysql-connector-c++.rb, Livecheckables/mysql.rb, Livecheckables/mysql@5.6.rb, Livecheckables/mysql@5.7.rb, Livecheckables/packetq.rb, Livecheckables/unp64.rb, Livecheckables/unrar.rb, Livecheckables/varnish.rb, Livecheckables/xrootd.rb
This PR changes `href="` when followed by a path to `href=.*?`.
Extra attention is to be paid to the `mysql` family of Livecheckables, and `unp64` – due to the lack of alternative solutions which I felt would be apt (w.r.t matching a `.t` or something at the end).
=> Change `href="` followed by path to `href=.*?`

Livecheckables/jenkins-lts.rb
This PR updates the regex for `jenkins-lts`, bringing it up to current standards.
When changing `href="` to `href=.*?`, the older regex matched `2020-06-17` due to the capture group being `(\d+.\d+.\d+)`. A separate PR was necessary due to the additional changes involved.
The changes made are:
* `href="` –> `href=.*?`
* Matching `/` now done using `/?["' >]`
* Version capturing group is now `(\d+(?:\.\d+)+)`
* `v?` in case directory is prefixed with `v`
* Case-insensitivity
=> jenkins-lts: update regex

Livecheckables/vault.rb
This PR updates `vault`'s regex to conform to current standards. The leading path wasn't necessary for livecheck to work.
=> vault: update regex

Livecheckables/ctags.rb, Livecheckables/faad2.rb
This updates a couple of instances of `url=.*?` to `url=.*?/` to bring them in line with the vast majority of similar regexes. [The only exceptions are `mingw-w64` and `unzip`.]
=> Add forward slash to some url=.*? regexes

Livecheckables/libwps.rb
This PR updates `libwps`'s regex.
Changes:
* `href="` –> `href=.*?` and removal of leading path
* `/` matching –> `/?["' >]`
* `-` –> `[._-]` (delimiter between formula name and version)
* `v?` before version capturing group
* Version capturing group updated to current standard
* Case-insensitivity
=> libwps: update regex

Livecheckables/remake.rb
This PR updates `remake`'s regex to conform to current standards. The regex probably needs changing: it's stricter than the previous one but matches the versioning format they've followed since 2009.
Until the `alterations` feature is out, the Livecheckable won't work as intended (and this is, most probably, a known issue).
=> remake: update regex

Livecheckables/bashdb.rb
This PR updates the regex for `bashdb`.
The changes are:
* `href="` to `href=.*?` and removed the path from the regex
* They've been using `x.x-x.x(.x)?` since 2004, the version capturing group has been updated accordingly (needs to be checked, of course).
* `v?` prior to version capturing group
* `/` matching changed to `/?["' >]`
* Case-insensitivity
=> bashdb: update regex

Livecheckables/ccm.rb, Livecheckables/diffoscope.rb, Livecheckables/eralchemy.rb, Livecheckables/pgcli.rb, Livecheckables/pipenv.rb, Livecheckables/tox.rb
This PR changes `pypi.org/simple/...` urls to the `:stable` Formula url reference. The Livecheckables affected are those not already handled in #1152.
=> Update PyPI urls to stable Formula urls

Livecheckables/bcpp.rb
This PR updates `bcpp`'s regex to conform to current standards.
=> bcpp: update regex

Livecheckables/etsh.rb
This PR updates `etsh`'s regex to conform to current standards.
In #323, the regex was updated to match either the archive files (`\.t`) or the version directories (`/`). However I've reverted to matching just the archive files, as it was sufficient to detect all versions of `etsh` present on the page.
Do let me know if I must change the regex suffix back to what it was after #323.
=> etsh: update regex

Livecheckables/chkrootkit.rb
This PR updates `chkrootkit`'s regex to conform to current standards. I took inspiration from `pidof` for this one, but there may be better alternatives.
=> chkrootkit: update regex

Livecheckables/fizmo.rb
This PR updates `fizmo`'s regex to conform to current standards. The leading `/` is necessary to prevent matching versions of `libfizmo`.
=> fizmo: update regex

Livecheckables/exiftool.rb
This PR updates `exiftool`'s regex to conform to current standards.
Only the stable (production) version seems to have its archive file present on the page, and the text might change in the future, so I thought the usual `href=` matching would suffice.
=> exiftool: update regex

Livecheckables/fs-uae.rb
This PR updates `fs-uae`'s `url` to that of an index page of all releases, and also brings the `regex` up to current standards.
=> fs-uae: update url and regex

Livecheckables/gcc.rb
This PR updates `gcc`'s regex to conform to current standards. They've been using the version directory format consistently since 2003, so I thought it was okay to match only version directories. Let me know if that has to be changed.
=> gcc: update regex

Livecheckables/ghc.rb
This PR updates `ghc`'s `url` to that of an index page of all releases (which aligns with the stable archive location). The `regex` has also been updated as a result, and it conforms to current standards.
=> ghc: update url and regex

Livecheckables/nss.rb
This PR updates `nss`'s `url` to align with the location of the stable archive file. The `regex` has also been updated as a consequence, and has been brought up to current standards.
=> nss: update url and regex

Livecheckables/opus.rb
The `url` for `opus` has been updated to align with that of the stable archive. The new `url` is an index page of all versions. One concern is that either the file format (name) has either varied over the years, or the other names truly denote other software/Formulae. Do let me know if there are any changes.
=> opus: update url and regex

Livecheckables/libav.rb, Livecheckables/qtfaststart.rb
This PR updates `qtfaststart`'s `url` to align with that of the stable archive. The `regex` has also been updated to conform to current standards.
=> qtfaststart: update url and regex

Livecheckables/packer.rb
This PR updates the url of `packer` to the GitHub `latest` release page, as the stable URL in the Formula is that of the GitHub repository (tag v1.6.0). The regex has been updated accordingly.
=> packer: update url and regex

Livecheckables/sane-backends.rb
The stable archive for `sane-backends` is obtained from GitLab, so I decided to use `head` and match tags instead. Let me know if this should be changed to something else.
Note: About 2 or so years ago they were using `RELEASE_1_0_x` as the tag format, but this has changed since about 11 months ago. If we would like to match the older scheme as well, I'll update the regex.
=> sane-backends: update url and regex

Livecheckables/strongswan.rb
The url for `strongswan` has been updated to align with that of the stable archive file. The regex has been brought up to standards. The reason for `[a-z]?` – there was one `2.4.0a`, and if they decide to include releases named in that format sometime later, we should be able to match them. Let me know if this should be changed.
=> strongswan: update url and regex

Livecheckables/zanata-client.rb
This PR updates the url for `zanata-client` to align with that of the Formula's stable archive file. We need to match version directories with this url, so the regex has been updated accordingly.
=> zanata-client: update url and regex

Livecheckables/r.rb
This PR updates `r`'s `regex` to conform to current standards.
I checked if we could change the url to align with that of the stable archive, but the files are organised into directories and the filename of the latest version is `R-latest`, so I've not changed the url.
=> r: update regex

Livecheckables/terraform.rb
The url for `terraform` has been updated to its GitHub latest release URL, and the regex has been updated accordingly.
=> terraform: update url and regex

Livecheckables/cataclysm.rb, Livecheckables/ifstat.rb, Livecheckables/neo4j.rb, Livecheckables/nkf.rb, Livecheckables/node@12.rb, Livecheckables/ttyrec.rb
We've been standardizing on `["']`, `["' >]`, etc. and we updated most instances while working on the `href=` regexes but there were still a few lingering cases.
This brings these instances up to date while also addressing some other clean-up tasks in the process:
=> Align HTML attribute delimiters with current usage

Livecheckables/proguard.rb
The `proguard` formula now uses releases from GitHub, so the current check (SourceForge) wasn't finding the latest release (i.e., `proguard : 7.0.0 ==> 6.2.2`).
This updates the existing livecheckable to check the "latest" release on GitHub.
=> proguard: update url and regex

Livecheckables/desktop-file-utils.rb
The existing `desktop-file-utils` livecheckable broke when we added the `Xorg` strategy but this check will work properly if we simply remove the livecheckable.
=> desktop-file-utils: delete livecheckable

Livecheckables/micronaut.rb
The `micronaut` formula now uses releases from micronaut-projects/micronaut-starter, so this updates the livecheckable to check for the "latest" release from this repository.
=> micronaut: update url

Livecheckables/afl-fuzz.rb
The `afl-fuzz` formula was modified in Homebrew/homebrew-core to include the trailing `b` in the version (e.g., `2.57b`). This updates the livecheckable's regex to do the same.
=> afl-fuzz: update regex

Livecheckables/libwebsockets.rb
The existing livecheckable for `libwebsockets` is picking up an unstable version (i.e. `libwebsockets : 4.0.20 ==> 4.1.0-rc1`).
`libwebsockets` seems to have standardized on a `v1.2` or `v1.2.3` format in their Git tags, so we can simply use the standard regex for Git tags here.
=> libwebsockets: update regex

Livecheckables/boost-build.rb
The existing livecheckable for `boost-build` was matching beta releases, returning a `1.74.0.` version as newest for a `1.74.0.beta1` Git tag.
This restricts matching to releases like `boost-1.73.0` and not `boost-1.69.0-beta1`, `boost-1.2.3-beta1`, `boost-1.30.2-rc1`, etc.
=> boost-build: update regex

Livecheckables/smpeg.rb
The `smpeg` formula shouldn't be matching releases at 2.0 or later, as that's what the `smpeg2` formula is for.
This updates the regex to restrict matching to major versions of 0 or 1. The latest `smpeg` version is 0.4.5 and there are no 1.x versions but I figured it would be a bit safer than just restricting to a major version of 0.
=> smpeg: update regex

Livecheckables/smpeg2.rb
This adds a livecheckable that is similar to the existing `smpeg` check but instead restricts matching to 2.x versions.
=> smpeg2: add livecheckable

Livecheckables/gabedit.rb
The existing livecheckable for `gabedit` checks release archives on SourceForge. Unfortunately these files have a name format like `GabeditSrc250.tar.gz` for version `2.5.0`. Until we have an `alterations` feature, where we could change `250` into `2.5.0`, this check doesn't work properly (i.e., 250 > 2.5.0).
This updates the livecheckable to check the "Downloads" page linked from the `gabedit` homepage. There hasn't been a new release since 2017-07-10, so this may not be infallible but it may be okay for now.
=> gabedit: update url and regex

Livecheckables/mbedtls.rb
It seems the `?` wasn't added after `.*` in `mbedtls`'s regex, so I've added it in this PR.
=> mbedtls: update regex

Livecheckables/sylpheed.rb, Livecheckables/xrootd.rb
It seems `sylpheed` and `xrootd` still used `href=".*?` so I've updated them to use `href=.*?` instead.
=> Change remaining `href=".*?` to `href=.*?`

Livecheckables/gocr.rb
The existing livecheckable for GOCR checks the homepage but after making the regex case insensitive it picks up releases for `libgocr` as well. Livecheck is still reporting the correct latest version but it would be better to deal with this instead of hoping it doesn't ever become a problem.
This simply updates the livecheckable to use the [Download](https://wasd.urz.uni-magdeburg.de/jschulen/ocr/download.html) page and updates the regex to only match archives like `gocr-0.52.tar.gz`.
=> gocr: update url and regex

Livecheckables/pngcrush.rb
The existing livecheckable for `pngcrush` checks an HTML changelog on SourceForge. Updating the regex to be case insensitive ended up matching more versions than before, which brought this to my attention.
This updates the livecheckable to use the `stable` URL, which uses the SourceForge strategy, and updates the regex accordingly.
=> pngcrush: update url and regex

Livecheckables/unixodbc.rb
The existing livecheckable for `unixodbc` started to match some additional versions when the regex was updated to be case insensitive. This was appropriate but this check was brought to my attention as a result.
This updates the livecheckable to check the downloads page instead, which is where the stable archive is found.
=> unixodbc: update url and regex

Livecheckables/gsoap.rb
The existing livecheckable for `gsoap` artificially restricts matching to 2.8.x versions, which doesn't seem necessary.
This also replaces the existing SourceForge URL with `:stable`, which uses the `Sourceforge` strategy, and updates the regex accordingly.
=> gsoap: update url and regex

Livecheckables/sqlite.rb
The existing livecheckable for `sqlite` was artificially restricted to a major version of 3 but this didn't seem necessary.
This updates the regex to match versions on the News page in a different manner, which will continue to work when there's a new major version.
=> sqlite: update regex

Livecheckables/dovecot.rb
The existing livecheckable for `dovecot` uses a URL that's restricted to a specific major/minor version. This becomes a problem when a new major/minor release happens, as the check will no longer find new versions and has to be manually updated to work again.
This updates the livecheckable to check the first-party downloads page instead and also brings the regex up to current standards.
=> dovecot: update url and regex

Livecheckables/wildfly-as.rb
This brings the existing `wildfly-as` livecheckable up to current standards:
=> wildfly-as: update regex

Livecheckables/ircii.rb
This brings the existing `ircii` livecheckable up to current standards:
* Use `href=.*?` to match the file name within the `href` attribute, when applicable
* Use `v?(\d{6,8})` for date-based versions instead of `([0-9]+)`
=> ircii: update url and regex

Livecheckables/libhdhomerun.rb
This brings the existing `libhdhomerun ` livecheckable up to current standards:
* Use `v?(\d{6,8})` for date-based versions instead of `([0-9]+)`
=> libhdhomerun: update regex

Livecheckables/dcmtk.rb
This brings the existing `dcmtk` livecheckable up to current standards:
* Use `v?(\d+(?:\.\d+)+)` instead of `([0-9._]+)`
=> dcmtk: update regex

Livecheckables/phplint.rb
This brings the existing `example` livecheckable up to current standards:
* Use some form of `v?(\d+(?:\.\d+)+)` instead of `([0-9._]+)`
Besides the above, this updates the livecheckable to check the first-party downloads page instead of the `CHANGES.txt` file.
=> phplint: update url and regex

Livecheckables/boost.rb
The existing livecheckable for `boost` used a regex that was matching text in the `<copyright>` element of the RSS feed, leading to the inclusion of a `1.0` version from the following text:
```
<copyright>Distributed under the Boost Software License, Version 1.0. (See accompanying file LICENSE_1_0.txt or https://www.boost.org/LICENSE_1_0.txt)</copyright>
```
This updates the regex to restrict matching to text between an opening and closing element, so we're only likely to match the `<title>` elements. If this isn't strict enough in the long run, we can modify the regex to be more explicit (e.g., `/<title[^>]*>Version v?(\d+(?:\.\d+)+)</i`).
Besides this, I've also updated the regex to be case insensitive, since it isn't required for matching with the aforementioned modification.
=> boost: update regex

Livecheckables/cabextract.rb
The existing livecheckable for `cabextract` was matching prerelease versions (e.g., `v0.0.20060920alpha`, `v0.10.1alpha`, etc.), since there was no ending delimiter.
This updates the check to use the homepage (since the formula's stable archive comes from the first-party website) and modifies the regex accordingly.
=> cabextract: update url and regex

Livecheckables/gromacs.rb
The recent update to the `gromacs` livecheckable's regex caused it to not match versions that consist of one numeric part like `2016`, `2018`, `2019`, and `2020` (most versions are like `2020.1`, `2020.2`, etc.).
This updates the regex to make the `(?:\.\d+)+` part optional (i.e., `(?:\.\d+)*`), which addresses this issue.
=> gromacs: update regex

Livecheckables/ii.rb
The recent update to the regex in the existing livecheckable for `ii` caused it to not match versions that consist of one numeric part like `1` (most versions are like `1.1`, `1.2`, etc.).
This updates the regex to make the `(?:\.\d+)+` part optional (i.e., `(?:\.\d+)*`), which addresses this issue.
=> ii: update regex

Livecheckables/zsh.rb
Before the recent update to the existing livecheckable's regex for `zsh`, the regex at the time (`/zsh-([0-9.]+)\./i`) was producing a partial match of `5` (along with the good `5.8` version), probably from the `zsh-5.8-doc.tar.xz` file. This was primarily due to the regex being too loose and not including an adequate trailing delimiter (e.g., `\.t`)
This brings the regex up to current standards, which will help to avoid this sort of situation in the future:
* Use `href=.*?` to match the file name within the `href` attribute, when applicable
* Use `\.t` as the trailing delimiter for tarballs
=> zsh: update regex

Livecheckables/autossh.rb, Livecheckables/calc.rb, Livecheckables/dwarfutils.rb, Livecheckables/fdclone.rb, Livecheckables/homebank.rb, Livecheckables/hspell.rb, Livecheckables/rsstail.rb, Livecheckables/sqliteodbc.rb
This PR updates instances of `HREF="` to `href=.*?` in Livecheckable regexes. I believe CI might fail (specifically for `hspell`) as SourceForge is experiencing problems right now.
Update (as expected):
```
Error: hspell: 503 Service Temporarily Unavailable
```
=> Update HREF=" to href=.*? in regexes

Livecheckables/acpica.rb, Livecheckables/dwarfutils.rb, Livecheckables/puzzles.rb, Livecheckables/wtf.rb
This PR depends on #1210 due to changes in `dwarfutils`.
I've updated `([0-9.]+)` in date-based version regexes to `v?(\d{6,8})`.
CI may fail for `wtf`'s livecheck as SourceForge is having problems.
=> Update ([0-9.]+) to v?(\d{6,8}) in regexes

Livecheckables/bmake.rb
This PR updates `bmake`'s regex to conform to current standards.
=> bmake: update regex

Livecheckables/txr.rb
This PR updates `txr`'s regex to conform to current standards.
They seem to have a 3-digit version number for now but in the past there was a sudden change to 2-digit versions, and then back to 3-digits. I've used just `\d+` but we might want to be stricter.
Also, the preceding `/` wasn't necessary so I removed it, but let me know if it should be added back.
=> txr: update regex

Livecheckables/diffoscope.rb
The PyPI strategy was working for this one, and it seemed like a Livecheckable was unnecessary. The output before and after the change are identical (version matches and latest).
=> diffoscope: remove livecheckable

Livecheckables/abcmidi.rb
This PR brings `abcmidi`'s regex up to current standards. They seem to be using a YYYY.MM.DD format, however I've been strict only with `\d{4}` for the year part of the version. Let me know if there are any changes, thanks!
=> abcmidi: update regex

cmd/livecheck.rb, livecheck/livecheck_strategy/apache.rb, livecheck/livecheck_strategy/bitbucket.rb, livecheck/livecheck_strategy/git.rb, livecheck/livecheck_strategy/gnome.rb, livecheck/livecheck_strategy/gnu.rb, livecheck/livecheck_strategy/hackage.rb, livecheck/livecheck_strategy/launchpad.rb, livecheck/livecheck_strategy/npm.rb, livecheck/livecheck_strategy/page_match.rb, livecheck/livecheck_strategy/pypi.rb, livecheck/livecheck_strategy/sourceforge.rb, livecheck/livecheck_strategy/xorg.rb
This fixes some RuboCop offenses that were added in Homebrew/brew:
* Freeze mutable objects assigned to constants
* Use the new Ruby 1.9 hash syntax
=> Fix new RuboCop offenses

Livecheckables/cppad.rb
This PR brings `cppad`'s regex up to current standards. They've consistently used a scheme that's 8 digits followed. by a dot and then a digit (could be digits). I didn't know what'd be the best solution here, but I've gone ahead with `(\d{8}(?:\.\d+)+)`, let me know if I should use something else.
=> cppad: update regex

Livecheckables/freetype.rb
This PR updates `freetype`'s regex to conform to current standards. I tried, initially, to match the filename so that we'd have a regex ending with `\.t`, but that doesn't match version `2.9`. So I used the same idea as the earlier regex, but just improved it based on our current standards. Do let me know if there are any changes.
=> freetype: update regex

Livecheckables/cmockery2.rb, Livecheckables/kpcli.rb, Livecheckables/lame.rb, Livecheckables/pcb.rb, Livecheckables/ser2net.rb, Livecheckables/shmcat.rb, Livecheckables/tclap.rb, Livecheckables/v8.rb, Livecheckables/writerperfect.rb
This PR updates regexes with multiple `[0-9.]+`s to our current default regex. Only `cmockery2` has an extra change – the `^...$` format to prevent matching any unstable tags (if present).
=> Update multiple [0-9.]+ to v?(\d+(?:\.\d+)+) in regexes

Livecheckables/postgresql@9.5.rb, Livecheckables/postgresql@9.6.rb
This PR updates the capture group in the regexes of `postgresql@9.5` and `postgresql@9.6`. I had missed updating these two regexes with my previous PR.
=> Update regex for postgresql@9.5 and postgresql@9.6

Livecheckables/dialog.rb
This PR brings `dialog`'s regex up to current standards.
=> dialog: update regex

Livecheckables/ffe.rb, Livecheckables/gdcm.rb, Livecheckables/gputils.rb, Livecheckables/imagemagick.rb, Livecheckables/libcdr.rb, Livecheckables/libtiff.rb, Livecheckables/libwpd.rb, Livecheckables/libwpg.rb, Livecheckables/omniorb.rb, Livecheckables/owamp.rb, Livecheckables/udpxy.rb
This PR updates `[0-9.-]` and `[0-9.\-]+` in regexes to conform to our current standards for the capturing group.
* If all versions reported by livecheck before the changes did not contain `-`, `v?(\d+(?:\.\d+)+)` was used.
* If some versions reported by livecheck contained `-`, `v?(\d+(?:\.\d+)+(?:-\d+)?)` was used.
* If `-` was present in all versions reported by livecheck, `v?(\d+(?:\.\d+)+-\d+)` was used.
=> Update [0-9.-] and [0-9.\-] in regexes

Livecheckables/percona-toolkit.rb
This PR brings `percona-toolkit`'s regex up to current standards. I figured matching `-` wasn't necessary as no versions reported by livecheck before the change included `-`. Let me know if any changes are required. Thanks!
=> percona-toolkit: update regex

Livecheckables/autossh.rb
This PR brings `autossh`'s regex up to current standards. I didn't want to deviate from the earlier regex too much so I've used `[a-z]+`, just as before.
=> autossh: update regex

Livecheckables/vsts-cli.rb
The Livecheckable was unnecessary thanks to the PyPI strategy. Also, I found this on the "homepage" linked to on PyPI (which happens to be this [repo](https://github.com/Azure/azure-devops-cli-extension)):
```
The Azure CLI with the Azure DevOps Extension has replaced the VSTS CLI. The VSTS CLI
has been deprecated and will no longer be receiving new features. We recommend that users
of the VSTS CLI switch to the Azure CLI and add the Azure DevOps extension.
```
=> vsts-cli: remove livecheckable

cmd/livecheck.rb, livecheck/livecheck_strategy/apache.rb, livecheck/livecheck_strategy/bitbucket.rb, livecheck/livecheck_strategy/git.rb, livecheck/livecheck_strategy/gnome.rb, livecheck/livecheck_strategy/gnu.rb, livecheck/livecheck_strategy/hackage.rb, livecheck/livecheck_strategy/launchpad.rb, livecheck/livecheck_strategy/npm.rb, livecheck/livecheck_strategy/page_match.rb, livecheck/livecheck_strategy/pypi.rb, livecheck/livecheck_strategy/sourceforge.rb, livecheck/livecheck_strategy/xorg.rb
Currently `LivecheckStrategy` classes are required to include `NAME = name.demodulize.freeze`, so that we avoid running this code numerous times within `#latest_version`. Ideally this should be handled within livecheck, so it's not necessary to include this snippet in all `LivecheckStrategy` classes.
This PR aims to achieve this by creating and populating a `@livecheck_strategy_names` hash, which maps a `LivecheckStrategy` to the demodulized strategy name. With this setup, we continue to only run `strategy.name.demodulize` once per strategy over a given run of `brew livecheck`.
=> Remove LivecheckStrategy NAME requirement

Livecheckables/jpeg.rb
Updating `jpeg`'s regex to match within the stable archive's URL.
=> jpeg: update url and regex

Livecheckables/openrtsp.rb
Versions of `openrtsp` seem to be of the form YYYY.MM.DD, so I've used the standard `v?(\d+(?:\.\d+)+)` here, but I found this in the changelog:
```
2018.08.28a:
- Oops, the previous version wasn't building properly; it's fixed now.
```
So, I've used `v?(\d+(?:\.\d+)+[a-z]?)`.
=> openrtsp: update regex

.github/workflows/tests.yml
The `.github/workflows/tests.yml` file was recently updated and this included switching `runs-on` from `macOS-latest` to `ubuntu-latest`. Unfortunately, livecheck encounters some additional SSL errors on Ubuntu that we don't find on macOS (as seen in the `discount` formula in #1232), so it makes sense to switch this back to `macOS-latest`.
Either way, this will be a short-lived change, as this repository will be archived after the homebrew-core and Homebrew/brew migrations are complete (within a month).
=> workflows: revert to macOS-latest

Livecheckables/cscope.rb, Livecheckables/discount.rb, Livecheckables/fdclone.rb, Livecheckables/fig2dev.rb, Livecheckables/isc-dhcp.rb, Livecheckables/mksh.rb, Livecheckables/x264.rb
This PR updates regexes containing `0-9` and `a-z`.
Attention required:
* `cscope`: We were matching a version ending in `bl2`, hence the `*`
* `isc-dhcp`: Seems like it doesn't need `[a-z]`
* `mksh`: Made `R` optional (`R?` just like `v?`)
* `x264`: No change in capture group
=> Update regexes containing `a-z` and `0-9`

Livecheckables/readosm.rb
`readosm`'s [releases page](http://www.gaia-gis.it/gaia-sins/readosm-sources/) lists all older versions and the current one but the stable archive url we use in homebrew-core matches with the one on the homepage. Thus, the livecheckable url remains unchanged but the regex has been updated to match within the url of the stable archive.
=> readosm: update regex

Livecheckables/wwwoffle.rb
This brings the existing `wwwoffle` livecheckable up to current standards:
* Use `href=.*?` to match the file name within the `href` attribute, when applicable
* Use `v?(\d+(?:\.\d+)+[a-z]?)` instead of `([a-z0-9.]+)`, to be more clear about what we want to match
=> wwwoffle: update url and regex

livecheck/extend/formulary.rb
Due to recent changes in brew:
https://github.com/Homebrew/brew/commit/24eff8f81ac6bf50916a61bfa28fb9e4d950499a
https://github.com/Homebrew/brew/commit/08e35e9cb4e65c6969016ffaa8af4e1a968ca496
https://github.com/Homebrew/brew/commit/e07b02fde2a423ef6389330a80f4c3e5e71fcfed
Before this PR:
```
➜  homebrew/homebrew-livecheck stash master ✓  brew livecheck k3d --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/k3d.rb
Error: wrong number of arguments (given 5, expected 4)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/livecheck/extend/formulary.rb:14:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:61:in `load_formula_from_path' …
```
=> extend/formulary: fix formula loading

Livecheckables/pg_top.rb
The default check for `pg_top` has been loudly failing for quite some time, since the homepage was a Git repository that had been removed. The formula has been updated to use the current homepage instead (an HTML page) but the default check isn't able to work with any of the sources in the formula without a livecheckable.
This adds a livecheckable for `pg_top` that checks the current GitLab repository's tags. The newest stable version at the moment is still 3.7.0 but there are recent alpha versions of 4.0.0. The reason why I'm using the GitLab repo in this check is that the current stable source in the formula doesn't contain the 4.0.0 alpha releases, so we may miss the stable release in the future if we used that source. Once the stable 4.0.0 release occurs sometime in the future, we can …
=> pg_top: add livecheckable

cmd/livecheck.rb, livecheck/extend/livecheck.rb
This is an implementation of the oft-mentioned `strategy` feature (née `using`). As described in #301, the purpose of this is to specify the strategy to use in a livecheckable. This is the end result of a number of internal changes that enabled this feature to exist.
Specifying the `strategy` in a livecheckable is generally only necessary when the default strategy that livecheck selects isn't the one that we want. For example, the `Sourceforge` strategy may apply to a given URL but we want to use `PageMatch` instead.
An example of this is as follows:
```ruby
livecheck do
url :stable
strategy :page_match
regex(/href=.*?example[._-]v?(\d+(?:\.\d+)+)\.t/i)
end
```
The argument for `strategy` is a symbol corresponding to the strategy name (with an underscore between words, as in the strategy …
=> Add strategy to livecheck DSL

Livecheckables/acme.rb
Need help with this one @samford. Their [Changes.txt](https://sourceforge.net/p/acme-crossass/code-0/HEAD/tree/trunk/docs/Changes.txt) file shows a version `0.96.5`, but that doesn't show up in the RSS. Also, I think the RSS shows only Windows versions. What do we do for this Formula?
=> acme: add livecheckable

Livecheckables/popt.rb
This updates the regex in the existing livecheckable for `popt` to move the delimiter between the software name and version (i.e., `[._-]`) into the non-capturing group for the software name. This makes the preceding `popt-` part on tags like `popt-1.18-release` or `popt-1_2_3` optional, which was the actual intention here.
While I was at it, I updated the comment to reflect the current situation, as there's now a stable 1.18 release at http://ftp.rpm.org/popt/releases/popt-1.x/
=> popt: update regex and comment

livecheck/livecheck_strategy.rb
This is a simple change that establishes the idea that a `LivecheckStrategy` with a `PRIORITY` of zero (or lower) should be ignored. This allows us to create strategies that aren't applied by default but can be applied through certain conditions internally (e.g., `PageMatch`) or through `strategy :strategy_name` in a `livecheck` block.
This primarily benefits the `PageMatch` strategy, which already has a `PRIORITY` of `0` but we were manually omitting it in `LivecheckStrategy#from_url` (before conditionally including it when a `livecheck` block contains a `regex`).
Besides that, this could also be useful if/when we need to create a strategy that should only be manually applied through `strategy :strategy_name` in a `livecheck` block. For example, I'm working on a `GithubLatest` strategy …
=> Ignore strategies with a PRIORITY of zero or lower

livecheck/livecheck_strategy/page_match.rb
The `PageMatch` strategy is currently the only one without a `#match?` method, which causes us to have to defensively check `strategy.respond_to?(:match?)` before using `strategy.match?(url)`. I think it's reasonable to require `#match?` for all strategies (both internal and in taps), as `#match?` and `#from_url` are essential for livecheck to be able to apply strategies.
We've previously discussed having `PageMatch#match?` always return `true`. I think it makes sense to use something broad but more specific than just `true`. I've used `%r{^https?://}.match?(url)` here, as I think it makes sense to only apply the strategy to something over HTTP (since it fetches using `open-uri`).
Ideally, we would only apply this strategy to HTML pages, text files, etc. but that's something we could …
=> Add #match? method to PageMatch strategy

cmd/livecheck.rb, livecheck/livecheck_strategy/git.rb
Currently we have an issue where `brew livecheck --json` output isn't valid JSON if the run includes a Git error. Currently the `pg_top` formula produces a Git error (until/unless Homebrew/homebrew-core#56262 is merged) and it ends up being printed before the JSON:
```
fatal: repository 'https://git.postgresql.org/gitweb/?p=pg_top.git/' not found
[{"formula":"pg_top","status":"error","messages":["Unable to get versions"]}]
```
This PR is a first attempt at capturing Git errors in the JSON output. The JSON output on this branch follows the existing format for errors and contains the Git error in the `messages` array:
```json
[{"formula":"pg_top","status":"error","messages":["fatal: repository 'https://git.postgresql.org/gitweb/?p=pg_top.git/' not found"]}]
```
This implementation works …
=> Capture Git errors in JSON output

livecheck/extend/formulary.rb
Debug messages that use `odebug` are formatted differently than `puts ... if Homebrew.args.debug?` -- it helps quickly find them in the output.
=> Use odebug instead of puts... if Homebrew.args.debug?

.github/workflows/tests.yml
The homebrew-livecheck CI was recently changed to replace the `brew style` step with `brew test-bot --only-tap-syntax`. This was fine until some very recent CI-related changes outside of homebrew-livecheck modified the related behavior.
We're currently seeing audit failures for homebrew-core formulae on our CI here, which we certainly don't want. With this in mind, I discussed this with Dawid and it makes sense to revert the related CI step here back to `brew style`.
=> workflows: revert tap-syntax step to brew style

cmd/livecheck.rb, livecheck/livecheck_strategy/gnu.rb
This updates all the current usage of `Homebrew.args` to use an `args` variable instead. In line with how the Homebrew/brew commands handle this, I've updated the functions to accept a named `args` argument.
The instance in the `Gnu` strategy has simply been replaced with `odebug`, as that's more appropriate.
Closes #1248 (I discussed this with Seeker and they were fine with me opening this PR that closes theirs).
=> Update CLI::Parser args handling

Livecheckables/a52dec.rb, Livecheckables/avfs.rb, Livecheckables/bashdb.rb, Livecheckables/bcrypt.rb, Livecheckables/foremost.rb, Livecheckables/libmikmod.rb, Livecheckables/libwps.rb, Livecheckables/mikmod.rb, Livecheckables/netpbm.rb, Livecheckables/potrace.rb, Livecheckables/remake.rb, Livecheckables/zshdb.rb, livecheck/livecheck_strategy/sourceforge.rb
The `Sourceforge` strategy's `SPECIAL_CASES` array is no longer necessary now that we can manually specify the strategy to use in the `livecheck` block.
This modifies/adds related checks and removes the `SPECIAL_CASES` array. Some of these simply needed `strategy :page_match` in the `livecheck` block and others were seemingly fine to use the `Sourceforge` strategy at this point.
=> Remove Sourceforge strategy SPECIAL_CASES

Livecheckables/avrdude.rb, Livecheckables/clisp.rb, Livecheckables/cvs.rb, Livecheckables/dvdrtools.rb, Livecheckables/icoutils.rb, Livecheckables/kawa.rb, Livecheckables/lzip.rb, Livecheckables/mit-scheme.rb, Livecheckables/oath-toolkit.rb, livecheck/livecheck_strategy/gnu.rb
The `Gnu` strategy's `SPECIAL_CASES` array is no longer necessary now that we can manually specify the strategy to use in the `livecheck` block.
This modifies related checks to add `strategy :page_match` to the `livecheck` block and removes the `SPECIAL_CASES` array.
=> Remove Gnu strategy SPECIAL_CASES

Livecheckables/clzip.rb, Livecheckables/flvstreamer.rb, Livecheckables/gpsd.rb, Livecheckables/jcal.rb, Livecheckables/kimwitu++.rb, Livecheckables/libexosip.rb, Livecheckables/lout.rb, Livecheckables/m2c.rb, Livecheckables/man-db.rb, Livecheckables/nmh.rb, Livecheckables/oath-toolkit.rb, Livecheckables/png++.rb, Livecheckables/quilt.rb, Livecheckables/renameutils.rb, Livecheckables/treecc.rb, Livecheckables/z80asm.rb, livecheck/livecheck_strategy/gnu.rb
The `Gnu` strategy was matching Savannah GNU URLs like `https://download.savannah.gnu.org/releases/avrdude/avrdude-6.3.tar.gz` but these URLs aren't compatible with the strategy.
I worked on expanding the `Gnu` strategy to account for this but it wasn't as straightforward as the existing supported URLs. For the moment, I've simply added livecheckables for all the related formulae.
I've also updated the default regex for the `Gnu` strategy, as it was matching some files that it shouldn't (diffs, patches) and giving incorrect results. The changes here bring it more in line with our current standards as well.
=> Gnu: don't match Savannah URLs, update regex

Livecheckables/poppler.rb
The [`poppler` homepage](https://poppler.freedesktop.org) is sufficient to find the latest version and is only around 2 KB gzipped, whereas the [`releases.html` page](https://poppler.freedesktop.org/releases.html) is around 46 KB gzipped. It never hurts to save a little data, especially when we're checking thousands of formulae.
=> poppler: update url

Livecheckables/hevea.rb
This updates the existing livecheckable for `hevea` to use the directory index page where the stable archive is located and brings the regex up to current standards.
=> hevea: update url and regex

Livecheckables/fontconfig.rb
This updates the existing livecheckable for `fontconfig` to use the `stable` formula URL instead of the `homepage` and brings the regex up to current standards.
=> fontconfig: update url and regex

Livecheckables/cvs.rb, Livecheckables/podiff.rb, livecheck/livecheck_strategy/gnu.rb
In updating the `Gnu` strategy's `#match?` method  in #1257, I overlooked the fact that one of the `PROJECT_NAME_REGEXES` had a trailing `$` delimiter. This is an important detail, so I've incorporated it here. This causes the `Gnu` strategy to no longer match the `cvs` and `podiff` formulae, which is a desirable change.
Before, the default check for `podiff` was trying the `Gnu` strategy but this URL isn't compatible, so it gave a `404 Not Found` error. This also adds a livecheckable for `podiff` to establish a working check.
=> Gnu: update regex in match?

Livecheckables/clojure.rb
The current livecheck is not quite right, see the comment in [here](https://github.com/Homebrew/homebrew-core/pull/59478#issue-466121012).
Updating to track down the official installation page rather than the `homebrew-tools` one
---
```
$ brew livecheck clojure
clojure : 1.10.1.645 ==> 1.10.1.561
```
=> clojure: update url and regex

livecheck/livecheck_strategy/apache.rb
This brings the default regex for the Apache strategy up to date with some of our current standards.
* Use `\.t` instead of specific tarball extensions (e.g., .tar.gz)
* Use `href=["']?` instead of `href="`
* Use `v?` before the numeric version matching snippet
It's worth noting that we're using `href=["']?` here as it's less explicit than `href="`. We can't use the usual `href=.*?` snippet, as it ends up matching more than it should when it comes to directory names.
=> Apache: update regex to current standards

Livecheckables/ghc.rb, livecheck/livecheck_strategy/hackage.rb
This updates the `Hackage` strategy to also handle `downloads.haskell.org` URLs, which allows us to use it for `ghc`.
This also updates the way in which we identify the `package_name` to support file names like `ghc-8.10.1-src.tar.xz`. Before, we only supported file names like `Agda-2.6.1.tar.gz`, where the last hyphen we encounter is after the package name (i.e., there's no trailing `-src` after the numeric version).
=> Hackage: handle downloads.haskell.org URLs

Livecheckables/allureofthestars.rb, Livecheckables/bench.rb, Livecheckables/cryptol.rb, Livecheckables/darcs.rb, Livecheckables/dhall-bash.rb, Livecheckables/dhall-json.rb, Livecheckables/dhall-lsp-server.rb, Livecheckables/dhall-yaml.rb, Livecheckables/dhall.rb, Livecheckables/hledger.rb, Livecheckables/hlint.rb, Livecheckables/hopenpgp-tools.rb, Livecheckables/mighttpd2.rb, Livecheckables/pandoc-crossref.rb, Livecheckables/pandoc-include-code.rb, Livecheckables/pandoc.rb, Livecheckables/purescript.rb, Livecheckables/shelltestrunner.rb, Livecheckables/texmath.rb
Some of the Haskell formulae were checking the `head` Git repository in their formula and finding incorrect versions. Others were using the stable URL which uses `Hackage` strategy but we want to prevent this from breaking in the future if `head` is added to the formula.
In both of these cases, adding a livecheckable (or modifying an existing one) to simply use `url :stable` is appropriate.
=> Use stable for Haskell formulae

Livecheckables/widelands.rb
The default check for `widelands` returns a version like `build21` whereas the formula uses a version of `21`. This adds a livecheckable that uses a modified version the `Launchpad` strategy regex where we only capture the numeric version.
I considered updating the `Launchpad` strategy's default regex to account for this but I figured it may cause problems in the future if we encounter stable versions with some trailing non-digit content (e.g., `1.2.3a`). I may revisit this in the future but I'm holding off for the moment.
=> widelands: add livecheckable

Livecheckables/libmetalink.rb
This brings the regex in the existing livecheckable for `libmetalink` up to date with the default regex for the `Launchpad` strategy.
=> libmetalink: update regex

Livecheckables/bzrtools.rb
The `Launchpad` strategy doesn't work properly for `bzrtools` by default, since https://launchpad.net/bzrtools/ lists the latest version as `2.3.0` whereas the latest version on the https://launchpad.net/bzrtools/stable/ page is `2.6.0`. The formula uses a release from `/bzrtools/stable/`, so it's necessary to check that page to find the latest version.
It may be that we can modify the `Launchpad` strategy in some way to deal with this kind of situation but this livecheckable will work for now.
=> bzrtools: add livecheckable

Livecheckables/bazaar.rb, Livecheckables/byobu.rb, Livecheckables/bzr-builder.rb, Livecheckables/bzr-colo.rb, Livecheckables/bzr-externals.rb, Livecheckables/bzr-extmerge.rb, Livecheckables/bzr-rewrite.rb, Livecheckables/bzr-upload.rb, Livecheckables/bzr-xmloutput.rb, Livecheckables/duplicity.rb, Livecheckables/flowgrind.rb, Livecheckables/intltool.rb, Livecheckables/libmemcached.rb, Livecheckables/pastebinit.rb, Livecheckables/pbzip2.rb, Livecheckables/pipemeter.rb, Livecheckables/schroedinger.rb, Livecheckables/utimer.rb
All of the formulae that are using a launchpad.net `stable` URL are currently using the `Launchpad` strategy but this formalizes this in livecheckables using `url :stable`. This prevents the checks from breaking or giving an incorrect result if `head` is added to these formula in the future.
=> Use stable for Launchpad formulae

livecheck/livecheck_strategy/pypi.rb
This modifies the `Pypi` strategy to replace URL-encoded spaces (i.e., `%20`) in the `package_name` string with hyphens. This only affects one formula at the moment, which is `gimme-aws-creds`.
The file name in the stable URL of the `gimme-aws-creds` formula is like `gimme%20aws%20creds-2.3.4.tar.gz`, so the `package_name` string is `gimme%20aws%20creds`. This is a problem because it's used in the URL (and regex), leading to a 404 because this part of the URL should be `gimme-aws-creds`. The changes here resolve this situation and fix the broken check.
As usual, I did a comparison of the output without and with this change and the only affected formula was `gimme-aws-creds`, as described above.
=> Pypi: replace spaces in package_name with hyphens

Livecheckables/weboob.rb
Livecheck can't identify versions for `weboob` by default, so this adds a livecheckable which checks the upstream Git repository (where the stable archive comes from).
=> weboob: add livecheckable

Livecheckables/git-plus.rb, Livecheckables/pwncat.rb, Livecheckables/trezor-agent.rb, livecheck/livecheck_strategy/pypi.rb
This makes some changes to the `Pypi` strategy that resolve issues with specific formulae while bringing it more up to date with current regex standards.
* Use named capture groups to identify the package name and file name extension.
* Use `\.t` instead of specific tarball extensions (e.g., .tar.gz), as found in other strategies.
* Replace URL-encoded spaces (`%20`) and underscores in the package name with a hyphen but only for the`page_url`. We only do the replacement in the `page_url` because we need the original `package_name` for the default `regex`.
* Update the default regex to bring it up to current standards.
The `git-plus`, `pwncat`, and `trezor-agent` changes here depend on these changes, so I've included them here to wrap up livecheckable changes on the `Pypi` formulae.
=> Pypi: update page_url and regex creation

livecheck/livecheck_strategy/git.rb, livecheck/livecheck_strategy/gnu.rb
This integrates the replacement of `#empty?` with `#blank?` found in the Homebrew/brew migration strategies PR. This should make it ever-so-slightly easier to integrate strategy changes from this repository into that PR in the near future.
=> Use #blank? instead of #empty?

livecheck/livecheck_strategy/pypi.rb
There was a small typo in the `Pypi` strategy's regex for extracting parts of the URL, where `0=9` was used instead of `0-9` in a character class.
=> Pypi: fix typo in regex

Livecheckables/amap.rb
This adds a livecheckable for `amap` which checks the page for the "Tools" directory of the GitHub repository where the `stable` archive comes from. The THC-Archive repository's "Tools" directory simply contains archive files for various tools, so we can't check the Git repo tags or releases for versions like we would normally do.
=> amap: add livecheckable

Livecheckables/geomview.rb
This adds a livecheckable for `geomview` which checks the Debian directory index where the `stable` archive is found.
=> geomview: add livecheckable

Livecheckables/abook.rb
This adds a livecheckable for `abook` which checks the homepage, since that's where the stable archive comes from (not the SourceForge project files). We can't use `url :homepage` because the `https://abook.sourceforge.io` URL redirects to `http://abook.sourceforge.net` and we receive a `redirection forbidden` error.
=> abook: add livecheckable

Livecheckables/csound.rb
This adds a livecheckable for `csound` which checks the "latest" GitHub release, since `stable` uses a tag from the GitHub repository.
=> csound: add livecheckable

Livecheckables/igv.rb
The artifact is in the FTP server, it is good to livecheck against the FTP server rather than github tag.
The files are actually different btw FTP server and Github repo.
```
$ du -h igv*
52M	IGV_2.8.9.zip
118M	igv-2.8.10.zip
118M	igv-2.8.9.zip
```
```
$ brew livecheck igv
igv : 2.8.9 ==> 2.8.9
```
=> igv: update url and regex

Livecheckables/go@1.14.rb
relates to the recent go1.15 upgrade.
```
$ brew livecheck go@1.14
go@1.14 : 1.14.7 ==> 1.14.7
```
=> go@1.14: update url and regex

Livecheckables/helm@2.rb
helm 2.x is still actively maintained, it is good to keep it under the watch. The most recent release was three days back.
=> helm@2: add livecheckable

Livecheckables/go.rb
This updates the regex in the existing livecheckable for `go` to something closer to our current standards.
* Use `[._-]` between the software name and numeric version. In this case we make it optional since it's currently not part of the version format (e.g., `go1.15`).
* Use `[._-]src` in place of `\.src`, in case the format changes to `-src` or `_src` in the future.
=> go: update regex

Livecheckables/ivykis.rb
The existing livecheckable for `ivykis` checks the `homepage`, which is the SourceForge project. However, the `stable` archive currently comes from GitHub.
This updates the livecheckable to check the GitHub repo tags, as there's no "latest" version.
=> ivykis: update url and regex

Livecheckables/anycable-go.rb
using the current regex std to check against the latest tag of the formula.
```
$ brew livecheck anycable-go
anycable-go (guessed) : 1.0.0 ==> 1.0.1
```
```
$ brew livecheck anycable-go
anycable-go : 1.0.0 ==> 1.0.0
```
=> anycable-go: add livecheckable

Livecheckables/bde.rb
Using the current std way to populate this livecheckable.
```
$ brew livecheck bde
bde (guessed) : 3.59.0.2 ==> 20120129
```
```
$ brew livecheck bde
bde : 3.59.0.2 ==> 3.60.0.1
```
=> bde: add livecheckable

livecheck/livecheck_strategy/bitbucket.rb
This updates the `Bitbucket` strategy's regex to bring it more in line with our current standards.
This also makes tarball extensions in the `suffix` generic (i.e., `\.t`) as we do in other regexes. This helps to avoid the situation where the `stable` archive is a `.tar.gz` file but the upstream releases have moved to `.tar.xz` and we would miss the new releases if the regex was explicitly matching `.tar.gz`.
=> Bitbucket: Update regex

Livecheckables/connect.rb, Livecheckables/csv-fix.rb, Livecheckables/foma.rb, Livecheckables/fuse-zip.rb, Livecheckables/game-music-emu.rb, Livecheckables/groovyserv.rb, Livecheckables/jerasure.rb, Livecheckables/makeicns.rb, Livecheckables/mecab-ko-dic.rb, Livecheckables/mecab-ko.rb, Livecheckables/mpi4py.rb, Livecheckables/mvnvm.rb, Livecheckables/ode.rb, Livecheckables/ori.rb, Livecheckables/procyon-decompiler.rb, Livecheckables/pypy.rb, Livecheckables/pypy3.rb, Livecheckables/sagittarius-scheme.rb, Livecheckables/uru.rb, Livecheckables/vcprompt.rb, Livecheckables/vera++.rb, Livecheckables/walkmod.rb, Livecheckables/x265.rb
This adds/modifies livecheckables to use the `stable` URL for formulae with a `stable` URL that uses the `Bitbucket` strategy.
=> Use stable for Bitbucket formulae

Livecheckables/gcc@4.9.rb, Livecheckables/gcc@5.rb, Livecheckables/gcc@6.rb, Livecheckables/gcc@7.rb, Livecheckables/gcc@8.rb, Livecheckables/gcc@9.rb
This adds/modifies livecheckables for the various versioned `gcc` formulae, bringing them in line with the check for `gcc`.
=> Update versioned gcc checks

Livecheckables/gdcm.rb
This updates the existing livecheckable for `gdcm` to check the "latest" GitHub release, since the stable archives now come from the GitHub repository.
=> gdcm: update url and regex

Livecheckables/cppunit.rb, Livecheckables/libcdr.rb, Livecheckables/libetonyek.rb, Livecheckables/libfreehand.rb, Livecheckables/libmspub.rb, Livecheckables/libodfgen.rb, Livecheckables/libpagemaker.rb, Livecheckables/librevenge.rb, Livecheckables/libvisio.rb, Livecheckables/libwpd.rb, Livecheckables/libwpg.rb
This adds/modifies livecheckables that come from https://dev-www.libreoffice.org/src/, to standardize their URLs and regexes.
=> Add/update livecheckables for LibreOffice formulae

Livecheckables/aldo.rb, Livecheckables/atool.rb, Livecheckables/avrdude.rb, Livecheckables/dvdrtools.rb, Livecheckables/fastjar.rb, Livecheckables/icoutils.rb, Livecheckables/libntlm.rb, Livecheckables/lzip.rb, Livecheckables/normalize.rb, Livecheckables/tcc.rb
This adds livecheckables for `aldo`, `fastjar`, `libntlm`, `normalize`, and `tcc`, which come from download.savannah.gnu.org, download.savannah.nongnu.org, or www.nongnu.org.
This also updates some existing Savannah livecheckables to bring them in line with the others. This primarily involves removing `strategy :page_match` (for now), as it isn't explicitly necessary and I had only added it while working on potentially adding support for Savannah URLs to the `Gnu` formula earlier.
=> Add/update Savannah/non-GNU livecheckables

Livecheckables/onioncat.rb
The `onioncat` formula was recently updated from 0.2.8 (latest "stable" release) to 0.3.8 (latest "current" release). The existing livecheckable was previously checking the "stable" release folder but with the formula moving to a "current" release, it was necessary to update the livecheckable accordingly.
=> onioncat: update url

Livecheckables/aardvark_shell_utils.rb
The existing check for `aardvark_shell_utils` broke because downloads.laffeycomputer.com is currently missing. This updates the livecheckable to use the homepage instead, updating the regex accordingly.
=> aardvark_shell_utils: update url and regex

Livecheckables/bashdb.rb, Livecheckables/devil.rb, Livecheckables/gcc.rb, Livecheckables/gcc@4.9.rb, Livecheckables/gcc@5.rb, Livecheckables/gcc@6.rb, Livecheckables/gcc@7.rb, Livecheckables/gcc@8.rb, Livecheckables/gcc@9.rb, Livecheckables/geoserver.rb, Livecheckables/gtk+.rb, Livecheckables/libdc1394.rb, Livecheckables/pulseaudio.rb, Livecheckables/remake.rb, Livecheckables/safe-rm.rb, Livecheckables/uchardet.rb, Livecheckables/zboy.rb, Livecheckables/zshdb.rb
This should be most of the remaining formulae that could benefit from having a livecheckable using the stable URL (due to being compatible with an existing strategy).
For the related formulae that aren't using one of these strategies (i.e., using the `PageMatch` strategy due to a technical reason), I made sure to add explanatory comments where it made sense.
=> Use stable urls and explain exceptions

Livecheckables/qtads.rb
This adds a livecheckable for `qtads` which checks the upstream GitHub repository, as that's where new releases now reside. This may not stick around in the long run, as there was trouble updating the `qtads` formula to 3.0.0 and there was discussion of moving the formula to a cask instead. In the interim time, here we are.
=> qtads: add livecheckable

Livecheckables/imapsync.rb
The default check for `imapsync` was checking the Git repository tags but the latest tagged version is `1.945` whereas the release in the formula (not from GitHub) is `1.977`. This adds a livecheckable that checks for the latest version in the same location as the stable archive, which addresses the issue.
=> imapsync: add livecheckable

Livecheckables/gcab.rb, Livecheckables/gtk-doc.rb, Livecheckables/gtk-mac-integration.rb, Livecheckables/libart.rb, Livecheckables/libepoxy.rb, livecheck/livecheck_strategy/gnome.rb
This removes the `DEV_VERSION_ALLOWLIST` from the `Gnome` formula and adds appropriate regexes to the relevant livecheckables. This saves us from having to keep the allowlist up to date as formulae are added/removed while maintaining the same behavior for affected formulae.
Any checks that don't use GNOME's "even-numbered minor is stable" version scheme should simply override the default `Gnome` regex using a `livecheck` block, as these examples do.
=> Gnome: remove DEV_VERSION_ALLOWLIST

livecheck/strategy/apache.rb, livecheck/strategy/bitbucket.rb, livecheck/strategy/git.rb, livecheck/strategy/gnome.rb, livecheck/strategy/gnu.rb, livecheck/strategy/launchpad.rb, livecheck/strategy/npm.rb, livecheck/strategy/pypi.rb, livecheck/strategy/sourceforge.rb, livecheck/strategy/xorg.rb
* Identify the filename prefix in the URL and include it in the default regex, when available.
* Rename variables to bring them more in line with other strategy methods.
* Use `if stderr_str.present?` instead of `unless stderr_str.blank?`.
* Fix `^{}` removal from tags by using `gsub` instead (i.e., `delete_suffix` was a mistake in this context).
* Reduce regex specificity, to hopefully make it a little less fragile over time.
* Rework the `package_name` identification code to make it more understandable.
* Add `href=.*?` to the start of the default regex, to bring it more in line with current regex standards.
* Rename the `filename_end` variable to `suffix`, to bring it more in line with naming conventions in other strategies.
* Rename `package_name` to `module_name`, to reflect upstream …
=> Add various strategy tweaks

livecheck/strategy.rb, livecheck/strategy/apache.rb, livecheck/strategy/bitbucket.rb, livecheck/strategy/git.rb, livecheck/strategy/gnome.rb, livecheck/strategy/gnu.rb, livecheck/strategy/hackage.rb, livecheck/strategy/launchpad.rb, livecheck/strategy/npm.rb, livecheck/strategy/page_match.rb, livecheck/strategy/pypi.rb, livecheck/strategy/sourceforge.rb, livecheck/strategy/xorg.rb
The primary goals of this PR are to refactor the regexes in strategies to make them more comprehensible and to add documentation to explain how the strategies work in general.
Some of the changes here are as follows:
* Make the default priority for strategies a constant and explain the priority setup.
* Split complex regexes onto multiple lines and add explanatory comments, to help make them more understandable.
* Use named capture groups in regexes, where possible.
* Use `<<~EOS`/`EOS` instead of newlines in string literals.
* Uniformly use `Regexp#escape` when interpolating variables in strategy default regexes.
One thing to note is that I didn't split the default regex literals onto multiple lines. These regexes are printed in debug output and included in verbose JSON output, so …
=> Refactor and document strategies

Livecheckables/little-cms2.rb
The existing check for `little-cms2` checked the first-party "Download" page for new releases. The formula uses archives from SourceForge but a given release isn't official until it's on the first-party website.
The first-party website has been redesigned and there's no longer a "Download" page to check. Instead, our only option seems to be checking the posts in the blog "Releases" category. At the moment, this check is identifying versions by checking the blog post URLs. There's currently only one example and it looks like this: `http://littlecms.com/blog/2019/10/02/lcms2-2.11/`
There's no telling if this naming convention will remain consistent, so this check will need to be updated in the future if this doesn't hold true over time. The other options right now are to match text in the …
=> little-cms2: update url and regex

Livecheckables/pypy.rb, Livecheckables/pypy3.rb
The `pypy` and `pypy3` formulae recently switched to using stable archives from https://downloads.python.org. The existing `livecheck` blocks for these formulae simply used `url :stable`, since they previously used Bitbucket archive files.
This updates the existing checks to identify versions on the https://downloads.python.org/pypy/ directory listing page where the stable archives come from.
=> pypy, pypy3: update url and add regex

Livecheckables/atlassian-cli.rb
The URL for the Atlassian CLI page on the marketplace changed, so this updates it to the current location.
=> atlassian-cli: update url

Livecheckables/connect.rb, Livecheckables/csv-fix.rb, Livecheckables/makeicns.rb, Livecheckables/procyon-decompiler.rb, Livecheckables/vcprompt.rb
Bitbucket finally dropped support for Mercurial repositories relatively recently and these repositories were seemingly removed. Now some of these checks give a `403 Forbidden` response, so we're skipping these formulae for the time being.
If these weren't skipped, then the `Bitbucket` strategy would try to fetch these pages and always fail. We can easily update these `livecheck` blocks if any of these repositories reappear in the future.
=> Skip formulae with a missing Bitbucket repository

livecheck/strategy/apache.rb
The `path` parameter is a required part of Apache URLs to be able to use the `Apache` strategy, so it makes sense to make it an explicit part of the `URL_MATCH_REGEX`.
=> Apache: add path parameter to URL_MATCH_REGEX

livecheck/strategy/git.rb
The existing method of determining if a URL can be used with the `Git` strategy led to a situation where `#match?` would return `nil` if the URL doesn't match. The return value of `#match?` should always be a boolean and this ensures that's the case.
=> Git: ensure #match? returns a boolean value

livecheck/strategy/apache.rb, livecheck/strategy/bitbucket.rb, livecheck/strategy/git.rb, livecheck/strategy/gnome.rb, livecheck/strategy/gnu.rb, livecheck/strategy/hackage.rb, livecheck/strategy/launchpad.rb, livecheck/strategy/npm.rb, livecheck/strategy/page_match.rb, livecheck/strategy/pypi.rb, livecheck/strategy/sourceforge.rb, livecheck/strategy/xorg.rb
The strategies were converted to modules as part of the Homebrew/brew migration, to help ease the process of incorporating some changes from this repository into the related PRs in Homebrew/brew. We recently converted the strategies back to classes in one of those PRs, so this PR does the same thing here.
=> Convert strategies back to classes

Livecheckables/dolt.rb
```
$ brew livecheck dolt
dolt : 0.18.3 ==> 0.18.3
```
relates to https://github.com/Homebrew/homebrew-core/pull/60297
=> dolt: add livecheckable
